-- seed S2–S4 banda 1–2 (84 activities). Does not touch S1.
insert into public.activities (
  id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default,
  materiale, pasi, gata_cand, nota, tema_saptamana
) values
(
    's2-2-3-z1-fizic',
    '1-2',
    2,
    1,
    'fizic'::public.pillar,
    'Pași până la robinet',
    4,
    'A'::public.completion_mode,
    ARRAY['baie/bucătărie']::text[],
    ARRAY['Mergeți împreună până la apă.', 'Arătați robinetul: „Apă.”']::text[],
    'A mers până la sursa de apă.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z1-mental',
    '1-2',
    2,
    1,
    'mental'::public.pillar,
    'Uite apa',
    3,
    'A'::public.completion_mode,
    ARRAY['pahar/chiuvetă']::text[],
    ARRAY['Arătați apa curgând puțin.', '„Apă. Curge.”']::text[],
    'A privit apa.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z1-resurse',
    '1-2',
    2,
    1,
    'resurse'::public.pillar,
    'Paharul meu cu apă',
    4,
    'A'::public.completion_mode,
    ARRAY['pahar']::text[],
    ARRAY['Turnați puțin împreună.', '„Beau apă.”']::text[],
    'A ținut paharul sau a gustat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z1-social',
    '1-2',
    2,
    1,
    'social'::public.pillar,
    'Cer apă',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Modelați: „Vreau apă.”', 'Răspundeți când încearcă.']::text[],
    'A auzit / încercat cererea.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z2-fizic',
    '1-2',
    2,
    2,
    'fizic'::public.pillar,
    'Turnăm cu grijă',
    5,
    'A'::public.completion_mode,
    ARRAY['pahar, apă']::text[],
    ARRAY['Țineți mâna lui pe pahar.', 'Turnați puțin pe jos într-un vas.']::text[],
    'A ajutat la turnat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z2-mental',
    '1-2',
    2,
    2,
    'mental'::public.pillar,
    'Gol și plin',
    4,
    'A'::public.completion_mode,
    ARRAY['două pahare']::text[],
    ARRAY['Arătați gol, apoi plin.', '„Gol. Plin.”']::text[],
    'A văzut diferența.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z2-resurse',
    '1-2',
    2,
    2,
    'resurse'::public.pillar,
    'Udăm planta',
    5,
    'A'::public.completion_mode,
    ARRAY['plantă, apă']::text[],
    ARRAY['Turnați puțin la rădăcină.', '„Dăm apă plantei.”']::text[],
    'A ajutat la udat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z2-social',
    '1-2',
    2,
    2,
    'social'::public.pillar,
    'Beau cu tine',
    3,
    'A'::public.completion_mode,
    ARRAY['pahar']::text[],
    ARRAY['Beți împreună.', 'Zâmbiți, fără grabă.']::text[],
    'A băut lângă voi.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z3-fizic',
    '1-2',
    2,
    3,
    'fizic'::public.pillar,
    'Stropi pe mână',
    3,
    'A'::public.completion_mode,
    ARRAY['apă']::text[],
    ARRAY['Udați-i puțin dosul mâinii.', '„Ud. Rece.”']::text[],
    'A simțit stropii.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z3-mental',
    '1-2',
    2,
    3,
    'mental'::public.pillar,
    'Unde e paharul?',
    4,
    'A'::public.completion_mode,
    ARRAY['pahar']::text[],
    ARRAY['Pahar la vedere pe jumătate ascuns.', '„Unde e paharul?”']::text[],
    'A arătat / găsit paharul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z3-resurse',
    '1-2',
    2,
    3,
    'resurse'::public.pillar,
    'Ștergem apa',
    4,
    'A'::public.completion_mode,
    ARRAY['cârpă']::text[],
    ARRAY['Ștergeți o picătură împreună.', '„Ștergem.”']::text[],
    'A atins cârpa.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z3-social',
    '1-2',
    2,
    3,
    'social'::public.pillar,
    'Mulțumesc pentru apă',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['După băut: „Mulțumesc.”', 'Modelați voi.']::text[],
    'A auzit mulțumesc.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z4-fizic',
    '1-2',
    2,
    4,
    'fizic'::public.pillar,
    'Cărăm paharul gol',
    4,
    'A'::public.completion_mode,
    ARRAY['pahar gol plastic']::text[],
    ARRAY['Cărati 5 pași paharul gol.', '„Tu porți.”']::text[],
    'A cărat paharul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z4-mental',
    '1-2',
    2,
    4,
    'mental'::public.pillar,
    'Apă vs uscat',
    3,
    'A'::public.completion_mode,
    ARRAY['cârpă udă/uscată']::text[],
    ARRAY['Atingeți ambele.', '„Ud. Uscat.”']::text[],
    'A reacționat la diferență.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z4-resurse',
    '1-2',
    2,
    4,
    'resurse'::public.pillar,
    'Punem paharul la loc',
    3,
    'A'::public.completion_mode,
    ARRAY['pahar']::text[],
    ARRAY['Pahar pe masă/locul lui.', '„La loc.”']::text[],
    'A ajutat să pună paharul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z4-social',
    '1-2',
    2,
    4,
    'social'::public.pillar,
    'Împărțim o înghițitură',
    4,
    'A'::public.completion_mode,
    ARRAY['pahar']::text[],
    ARRAY['Voi beți, apoi el — fără forțare.', 'Rândul lui / rândul vostru.']::text[],
    'A acceptat sau refuzat clar.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z5-fizic',
    '1-2',
    2,
    5,
    'fizic'::public.pillar,
    'Dans cu stropi pe geam',
    4,
    'A'::public.completion_mode,
    ARRAY['geam, pulverizator opțional']::text[],
    ARRAY['Stropiți ușor geamul.', 'Mișcați degetul pe urmă.']::text[],
    'A atins geamul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z5-mental',
    '1-2',
    2,
    5,
    'mental'::public.pillar,
    'Ascultăm apa',
    3,
    'A'::public.completion_mode,
    ARRAY['robinet']::text[],
    ARRAY['Deschideți un fir de apă.', '„Auzi apa?”']::text[],
    'A orientat atenția.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z5-resurse',
    '1-2',
    2,
    5,
    'resurse'::public.pillar,
    'Opriți robinetul',
    3,
    'A'::public.completion_mode,
    ARRAY['robinet']::text[],
    ARRAY['Închideți împreună.', '„Oprit.”']::text[],
    'A văzut / ajutat la închis.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z5-social',
    '1-2',
    2,
    5,
    'social'::public.pillar,
    'Arătăm apei bunicii',
    5,
    'A'::public.completion_mode,
    ARRAY['opțional video scurt']::text[],
    ARRAY['Arătați paharul cuiva drag 1–2 min.', 'Salut scurt.']::text[],
    'A participat la arătat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z6-fizic',
    '1-2',
    2,
    6,
    'fizic'::public.pillar,
    'Băltoacă sau iarbă udă',
    6,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['Dacă e ud afară, pășiți lângă baltă (nu în adânc).', '„Apă jos.”']::text[],
    'A explorat zona udă cu adult.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z6-mental',
    '1-2',
    2,
    6,
    'mental'::public.pillar,
    'Nor sau soare',
    3,
    'A'::public.completion_mode,
    ARRAY['afară']::text[],
    ARRAY['Arătați cerul.', '„Nor. / Soare.”']::text[],
    'A privit cerul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z6-resurse',
    '1-2',
    2,
    6,
    'resurse'::public.pillar,
    'Adunăm 2 frunze ude',
    4,
    'A'::public.completion_mode,
    ARRAY['frunze']::text[],
    ARRAY['Luați 2 frunze, puneți-le jos la loc.', 'Numărați: una, două.']::text[],
    'A ținut o frunză.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z6-social',
    '1-2',
    2,
    6,
    'social'::public.pillar,
    'Joacă lângă adult la apă',
    8,
    'A'::public.completion_mode,
    ARRAY['vas mic apă']::text[],
    ARRAY['Voi turnați, el stă lângă.', 'Comentați ce face, fără a prelua.']::text[],
    'A stat lângă joc 2–3 min.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z7-fizic',
    '1-2',
    2,
    7,
    'fizic'::public.pillar,
    'Plimbare liberă scurtă',
    8,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['El dictează.', 'Voi numiți apa/plantă dacă arată.']::text[],
    'A explorat ≥5 min.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z7-mental',
    '1-2',
    2,
    7,
    'mental'::public.pillar,
    'Carte cu apă / baie',
    5,
    'A'::public.completion_mode,
    ARRAY['carte']::text[],
    ARRAY['Pagini cu apă dacă aveți; altfel orice carte.', 'El întoarce.']::text[],
    'A rămas scurt la carte.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z7-resurse',
    '1-2',
    2,
    7,
    'resurse'::public.pillar,
    'Prosopul la loc',
    4,
    'A'::public.completion_mode,
    ARRAY['prosop']::text[],
    ARRAY['După baie/mână: prosopul pe cârlig.', '„La loc.”']::text[],
    'A ajutat cu prosopul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's2-2-3-z7-social',
    '1-2',
    2,
    7,
    'social'::public.pillar,
    'Noapte bună',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['„Noapte bună.”', 'Lumină mică.']::text[],
    'A participat la ritual.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Apa în casă și afară'
  ),
(
    's3-2-3-z1-fizic',
    '1-2',
    3,
    1,
    'fizic'::public.pillar,
    'Pași care se aud',
    4,
    'A'::public.completion_mode,
    ARRAY['podea']::text[],
    ARRAY['Mergeți apăsat puțin.', '„Auzi pașii?”']::text[],
    'A mers și a auzit.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z1-mental',
    '1-2',
    3,
    1,
    'mental'::public.pillar,
    'Liniște 10 secunde',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Stați liniștiți scurt.', '„Liniște.”']::text[],
    'A tolerat liniștea scurt.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z1-resurse',
    '1-2',
    3,
    1,
    'resurse'::public.pillar,
    'Jucăria care face zgomot',
    4,
    'A'::public.completion_mode,
    ARRAY['jucărie sonoră']::text[],
    ARRAY['Un sunet, apoi stop.', '„Sunet. Stop.”']::text[],
    'A reacționat la sunet.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z1-social',
    '1-2',
    3,
    1,
    'social'::public.pillar,
    'Strigăm pe nume blând',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Spuneți numele lui blând.', 'Așteptați privirea.']::text[],
    'A întors privirea.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z2-fizic',
    '1-2',
    3,
    2,
    'fizic'::public.pillar,
    'Bătăi din palme',
    4,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Bateți din palme împreună.', '2–5 bătăi.']::text[],
    'A încercat să bată.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z2-mental',
    '1-2',
    3,
    2,
    'mental'::public.pillar,
    'Unde e sunetul?',
    4,
    'A'::public.completion_mode,
    ARRAY['telefon/jucărie']::text[],
    ARRAY['Sunet din altă parte a camerei.', '„Unde?”']::text[],
    'A orientat spre sunet.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z2-resurse',
    '1-2',
    3,
    2,
    'resurse'::public.pillar,
    'Pune jucăria sonoră la loc',
    3,
    'A'::public.completion_mode,
    ARRAY['jucărie']::text[],
    ARRAY['După joacă: în cutie.', '„La loc.”']::text[],
    'A ajutat la pus.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z2-social',
    '1-2',
    3,
    2,
    'social'::public.pillar,
    'Ascultăm împreună',
    5,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Stați ureche la ureche pe o fereastră.', '„Auzim.”']::text[],
    'A stat lângă voi scurt.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z3-fizic',
    '1-2',
    3,
    3,
    'fizic'::public.pillar,
    'Dans pe o melodie scurtă',
    4,
    'A'::public.completion_mode,
    ARRAY['muzică']::text[],
    ARRAY['30–60 sec muzică.', 'Stop.']::text[],
    'S-a mișcat pe ritm.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z3-mental',
    '1-2',
    3,
    3,
    'mental'::public.pillar,
    'Voce tare / voce încet',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Spuneți același cuvânt tare, apoi încet.', '„Tare. Încet.”']::text[],
    'A reacționat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z3-resurse',
    '1-2',
    3,
    3,
    'resurse'::public.pillar,
    'Oprim muzica',
    3,
    'A'::public.completion_mode,
    ARRAY['telefon/boxă']::text[],
    ARRAY['Apăsați stop împreună.', '„Oprit.”']::text[],
    'A văzut oprirea.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z3-social',
    '1-2',
    3,
    3,
    'social'::public.pillar,
    'Cântec scurt cu familia',
    5,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Un refren cunoscut, 1 min.', 'Fără forțare să cânte.']::text[],
    'A auzit cântecul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z4-fizic',
    '1-2',
    3,
    4,
    'fizic'::public.pillar,
    'Sărituri pe bătăi',
    4,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Bateți din palme, săritură mică.', '2–4.']::text[],
    'A sărit sau a încercat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z4-mental',
    '1-2',
    3,
    4,
    'mental'::public.pillar,
    'Pasăre sau mașină',
    4,
    'A'::public.completion_mode,
    ARRAY['afară']::text[],
    ARRAY['Ascultați.', '„Pasăre? Mașină?”']::text[],
    'A orientat atenția afară.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z4-resurse',
    '1-2',
    3,
    4,
    'resurse'::public.pillar,
    'Închidem ușa încet',
    3,
    'A'::public.completion_mode,
    ARRAY['ușă']::text[],
    ARRAY['Închideți fără trântit.', '„Încet.”']::text[],
    'A participat la închis.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z4-social',
    '1-2',
    3,
    4,
    'social'::public.pillar,
    'Rândul la sunet',
    4,
    'A'::public.completion_mode,
    ARRAY['tobe/jucărie']::text[],
    ARRAY['Tu o dată, el o dată.', '„Acum tu.”']::text[],
    'A încercat rândul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z5-fizic',
    '1-2',
    3,
    5,
    'fizic'::public.pillar,
    'Mers pe vârfuri (încercare)',
    4,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Arătați mers ușor.', 'Câțiva pași.']::text[],
    'A încercat mers ușor.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z5-mental',
    '1-2',
    3,
    5,
    'mental'::public.pillar,
    'Numim 3 sunete din casă',
    4,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Frigider, apă, voce — ce aveți.', 'Arătați sursa.']::text[],
    'A privit sursele.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z5-resurse',
    '1-2',
    3,
    5,
    'resurse'::public.pillar,
    'Telefonul pe silent (model)',
    3,
    'A'::public.completion_mode,
    ARRAY['telefon']::text[],
    ARRAY['Puneți pe silent vizibil.', '„Liniște acum.”']::text[],
    'A văzut gestul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z5-social',
    '1-2',
    3,
    5,
    'social'::public.pillar,
    'Salut pe voce',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['„Bună!” cu zâmbet.', 'Așteptați răspunsul lui.']::text[],
    'A reacționat la salut.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z6-fizic',
    '1-2',
    3,
    6,
    'fizic'::public.pillar,
    'Afară: pași pe pietriș/iarbă',
    6,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['Texturi care sună diferit.', '„Auzi?”']::text[],
    'A pășit pe 2 texturi.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z6-mental',
    '1-2',
    3,
    6,
    'mental'::public.pillar,
    'Vântul se aude?',
    3,
    'A'::public.completion_mode,
    ARRAY['afară']::text[],
    ARRAY['Stați 15 sec.', '„Vânt.” / „Liniște.”']::text[],
    'A ascultat afară.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z6-resurse',
    '1-2',
    3,
    6,
    'resurse'::public.pillar,
    'Aducem o piatră care nu sună',
    4,
    'A'::public.completion_mode,
    ARRAY['piatră']::text[],
    ARRAY['Comparați cu jucăria sonoră.', 'Piatra la loc.']::text[],
    'A ținut piatra.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z6-social',
    '1-2',
    3,
    6,
    'social'::public.pillar,
    'Joacă paralel + comentariu',
    8,
    'A'::public.completion_mode,
    ARRAY['jucării']::text[],
    ARRAY['Comentați sunetele pe care le face el.', 'Nu preluați jocul.']::text[],
    'A jucat lângă voi.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z7-fizic',
    '1-2',
    3,
    7,
    'fizic'::public.pillar,
    'Plimbare liberă',
    8,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['El dictează.', 'Voi numiți sunete dacă apar.']::text[],
    'A explorat ≥5 min.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z7-mental',
    '1-2',
    3,
    7,
    'mental'::public.pillar,
    'Carte liniștită',
    5,
    'A'::public.completion_mode,
    ARRAY['carte']::text[],
    ARRAY['Fără ecrane.', 'Pagini încet.']::text[],
    'A rămas la carte scurt.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z7-resurse',
    '1-2',
    3,
    7,
    'resurse'::public.pillar,
    'Lumina stinsă încet',
    3,
    'A'::public.completion_mode,
    ARRAY['întrerupător']::text[],
    ARRAY['Stingeți cu adult.', '„Stins. Liniște.”']::text[],
    'A văzut stingerea.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's3-2-3-z7-social',
    '1-2',
    3,
    7,
    'social'::public.pillar,
    'Noapte bună șoptit',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Șoaptă: „Noapte bună.”', 'Calm.']::text[],
    'A participat la ritual.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Sunete și liniște'
  ),
(
    's4-2-3-z1-fizic',
    '1-2',
    4,
    1,
    'fizic'::public.pillar,
    'Deschide și strânge pumnul',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Arătați.', 'Repetați de 3 ori.']::text[],
    'A mișcat degetele.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z1-mental',
    '1-2',
    4,
    1,
    'mental'::public.pillar,
    'Arată degetul',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['„Uite degetul.”', 'Atingeți-i palma.']::text[],
    'A privit mâna.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z1-resurse',
    '1-2',
    4,
    1,
    'resurse'::public.pillar,
    'Punem capacul (mare)',
    5,
    'A'::public.completion_mode,
    ARRAY['cutie/capac mare']::text[],
    ARRAY['Capac pe cutie împreună.', 'Fără frustrare.']::text[],
    'A atins capacul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z1-social',
    '1-2',
    4,
    1,
    'social'::public.pillar,
    'Ținem mâna',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Oferiți mâna.', 'Nu forțați.']::text[],
    'A acceptat sau refuzat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z2-fizic',
    '1-2',
    4,
    2,
    'fizic'::public.pillar,
    'Culegem 3 obiecte cu mâna',
    5,
    'A'::public.completion_mode,
    ARRAY['jucării mici sigure']::text[],
    ARRAY['Una, două, trei în cutie.', 'El ia ce poate.']::text[],
    'A pus ≥1 obiect.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z2-mental',
    '1-2',
    4,
    2,
    'mental'::public.pillar,
    'Mare și mic',
    4,
    'A'::public.completion_mode,
    ARRAY['2 obiecte']::text[],
    ARRAY['„Mare. Mic.”', 'El arată.']::text[],
    'A văzut diferența.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z2-resurse',
    '1-2',
    4,
    2,
    'resurse'::public.pillar,
    'Turnăm boabe mari în bol',
    5,
    'A'::public.completion_mode,
    ARRAY['boabe/piese mari, bol']::text[],
    ARRAY['Una câte una.', 'Stop la oboseală.']::text[],
    'A turnat ≥1.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z2-social',
    '1-2',
    4,
    2,
    'social'::public.pillar,
    'Dăm obiectul din mână în mână',
    4,
    'A'::public.completion_mode,
    ARRAY['jucărie']::text[],
    ARRAY['„Ține. Dă înapoi.”', '2 schimburi.']::text[],
    'A dat / primit.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z3-fizic',
    '1-2',
    4,
    3,
    'fizic'::public.pillar,
    'Bate ritm cu degetele pe masă',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Taptap ușor.', 'El imită.']::text[],
    'A atins masa ritmic.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z3-mental',
    '1-2',
    4,
    3,
    'mental'::public.pillar,
    'Unde e mânuța?',
    3,
    'A'::public.completion_mode,
    ARRAY['mănușă/mână sub cârpă']::text[],
    ARRAY['„Unde e mânuța?”', 'Descoperiți.']::text[],
    'A căutat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z3-resurse',
    '1-2',
    4,
    3,
    'resurse'::public.pillar,
    'Trag fermuarul (cu ajutor)',
    4,
    'A'::public.completion_mode,
    ARRAY['haină cu fermoar']::text[],
    ARRAY['Trageți împreună puțin.', '„Sus. Jos.”']::text[],
    'A ținut fermoarul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z3-social',
    '1-2',
    4,
    3,
    'social'::public.pillar,
    'Gâdilat blând pe palmă',
    2,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Blând, oprire imediat dacă nu vrea.']::text[],
    'A râs sau a retras mâna clar.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z4-fizic',
    '1-2',
    4,
    4,
    'fizic'::public.pillar,
    'Împingem o cutie ușoară',
    4,
    'A'::public.completion_mode,
    ARRAY['cutie']::text[],
    ARRAY['5 pași.', '„Împinge.”']::text[],
    'A împins cutia.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z4-mental',
    '1-2',
    4,
    4,
    'mental'::public.pillar,
    'Degete: unul, două',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Arătați 1, apoi 2 degete.', '„Unu. Doi.”']::text[],
    'A privit degetele.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z4-resurse',
    '1-2',
    4,
    4,
    'resurse'::public.pillar,
    'Ștergem masa cu cârpă',
    4,
    'A'::public.completion_mode,
    ARRAY['cârpă']::text[],
    ARRAY['Mișcări scurte.', '„Curat.”']::text[],
    'A ținut cârpa.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z4-social',
    '1-2',
    4,
    4,
    'social'::public.pillar,
    'High-five blând',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Oferiți palma.', 'Fără forțare.']::text[],
    'A atins palma sau a refuzat.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z5-fizic',
    '1-2',
    4,
    5,
    'fizic'::public.pillar,
    'Urcăm pe mâini pe pernă (târâit)',
    5,
    'A'::public.completion_mode,
    ARRAY['pernă/saltea']::text[],
    ARRAY['Târâit pe pernă.', 'Scurt.']::text[],
    'A încercat târâitul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z5-mental',
    '1-2',
    4,
    5,
    'mental'::public.pillar,
    'Pipăie moale / aspru',
    4,
    'A'::public.completion_mode,
    ARRAY['două texturi']::text[],
    ARRAY['„Moale. Aspru.”']::text[],
    'A atins ambele.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z5-resurse',
    '1-2',
    4,
    5,
    'resurse'::public.pillar,
    'Punem șoseta la loc',
    4,
    'A'::public.completion_mode,
    ARRAY['șosetă']::text[],
    ARRAY['În sertar/coș.', '„La loc.”']::text[],
    'A ajutat cu șoseta.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z5-social',
    '1-2',
    4,
    5,
    'social'::public.pillar,
    'Mână pe umărul adultului',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['El pune mâna pe umărul vostru.', 'Modelați.']::text[],
    'A atins umărul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z6-fizic',
    '1-2',
    4,
    6,
    'fizic'::public.pillar,
    'Săpat cu mâna în nisip/pământ',
    6,
    'A'::public.completion_mode,
    ARRAY['curte/nisip']::text[],
    ARRAY['Săpați puțin împreună.', 'Fără murdărie în ochi.']::text[],
    'A săpat / atins pământul.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z6-mental',
    '1-2',
    4,
    6,
    'mental'::public.pillar,
    'Piatră sau frunză în mână',
    3,
    'A'::public.completion_mode,
    ARRAY['piatră, frunză']::text[],
    ARRAY['„Piatră. Frunză.”']::text[],
    'A ținut pe rând.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z6-resurse',
    '1-2',
    4,
    6,
    'resurse'::public.pillar,
    'Găleata la loc',
    4,
    'A'::public.completion_mode,
    ARRAY['găleată']::text[],
    ARRAY['După joacă: găleata pe locul ei.']::text[],
    'A împins / dus găleata.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z6-social',
    '1-2',
    4,
    6,
    'social'::public.pillar,
    'Joacă paralel cu mâinile',
    8,
    'A'::public.completion_mode,
    ARRAY['nisip/jucării']::text[],
    ARRAY['Voi săpați lângă.', 'Comentați mâinile lui.']::text[],
    'A jucat lângă voi.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z7-fizic',
    '1-2',
    4,
    7,
    'fizic'::public.pillar,
    'Plimbare + ținut un obiect',
    8,
    'A'::public.completion_mode,
    ARRAY['curte, obiect ușor']::text[],
    ARRAY['El ține ceva ușor în mână.', 'Voi supravegheați.']::text[],
    'A mers ținând obiectul scurt.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z7-mental',
    '1-2',
    4,
    7,
    'mental'::public.pillar,
    'Carte: el întoarce pagina',
    5,
    'A'::public.completion_mode,
    ARRAY['carte']::text[],
    ARRAY['Ajutați doar dacă blochează.']::text[],
    'A întors ≥1 pagină.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z7-resurse',
    '1-2',
    4,
    7,
    'resurse'::public.pillar,
    'Haina pe cârlig',
    4,
    'A'::public.completion_mode,
    ARRAY['haină']::text[],
    ARRAY['După afară.', '„La loc.”']::text[],
    'A ajutat cu haina.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  ),
(
    's4-2-3-z7-social',
    '1-2',
    4,
    7,
    'social'::public.pillar,
    'Pup / îmbrățișare de noapte',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Oferiți; acceptă/refuză ok.', '„Noapte bună.”']::text[],
    'A participat la ritual.',
    'Vârsta 1–2: scurt, fără forțare; el poate refuza.',
    'Mâini și degete'
  )
on conflict (id) do update set
  banda = excluded.banda,
  saptamana = excluded.saptamana,
  zi = excluded.zi,
  pilon = excluded.pilon,
  titlu = excluded.titlu,
  durata_min = excluded.durata_min,
  mod_default = excluded.mod_default,
  materiale = excluded.materiale,
  pasi = excluded.pasi,
  gata_cand = excluded.gata_cand,
  nota = excluded.nota,
  tema_saptamana = excluded.tema_saptamana;
