insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s21-2-3-z1-fizic', '1-2', 21, 1, 'fizic'::public.pillar, 'Mâna pe geam pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la geam. Atingeți sticla pe scurt.', '„Geam. Rece.” 10–20 de secunde.']::text[], 'A atins geamul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z1-mental', '1-2', 21, 1, 'mental'::public.pillar, 'Geam și afară', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați geamul: „Geam.”', 'Arătați afară: „Afară.”']::text[], 'A privit geamul sau afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z1-resurse', '1-2', 21, 1, 'resurse'::public.pillar, 'Perdeaua la loc', 4, 'A'::public.completion_mode, ARRAY['perdea sau draperie']::text[], ARRAY['Trageți perdeaua pe scurt împreună.', '„Perdea. La loc.”']::text[], 'A ajutat să miște perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z1-social', '1-2', 21, 1, 'social'::public.pillar, 'Privim geamul împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul la geam.', '„Împreună. Geam.” fără grabă.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z2-fizic', '1-2', 21, 2, 'fizic'::public.pillar, 'Deget pe geam rece', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți geamul cu un deget.', '„Rece. Deget.” pe scurt.']::text[], 'A atins geamul cu degetul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z2-mental', '1-2', 21, 2, 'mental'::public.pillar, 'Gheață pe geam dacă se vede', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă e gheață sau abur: „Gheață.” sau „Abur.”', 'Arătați cu degetul fără a forța.']::text[], 'A auzit cuvântul și a privit geamul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z2-resurse', '1-2', 21, 2, 'resurse'::public.pillar, 'Cârpa de geam pe scurt', 4, 'A'::public.completion_mode, ARRAY['cârpă uscată']::text[], ARRAY['Ștergeți un colț de geam împreună.', 'Puneți cârpa la loc: „La loc.”']::text[], 'A atins cârpa sau a ajutat la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s21-2-3-z2-social', '1-2', 21, 2, 'social'::public.pillar, 'Arătăm geamul adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Uite geamul.”', 'Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z3-fizic', '1-2', 21, 3, 'fizic'::public.pillar, 'De la geam la canapea caldă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați 10 secunde la geam.', 'Mergeți pe canapea: „Cald. Canapea.”']::text[], 'A mers de la geam la canapea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z3-mental', '1-2', 21, 3, 'mental'::public.pillar, 'Rece afară, cald în casă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam: „Rece.” pe scurt.', 'În cameră: „Cald. Casă.”']::text[], 'A auzit rece și cald.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z3-resurse', '1-2', 21, 3, 'resurse'::public.pillar, 'Pătura pe canapea', 4, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Luați pătura. Așezați-o pe canapea.', '„Pătură. La loc.” pe scurt.']::text[], 'A ajutat cu pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z3-social', '1-2', 21, 3, 'social'::public.pillar, 'Ne încălzim împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe canapea unul lângă altul.', '„Împreună. Cald.” fără forțare.']::text[], 'A șezut lângă voi pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z4-fizic', '1-2', 21, 4, 'fizic'::public.pillar, 'Suflăm pe geam pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Suflați blând pe geam o dată.', '„Suflu. Abur.” dacă apare.']::text[], 'A suflat sau a privit aburul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z4-mental', '1-2', 21, 4, 'mental'::public.pillar, 'Abur pe geam', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați aburul dacă e: „Abur.”', 'Atingeți cu degetul pe scurt: „Uite.”']::text[], 'A privit sau a atins aburul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s21-2-3-z4-resurse', '1-2', 21, 4, 'resurse'::public.pillar, 'Ștergem aburul și cârpa la loc', 4, 'A'::public.completion_mode, ARRAY['cârpă uscată']::text[], ARRAY['Ștergeți aburul pe scurt.', '„Cârpă. La loc.”']::text[], 'A ajutat să șteargă sau să pună cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z4-social', '1-2', 21, 4, 'social'::public.pillar, 'Suflăm pe rând pe geam', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi suflați. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z5-fizic', '1-2', 21, 5, 'fizic'::public.pillar, 'Pervazul: mână pe pervaz', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți pervazul cu mâna.', '„Pervaz.” 10–15 de secunde.']::text[], 'A atins pervazul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z5-mental', '1-2', 21, 5, 'mental'::public.pillar, 'Lumină la geam', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați lumina de la geam: „Lumină.”', 'Apoi camera: „Cameră.”']::text[], 'A privit lumina sau camera.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z5-resurse', '1-2', 21, 5, 'resurse'::public.pillar, 'Obiectul de pe pervaz la loc', 4, 'A'::public.completion_mode, ARRAY['un obiect de pe pervaz']::text[], ARRAY['Luați obiectul pe scurt.', 'Puneți-l la loc: „La loc. Pervaz.”']::text[], 'A ajutat să pună obiectul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z5-social', '1-2', 21, 5, 'social'::public.pillar, 'Pervazul cu adultul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la pervaz lângă adult.', '„Împreună. Pervaz.”']::text[], 'A stat lângă adult la pervaz.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z6-fizic', '1-2', 21, 6, 'fizic'::public.pillar, 'Geam, apoi pași în casă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Privire scurtă la geam.', 'Câteva pași prin cameră: „În casă. Cald.”']::text[], 'A privit geamul și a mers în casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s21-2-3-z6-mental', '1-2', 21, 6, 'mental'::public.pillar, 'Iarnă afară, casă caldă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam: „Iarnă.” pe scurt.', 'În cameră: „Casă. Cald.”']::text[], 'A auzit iarnă și casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z6-resurse', '1-2', 21, 6, 'resurse'::public.pillar, 'Șosetele la loc după geam', 4, 'A'::public.completion_mode, ARRAY['pereche de șosete']::text[], ARRAY['Dacă ați scos șosetele, puneți-le la loc.', '„Șosete. La loc.”']::text[], 'A ajutat cu șosetele la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z6-social', '1-2', 21, 6, 'social'::public.pillar, 'Spunem adultului: geam rece', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Geam. Rece.”', 'Stați pe scurt, fără grabă.']::text[], 'A fost prezent la spus.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z7-fizic', '1-2', 21, 7, 'fizic'::public.pillar, 'Plimbare liberă în casă, geam la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.', 'La final: o privire la geam dacă vrea.']::text[], 'A mers liber; a privit geamul sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z7-mental', '1-2', 21, 7, 'mental'::public.pillar, 'Carte: iarnă și casă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați un geam sau zăpadă dacă e clar: „Iarnă.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z7-resurse', '1-2', 21, 7, 'resurse'::public.pillar, 'Cartea și pătura pe raft', 4, 'A'::public.completion_mode, ARRAY['carte', 'pătură mică']::text[], ARRAY['Puneți cartea pe raft, pătura pe canapea.', '„La loc.”']::text[], 'A ajutat cu cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz'),
('s21-2-3-z7-social', '1-2', 21, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Iarna pe pervaz')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s22-2-3-z1-fizic', '1-2', 22, 1, 'fizic'::public.pillar, 'Balans ușor pe loc', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe loc. Balanșați corpul stânga-dreapta.', '„Dans. Corp.” 15–20 de secunde.']::text[], 'A balanșat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z1-mental', '1-2', 22, 1, 'mental'::public.pillar, 'Corp care se mișcă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați corpul: „Corp.”', 'Mișcați brațele: „Mișcare.”']::text[], 'A auzit corp și mișcare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z1-resurse', '1-2', 22, 1, 'resurse'::public.pillar, 'Spațiu liber pe jos', 4, 'A'::public.completion_mode, ARRAY['1–2 obiecte pe jos']::text[], ARRAY['Puneți 1–2 obiecte la loc ca să fie loc de mișcare.', '„La loc. Liber.”']::text[], 'A ajutat să elibereze spațiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z1-social', '1-2', 22, 1, 'social'::public.pillar, 'Dansăm împreună pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați împreună 20–30 de secunde.', '„Împreună. Dans.” fără forțare.']::text[], 'A balanșat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z2-fizic', '1-2', 22, 2, 'fizic'::public.pillar, 'Târâit pe jos 5–10 pași', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți în patru labe 5–10 pași dacă vrea.', '„Târâit. Pași.” pe scurt.']::text[], 'A încercat târâitul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z2-mental', '1-2', 22, 2, 'mental'::public.pillar, 'Jos pe podea', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți podeaua: „Jos.”', 'Apoi stați: „Sus.” pe scurt.']::text[], 'A auzit jos și sus.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z2-resurse', '1-2', 22, 2, 'resurse'::public.pillar, 'Covorul / zona de joacă liberă', 4, 'A'::public.completion_mode, ARRAY['jucărie pe covor']::text[], ARRAY['Puneți o jucărie de pe covor la loc.', '„La loc. Covor.”']::text[], 'A ajutat cu jucăria pe raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s22-2-3-z2-social', '1-2', 22, 2, 'social'::public.pillar, 'Târâim pe rând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi faceți 2–3 pași în patru labe. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z3-fizic', '1-2', 22, 3, 'fizic'::public.pillar, 'Sărituri mici pe loc', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Două-trei sărituri mici pe loc.', '„Săritură.” pe scurt, fără grabă.']::text[], 'A sărit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z3-mental', '1-2', 22, 3, 'mental'::public.pillar, 'Unu, doi — sărituri', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['O săritură: „Unu.”', 'A doua dacă vrea: „Doi.”']::text[], 'A auzit unu și doi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z3-resurse', '1-2', 22, 3, 'resurse'::public.pillar, 'Pernuța pe canapea după sărituri', 4, 'A'::public.completion_mode, ARRAY['pernă mică']::text[], ARRAY['Dacă ați folosit o pernă, puneți-o pe canapea.', '„Pernă. La loc.”']::text[], 'A ajutat cu perna la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z3-social', '1-2', 22, 3, 'social'::public.pillar, 'Sărim lângă adult', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Una-două sărituri lângă adult.', '„Împreună.” fără forțare.']::text[], 'A sărit sau a privit lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z4-fizic', '1-2', 22, 4, 'fizic'::public.pillar, 'Brațe sus și jos', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați brațele: „Sus.”', 'Coborâți: „Jos.” de 2–3 ori.']::text[], 'A mișcat brațele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z4-mental', '1-2', 22, 4, 'mental'::public.pillar, 'Sus și jos cu brațele', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Sus.” brațe sus.', 'Arătați: „Jos.” brațe jos.']::text[], 'A auzit sus și jos.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s22-2-3-z4-resurse', '1-2', 22, 4, 'resurse'::public.pillar, 'Jucăria de dans la loc', 4, 'A'::public.completion_mode, ARRAY['jucărie ținută în mână']::text[], ARRAY['Duceți jucăria pe raft după mișcare.', '„La loc.”']::text[], 'A ajutat să pună jucăria la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z4-social', '1-2', 22, 4, 'social'::public.pillar, 'Brațe sus împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați brațele împreună o dată.', '„Împreună. Sus.”']::text[], 'A ridicat brațele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z5-fizic', '1-2', 22, 5, 'fizic'::public.pillar, 'Pași pe loc în casă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Marșați pe loc 10–15 secunde.', '„Pași. Pe loc.”']::text[], 'A făcut pași pe loc sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z5-mental', '1-2', 22, 5, 'mental'::public.pillar, 'Mișcare, apoi gata', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Câteva mișcări. Apoi mâinile pe genunchi.', '„Gata. Corp calm.”']::text[], 'A auzit gata după mișcare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z5-resurse', '1-2', 22, 5, 'resurse'::public.pillar, 'Spațiul de mișcare strâns', 4, 'A'::public.completion_mode, ARRAY['2 obiecte']::text[], ARRAY['Puneți două obiecte la loc după joacă.', '„La loc.” pe rând.']::text[], 'A ajutat cu un obiect la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z5-social', '1-2', 22, 5, 'social'::public.pillar, 'Pași pe loc cu mama / tata', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Marșați pe loc lângă adult pe scurt.', '„Împreună. Pași.”']::text[], 'A participat la pași cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z6-fizic', '1-2', 22, 6, 'fizic'::public.pillar, 'Dans scurt, apoi așezat', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dans sau balans 20–30 de secunde.', 'Apoi așezați-vă: „Jos. Calm.”']::text[], 'A dansat sau s-a așezat după.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s22-2-3-z6-mental', '1-2', 22, 6, 'mental'::public.pillar, 'Mișcare și liniște în corp', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mișcare scurtă: „Mișcare.”', 'Stați pe loc: „Liniște. Corp.”']::text[], 'A auzit mișcare și liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z6-resurse', '1-2', 22, 6, 'resurse'::public.pillar, 'Mingea moale în cutie după dans', 4, 'A'::public.completion_mode, ARRAY['minge moale', 'cutie']::text[], ARRAY['Dacă ați folosit mingea, puneți-o în cutie.', '„La loc. În cutie.”']::text[], 'A ajutat cu mingea în cutie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z6-social', '1-2', 22, 6, 'social'::public.pillar, 'Arătăm mișcarea adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți o mișcare scurtă față de adult.', '„Uite. Corp.” fără forțare.']::text[], 'A mișcat sau a privit cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z7-fizic', '1-2', 22, 7, 'fizic'::public.pillar, 'Plimbare liberă, un dans la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.', 'La final: balans sau săritură mică dacă vrea.']::text[], 'A mers liber; a mișcat corpul sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z7-mental', '1-2', 22, 7, 'mental'::public.pillar, 'Carte: copii care se mișcă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați un copil care aleargă sau dansează: „Mișcare.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z7-resurse', '1-2', 22, 7, 'resurse'::public.pillar, 'Jucăriile de mișcare pe raft', 4, 'A'::public.completion_mode, ARRAY['1–2 jucării']::text[], ARRAY['Puneți jucăriile folosite pe raft.', '„La loc.”']::text[], 'A ajutat cu cel puțin o jucărie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă'),
('s22-2-3-z7-social', '1-2', 22, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp care se mișcă în casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s23-2-3-z1-fizic', '1-2', 23, 1, 'fizic'::public.pillar, 'Nas aproape de pâine pe scurt', 4, 'A'::public.completion_mode, ARRAY['felie de pâine rece']::text[], ARRAY['Aduceți pâinea la masă. Apropiați nasul pe scurt.', '„Pâine. Miros.” fără a forța gustul.']::text[], 'A mirosit sau a privit pâinea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z1-mental', '1-2', 23, 1, 'mental'::public.pillar, 'Pâine: miros', 3, 'A'::public.completion_mode, ARRAY['pâine']::text[], ARRAY['Arătați pâinea: „Pâine.”', 'Atingeți nasul: „Miros.”']::text[], 'A auzit pâine și miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z1-resurse', '1-2', 23, 1, 'resurse'::public.pillar, 'Pâinea în coș / pe masă la loc', 4, 'A'::public.completion_mode, ARRAY['pâine', 'coș sau farfurie']::text[], ARRAY['Puneți pâinea la loc după mirosit.', '„Pâine. La loc.”']::text[], 'A ajutat să pună pâinea la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z1-social', '1-2', 23, 1, 'social'::public.pillar, 'Mirosim pâinea împreună', 3, 'A'::public.completion_mode, ARRAY['pâine']::text[], ARRAY['Apropiați nasul pe rând.', '„Împreună. Pâine.” fără forțare.']::text[], 'A mirosit sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z2-fizic', '1-2', 23, 2, 'fizic'::public.pillar, 'Mâini și săpun pe scurt', 5, 'A'::public.completion_mode, ARRAY['săpun solid sau lichid blând']::text[], ARRAY['Spălați mâinile pe scurt cu săpun.', '„Săpun. Mâini.” clătiți împreună.']::text[], 'A atins apa sau săpunul pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z2-mental', '1-2', 23, 2, 'mental'::public.pillar, 'Săpun: miros curat', 3, 'A'::public.completion_mode, ARRAY['săpun']::text[], ARRAY['Arătați săpunul: „Săpun.”', 'Mirosiți pe scurt: „Miros.”']::text[], 'A auzit săpun și miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z2-resurse', '1-2', 23, 2, 'resurse'::public.pillar, 'Săpunul la loc lângă chiuvetă', 4, 'A'::public.completion_mode, ARRAY['săpun']::text[], ARRAY['Puneți săpunul la locul lui.', '„Săpun. La loc.”']::text[], 'A ajutat să așeze săpunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s23-2-3-z2-social', '1-2', 23, 2, 'social'::public.pillar, 'Spălăm mâinile cu adultul', 3, 'A'::public.completion_mode, ARRAY['săpun']::text[], ARRAY['Spălați pe scurt lângă adult.', '„Împreună. Mâini.”']::text[], 'A participat la spălat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z3-fizic', '1-2', 23, 3, 'fizic'::public.pillar, 'Cană cu ceai răcit — miros', 4, 'A'::public.completion_mode, ARRAY['cană cu ceai răcit']::text[], ARRAY['Apropiați nasul de cană pe scurt (ceai răcit).', '„Ceai. Miros.” fără a bea dacă nu vrea.']::text[], 'A mirosit sau a privit cana.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z3-mental', '1-2', 23, 3, 'mental'::public.pillar, 'Ceai: cald răcit, miros', 3, 'A'::public.completion_mode, ARRAY['cană cu ceai răcit']::text[], ARRAY['Arătați cana: „Ceai.”', 'Atingeți nasul: „Miros.”']::text[], 'A auzit ceai și miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z3-resurse', '1-2', 23, 3, 'resurse'::public.pillar, 'Cana pe masă / la chiuvetă', 4, 'A'::public.completion_mode, ARRAY['cană']::text[], ARRAY['Duceți cana pe masă sau la chiuvetă.', '„Cană. La loc.”']::text[], 'A ajutat să ducă cana.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z3-social', '1-2', 23, 3, 'social'::public.pillar, 'Mirosim ceaiul cu adultul', 3, 'A'::public.completion_mode, ARRAY['cană cu ceai răcit']::text[], ARRAY['Mirosiți pe rând lângă adult.', '„Împreună. Ceai.” fără forțare.']::text[], 'A mirosit sau a privit cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z4-fizic', '1-2', 23, 4, 'fizic'::public.pillar, 'Prosopul curat la nas pe scurt', 4, 'A'::public.completion_mode, ARRAY['prosop curat']::text[], ARRAY['Apropiați prosopul de nas pe scurt.', '„Prosop. Miros.”']::text[], 'A mirosit sau a atins prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z4-mental', '1-2', 23, 4, 'mental'::public.pillar, 'Curat: miros de rufe', 3, 'A'::public.completion_mode, ARRAY['prosop sau cămașă curată']::text[], ARRAY['Arătați: „Curat.”', 'Mirosiți: „Miros.”']::text[], 'A auzit curat și miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s23-2-3-z4-resurse', '1-2', 23, 4, 'resurse'::public.pillar, 'Prosopul pe cârlig / la loc', 4, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Puneți prosopul pe cârlig sau raft.', '„Prosop. La loc.”']::text[], 'A ajutat să pună prosopul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z4-social', '1-2', 23, 4, 'social'::public.pillar, 'Arătăm prosopul adultului', 3, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Duceți prosopul la adult: „Uite prosopul.”', 'Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z5-fizic', '1-2', 23, 5, 'fizic'::public.pillar, 'Măr sau fruct — miros pe scurt', 4, 'A'::public.completion_mode, ARRAY['măr sau fruct întreg']::text[], ARRAY['Apropiați fructul de nas pe scurt.', '„Măr. Miros.” fără a forța mușcătura.']::text[], 'A mirosit sau a ținut fructul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z5-mental', '1-2', 23, 5, 'mental'::public.pillar, 'Trei mirosuri: pâine, săpun, ceai', 4, 'A'::public.completion_mode, ARRAY['pâine', 'săpun', 'cană']::text[], ARRAY['Arătați pe rând: „Pâine. Săpun. Ceai.”', 'Un miros scurt la fiecare dacă vrea.']::text[], 'A privit cel puțin două obiecte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z5-resurse', '1-2', 23, 5, 'resurse'::public.pillar, 'Fructul în farfurie / coș', 4, 'A'::public.completion_mode, ARRAY['fruct', 'farfurie sau coș']::text[], ARRAY['Puneți fructul la loc după mirosit.', '„La loc.”']::text[], 'A ajutat să pună fructul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z5-social', '1-2', 23, 5, 'social'::public.pillar, 'Spunem adultului ce am mirosit', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Am mirosit pâine / săpun.”', 'Stați pe scurt, fără grabă.']::text[], 'A fost prezent la spus.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z6-fizic', '1-2', 23, 6, 'fizic'::public.pillar, 'Bucătăria: pași și miros pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Intrați în bucătărie pe scurt.', 'Stați pe loc: „Bucătărie. Miros.”']::text[], 'A intrat și a stat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s23-2-3-z6-mental', '1-2', 23, 6, 'mental'::public.pillar, 'Miros în casă, gata', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Un miros scurt. Apoi mâinile pe genunchi.', '„Gata. Miros.”']::text[], 'A auzit gata după miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z6-resurse', '1-2', 23, 6, 'resurse'::public.pillar, 'Farfuria și cana la loc', 4, 'A'::public.completion_mode, ARRAY['farfurie', 'cană']::text[], ARRAY['Puneți farfuria și cana la loc pe rând.', '„La loc.”']::text[], 'A ajutat cu un obiect la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z6-social', '1-2', 23, 6, 'social'::public.pillar, 'Mirosim în bucătărie cu adultul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați în bucătărie lângă adult pe scurt.', '„Împreună. Bucătărie.”']::text[], 'A stat lângă adult în bucătărie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z7-fizic', '1-2', 23, 7, 'fizic'::public.pillar, 'Plimbare liberă în casă, un miros la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.', 'La final: un miros blând (pâine/săpun) dacă vrea.']::text[], 'A mers liber; a mirosit sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z7-mental', '1-2', 23, 7, 'mental'::public.pillar, 'Carte: mâncare și casă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați pâine sau o cană din imagine: „Pâine.” sau „Ceai.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z7-resurse', '1-2', 23, 7, 'resurse'::public.pillar, 'Obiectele de miros la loc', 4, 'A'::public.completion_mode, ARRAY['pâine sau săpun folosit']::text[], ARRAY['Puneți obiectul folosit la loc.', '„La loc. Gata.”']::text[], 'A ajutat cu obiectul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă'),
('s23-2-3-z7-social', '1-2', 23, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Mirosuri din casă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s24-2-3-z1-fizic', '1-2', 24, 1, 'fizic'::public.pillar, 'Mână ridicată: salut pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați mâna o dată: „Bună.”', 'Coborâți mâna. Fără forțare.']::text[], 'A ridicat mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z1-mental', '1-2', 24, 1, 'mental'::public.pillar, 'Bună — cuvânt scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Spuneți blând: „Bună.”', 'Arătați mâna: „Salut.” pe scurt.']::text[], 'A auzit bună / salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z1-resurse', '1-2', 24, 1, 'resurse'::public.pillar, 'Jucăria de salut pe raft', 4, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['Luați o jucărie pe scurt ca „oaspete”.', 'Puneți-o pe raft: „La loc.”']::text[], 'A ajutat cu jucăria pe raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z1-social', '1-2', 24, 1, 'social'::public.pillar, 'Spunem bună adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Bună.”', 'Stați pe scurt, fără forțare.']::text[], 'A fost prezent la salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z2-fizic', '1-2', 24, 2, 'fizic'::public.pillar, 'Fluturăm mâna: la revedere', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Fluturați mâna o dată: „La revedere.”', 'Coborâți mâna pe scurt.']::text[], 'A fluturat mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z2-mental', '1-2', 24, 2, 'mental'::public.pillar, 'Bună și la revedere', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mână sus: „Bună.”', 'Fluturare: „La revedere.”']::text[], 'A auzit ambele cuvinte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z2-resurse', '1-2', 24, 2, 'resurse'::public.pillar, 'Haina de oaspete pe cârlig', 4, 'A'::public.completion_mode, ARRAY['haină sau eșarfă']::text[], ARRAY['Puneți o haină pe cârlig ca pentru oaspete.', '„Haină. La loc.”']::text[], 'A ajutat să atârne sau să atingă haina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s24-2-3-z2-social', '1-2', 24, 2, 'social'::public.pillar, 'La revedere adultului pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Fluturați mâna spre adult: „La revedere.”', 'Fără grabă, fără forțare.']::text[], 'A participat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z3-fizic', '1-2', 24, 3, 'fizic'::public.pillar, 'Ducem o jucărie „oaspetelui”', 5, 'A'::public.completion_mode, ARRAY['jucărie', 'scaun sau canapea']::text[], ARRAY['Duceți jucăria pe scaun ca la un oaspete.', '„Ține. Pentru tine.” pe scurt.']::text[], 'A dus sau a atins jucăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z3-mental', '1-2', 24, 3, 'mental'::public.pillar, 'Oaspete în casă', 3, 'A'::public.completion_mode, ARRAY['pluș sau păpușă']::text[], ARRAY['Așezați plușul pe scaun: „Oaspete.”', 'Arătați: „În casă.”']::text[], 'A auzit oaspete și a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z3-resurse', '1-2', 24, 3, 'resurse'::public.pillar, 'Scaunul liber pentru oaspete', 4, 'A'::public.completion_mode, ARRAY['1 obiect de pe scaun']::text[], ARRAY['Luați un obiect de pe scaun. Puneți-l la loc.', '„Scaun. Liber.”']::text[], 'A ajutat să elibereze scaunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z3-social', '1-2', 24, 3, 'social'::public.pillar, 'Oferim jucăria adultului-oaspete', 3, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['Oferiți jucăria adultului: „Ține.”', 'Stați pe scurt, fără forțare.']::text[], 'A oferit sau a privit oferirea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z4-fizic', '1-2', 24, 4, 'fizic'::public.pillar, 'Ne așezăm lângă oaspete pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Așezați-vă pe canapea lângă adult.', '„Lângă. Oaspete.” 20–30 de secunde.']::text[], 'A șezut lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z4-mental', '1-2', 24, 4, 'mental'::public.pillar, 'Aproape, fără grabă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați locul lângă adult: „Aproape.”', 'Stați: „Fără grabă.” pe scurt.']::text[], 'A auzit aproape / fără grabă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s24-2-3-z4-resurse', '1-2', 24, 4, 'resurse'::public.pillar, 'Paharul pe masă pentru oaspete', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Puneți un pahar pe masă pe scurt.', '„Pahar. Masă.” apoi la loc dacă e gata.']::text[], 'A ajutat cu paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z4-social', '1-2', 24, 4, 'social'::public.pillar, 'Stăm lângă oaspete fără forțare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă adult. El poate pleca dacă vrea.', '„Împreună.” fără forțare.']::text[], 'A stat sau a privit pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z5-fizic', '1-2', 24, 5, 'fizic'::public.pillar, 'Pași până la ușă: salut', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți până la ușă pe scurt.', 'Ridicați mâna: „Bună.” sau „La revedere.”']::text[], 'A mers la ușă și a văzut salutul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z5-mental', '1-2', 24, 5, 'mental'::public.pillar, 'Familie: mama, tata, copil', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Mama.” sau „Tata.”', 'Arătați-l pe el: „Tu.” pe scurt.']::text[], 'A auzit numele familiei pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z5-resurse', '1-2', 24, 5, 'resurse'::public.pillar, 'Pantofii de oaspete la loc', 4, 'A'::public.completion_mode, ARRAY['pereche de pantofi']::text[], ARRAY['Așezați pantofii lângă ușă sau pe raft.', '„Pantofi. La loc.”']::text[], 'A ajutat cu pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z5-social', '1-2', 24, 5, 'social'::public.pillar, 'Salut la ușă cu adultul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La ușă, lângă adult: „Bună.” pe scurt.', 'Fără forțare dacă nu vrea să vorbească.']::text[], 'A fost prezent la ușă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z6-fizic', '1-2', 24, 6, 'fizic'::public.pillar, 'Poză de familie — arătăm cu degetul', 4, 'A'::public.completion_mode, ARRAY['fotografie de familie sau album']::text[], ARRAY['Arătați poza. Atingeți cu degetul pe scurt.', '„Familie.” 15–20 de secunde.']::text[], 'A privit sau a atins poza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s24-2-3-z6-mental', '1-2', 24, 6, 'mental'::public.pillar, 'Cine e în poză', 3, 'A'::public.completion_mode, ARRAY['fotografie']::text[], ARRAY['Arătați o persoană: „Mama.” sau „Tata.”', 'Arătați-l pe el dacă e: „Tu.”']::text[], 'A privit cel puțin o persoană din poză.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z6-resurse', '1-2', 24, 6, 'resurse'::public.pillar, 'Poza / albumul pe raft', 4, 'A'::public.completion_mode, ARRAY['fotografie sau album']::text[], ARRAY['Puneți poza sau albumul pe raft.', '„La loc.”']::text[], 'A ajutat să pună poza la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z6-social', '1-2', 24, 6, 'social'::public.pillar, 'Arătăm poza adultului', 3, 'A'::public.completion_mode, ARRAY['fotografie']::text[], ARRAY['Duceți poza la adult: „Uite familia.”', 'Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z7-fizic', '1-2', 24, 7, 'fizic'::public.pillar, 'Plimbare liberă, salut la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.', 'La final: o mână ridicată „Bună.” dacă vrea.']::text[], 'A mers liber; a salutat sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z7-mental', '1-2', 24, 7, 'mental'::public.pillar, 'Carte: familie și casă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați o familie din imagine: „Familie.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z7-resurse', '1-2', 24, 7, 'resurse'::public.pillar, 'Jucăria-oaspete pe raft', 4, 'A'::public.completion_mode, ARRAY['pluș sau păpușă']::text[], ARRAY['Puneți plușul pe raft după joacă.', '„La loc. Gata.”']::text[], 'A ajutat cu plușul pe raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții'),
('s24-2-3-z7-social', '1-2', 24, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Familia și oaspeții')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
