insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s25-2-3-z1-fizic', '1-2', 25, 1, 'fizic'::public.pillar, 'Aprindem lampa', 4, 'A'::public.completion_mode, ARRAY['lampă de cameră']::text[], ARRAY['Aprindeți lampa împreună pe scurt.','„Lumină. Seară.” 10–20 de secunde.']::text[], 'A privit sau a atins întrerupătorul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z1-mental', '1-2', 25, 1, 'mental'::public.pillar, 'E lumină', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați lampa: „Lumină.”','Arătați camera: „Seară.”']::text[], 'A auzit lumină și seară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z1-resurse', '1-2', 25, 1, 'resurse'::public.pillar, 'Lampa stă pe locul ei', 4, 'A'::public.completion_mode, ARRAY['lampă mică']::text[], ARRAY['Așezați lampa pe noptieră sau masă.','„Lampă. La loc.”']::text[], 'A ajutat să așeze lampa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z1-social', '1-2', 25, 1, 'social'::public.pillar, 'Aprindem împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă lampă unul lângă altul.','„Împreună. Lumină.” fără grabă.']::text[], 'A stat lângă voi la lumină.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z2-fizic', '1-2', 25, 2, 'fizic'::public.pillar, 'Stingem lampa', 4, 'A'::public.completion_mode, ARRAY['perdea sau draperie']::text[], ARRAY['Trageți perdeaua împreună pe scurt.','„Perdea. Seară.”']::text[], 'A ajutat să miște perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z2-mental', '1-2', 25, 2, 'mental'::public.pillar, 'E întuneric — sau lumină?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam pe scurt: „Afară. Întuneric.”','În cameră: „Casă. Lumină.”']::text[], 'A privit geamul sau camera.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z2-resurse', '1-2', 25, 2, 'resurse'::public.pillar, 'Întrerupătorul, apoi mâna jos', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Închideți perdeaua pe scurt.','„Perdea. Gata.”']::text[], 'A participat la închiderea perdelelor.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s25-2-3-z2-social', '1-2', 25, 2, 'social'::public.pillar, 'Stingem împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Trageți perdeaua lângă adult.','„Împreună.” fără forțare.']::text[], 'A fost prezent la perdea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z3-fizic', '1-2', 25, 3, 'fizic'::public.pillar, 'Lumină mică de seară', 5, 'A'::public.completion_mode, ARRAY['pătură']::text[], ARRAY['Luați pătura. Așezați-o pe pat sau canapea.','„Pătură. Seară.” pe scurt.']::text[], 'A ajutat cu pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z3-mental', '1-2', 25, 3, 'mental'::public.pillar, 'Lumină — sau umbră?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați patul: „Pat.”','„Somn.” pe scurt, fără grabă.']::text[], 'A auzit pat și somn.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z3-resurse', '1-2', 25, 3, 'resurse'::public.pillar, 'Perdeaua trasă seara', 4, 'A'::public.completion_mode, ARRAY['pernă','pătură']::text[], ARRAY['Așezați perna. Apoi pătura.','„La loc.” pe rând.']::text[], 'A ajutat cu perna sau pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z3-social', '1-2', 25, 3, 'social'::public.pillar, 'Lumină mică împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe pat sau canapea pe scurt.','„Împreună. Calm.” fără forțare.']::text[], 'A șezut lângă voi pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z4-fizic', '1-2', 25, 4, 'fizic'::public.pillar, 'Întoarcem o pagină la lampă', 5, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce o pagină.','„Carte. Seară.” 20–30 de secunde.']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z4-mental', '1-2', 25, 4, 'mental'::public.pillar, 'Imagini la lumină', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Arătați o imagine: „Uite.”','Un cuvânt scurt despre ce vedeți.']::text[], 'A privit imaginea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s25-2-3-z4-resurse', '1-2', 25, 4, 'resurse'::public.pillar, 'Cartea pe raft după seară', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Puneți cartea pe noptieră sau raft.','„Carte. La loc.”']::text[], 'A ajutat să pună cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z4-social', '1-2', 25, 4, 'social'::public.pillar, 'Citim la lampă împreună', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Stați unul lângă altul cu cartea.','„Împreună. Carte.” fără grabă.']::text[], 'A șezut lângă voi cu cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z5-fizic', '1-2', 25, 5, 'fizic'::public.pillar, 'Pași prin camera luminată', 5, 'A'::public.completion_mode, ARRAY['apă','săpun']::text[], ARRAY['Spălați mâinile pe scurt împreună.','„Mâini. Apă.” fără grabă.']::text[], 'A atins apa sau săpunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z5-mental', '1-2', 25, 5, 'mental'::public.pillar, 'Unde e lampa?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați mâinile: „Curat.”','„Gata. Somn.” pe scurt.']::text[], 'A auzit curat și gata.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z5-resurse', '1-2', 25, 5, 'resurse'::public.pillar, 'Lampa rămâne pe loc', 4, 'A'::public.completion_mode, ARRAY['prosop mic']::text[], ARRAY['Ștergeți mâinile pe scurt.','„Prosop. La loc.”']::text[], 'A ajutat cu prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z5-social', '1-2', 25, 5, 'social'::public.pillar, 'Arătăm lampa', 4, 'A'::public.completion_mode, ARRAY['apă']::text[], ARRAY['Voi spălați pe scurt. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z6-fizic', '1-2', 25, 6, 'fizic'::public.pillar, 'Stăm lângă lampă', 4, 'A'::public.completion_mode, ARRAY['lampă']::text[], ARRAY['Stingeți lampa o dată împreună.','„Stins. Lumină mică.” pe scurt.']::text[], 'A privit stingerea sau a atins întrerupătorul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s25-2-3-z6-mental', '1-2', 25, 6, 'mental'::public.pillar, 'Seară în casă', 3, 'A'::public.completion_mode, ARRAY['lampă']::text[], ARRAY['Aprindeți: „Aprins.”','Stingeți: „Stins.” pe scurt.']::text[], 'A auzit aprins și stins.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z6-resurse', '1-2', 25, 6, 'resurse'::public.pillar, 'Perdeaua la loc', 4, 'A'::public.completion_mode, ARRAY['lumină de veghe sau lampă mică']::text[], ARRAY['Așezați lumina de veghe pe noptieră.','„La loc. Veghe.”']::text[], 'A ajutat cu lumina de veghe.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z6-social', '1-2', 25, 6, 'social'::public.pillar, 'Seară liniștită împreună', 3, 'A'::public.completion_mode, ARRAY['lampă']::text[], ARRAY['Voi stingeți. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z7-fizic', '1-2', 25, 7, 'fizic'::public.pillar, 'Plimbare prin casă, seara', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.','La final: o privire la lampă dacă vrea.']::text[], 'A mers liber; a privit lampa sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z7-mental', '1-2', 25, 7, 'mental'::public.pillar, 'Cartea de noapte', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați noapte sau lumină dacă e clar: „Noapte.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z7-resurse', '1-2', 25, 7, 'resurse'::public.pillar, 'Cartea și lampa la loc', 4, 'A'::public.completion_mode, ARRAY['carte','pătură']::text[], ARRAY['Puneți cartea pe raft, pătura pe pat.','„La loc.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară'),
('s25-2-3-z7-social', '1-2', 25, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Lumină de seară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s26-2-3-z1-fizic', '1-2', 26, 1, 'fizic'::public.pillar, 'Ne uităm din nou pe geam', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la geam. Atingeți sticla pe scurt.','„Geam. Favorit.” 10–20 de secunde.']::text[], 'A atins geamul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z1-mental', '1-2', 26, 1, 'mental'::public.pillar, 'Ți-aduci aminte geamul?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați geamul: „Geam.”','„Ne amintim.” pe scurt.']::text[], 'A privit geamul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z1-resurse', '1-2', 26, 1, 'resurse'::public.pillar, 'Perdeaua la loc, ca înainte', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Trageți perdeaua pe scurt.','„Perdea. La loc.”']::text[], 'A ajutat cu perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z1-social', '1-2', 26, 1, 'social'::public.pillar, 'Privim geamul din nou', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam unul lângă altul.','„Împreună. Din nou.” fără grabă.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z2-fizic', '1-2', 26, 2, 'fizic'::public.pillar, 'Dansăm din nou, ca atunci', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați corpul stânga-dreapta pe scurt.','„Dans. Favorit.” 15–20 de secunde.']::text[], 'A balansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z2-mental', '1-2', 26, 2, 'mental'::public.pillar, 'Ți-aduci aminte dansul?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați corpul: „Corp.”','Mișcați brațele: „Dans.”']::text[], 'A auzit corp și dans.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z2-resurse', '1-2', 26, 2, 'resurse'::public.pillar, 'Facem loc, ca înainte', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți 1–2 obiecte la loc.','„La loc. Liber.”']::text[], 'A ajutat să elibereze spațiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s26-2-3-z2-social', '1-2', 26, 2, 'social'::public.pillar, 'Dansăm din nou împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați împreună 20–30 de secunde.','„Împreună. Din nou.” fără forțare.']::text[], 'A dansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z3-fizic', '1-2', 26, 3, 'fizic'::public.pillar, 'Cartea iubită, pagina ta', 5, 'A'::public.completion_mode, ARRAY['carte preferată']::text[], ARRAY['El alege cartea dacă vrea.','Întoarce o pagină: „Carte. Favorită.”']::text[], 'A ales sau a întors pagina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z3-mental', '1-2', 26, 3, 'mental'::public.pillar, 'Aceeași carte', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Arătați o imagine cunoscută: „Uite.”','Un cuvânt scurt pe care îl știți amândoi.']::text[], 'A privit imaginea cunoscută.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z3-resurse', '1-2', 26, 3, 'resurse'::public.pillar, 'Cartea pe raft, ca întotdeauna', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Puneți cartea pe raft după lectură.','„Carte. La loc.”']::text[], 'A ajutat să pună cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z3-social', '1-2', 26, 3, 'social'::public.pillar, 'Citim din nou împreună', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Stați cu cartea lângă adult.','„Împreună. Carte.” fără grabă.']::text[], 'A șezut lângă voi cu cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z4-fizic', '1-2', 26, 4, 'fizic'::public.pillar, 'Mingea favorită, o dăm', 5, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Dați mingea pe scurt o dată.','„Minge. Favorită.” fără grabă.']::text[], 'A atins sau a dat mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z4-mental', '1-2', 26, 4, 'mental'::public.pillar, 'Ți-aduci aminte mingea?', 3, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Arătați mingea: „Minge.”','„Rând.” pe scurt.']::text[], 'A auzit minge și rând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s26-2-3-z4-resurse', '1-2', 26, 4, 'resurse'::public.pillar, 'Mingea în cutie din nou', 4, 'A'::public.completion_mode, ARRAY['minge','cutie']::text[], ARRAY['Puneți mingea în cutie.','„La loc. În cutie.”']::text[], 'A ajutat să pună mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z4-social', '1-2', 26, 4, 'social'::public.pillar, 'Dăm mingea din nou, pe rând', 4, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Voi dați. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z5-fizic', '1-2', 26, 5, 'fizic'::public.pillar, 'Căutăm jucăria cunoscută', 5, 'A'::public.completion_mode, ARRAY['3 obiecte cunoscute']::text[], ARRAY['Așezați trei obiecte pe masă.','El atinge unul: „Uite.” pe scurt.']::text[], 'A atins cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z5-mental', '1-2', 26, 5, 'mental'::public.pillar, 'Unde era?', 3, 'A'::public.completion_mode, ARRAY['2–3 obiecte']::text[], ARRAY['Arătați un obiect: „Unde e?”','Arătați-l: „Aici.”']::text[], 'A privit obiectul arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z5-resurse', '1-2', 26, 5, 'resurse'::public.pillar, 'Jucăria la locul ei', 5, 'A'::public.completion_mode, ARRAY['3 obiecte','cutie sau raft']::text[], ARRAY['Puneți cele trei obiecte la loc pe rând.','„La loc.” după fiecare.']::text[], 'A ajutat cu cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z5-social', '1-2', 26, 5, 'social'::public.pillar, 'Arătăm jucăria cunoscută', 3, 'A'::public.completion_mode, ARRAY['1–2 obiecte']::text[], ARRAY['Duceți un obiect la adult: „Uite.”','Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z6-fizic', '1-2', 26, 6, 'fizic'::public.pillar, 'Alegem o favorită', 4, 'A'::public.completion_mode, ARRAY['pâine sau săpun cunoscut']::text[], ARRAY['Apropiați nasul pe scurt de obiect.','„Miros. Favorit.” fără a forța.']::text[], 'A mirosit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s26-2-3-z6-mental', '1-2', 26, 6, 'mental'::public.pillar, 'Care îți place?', 3, 'A'::public.completion_mode, ARRAY['pâine sau săpun']::text[], ARRAY['Arătați obiectul: „Pâine.” sau „Săpun.”','Atingeți nasul: „Miros.”']::text[], 'A auzit numele și miros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z6-resurse', '1-2', 26, 6, 'resurse'::public.pillar, 'Favorita pe raft', 4, 'A'::public.completion_mode, ARRAY['pâine sau săpun']::text[], ARRAY['Puneți obiectul la loc după mirosit.','„La loc.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z6-social', '1-2', 26, 6, 'social'::public.pillar, 'Alegem împreună', 3, 'A'::public.completion_mode, ARRAY['pâine sau săpun']::text[], ARRAY['Apropiați nasul pe rând.','„Împreună. Din nou.” fără forțare.']::text[], 'A mirosit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z7-fizic', '1-2', 26, 7, 'fizic'::public.pillar, 'Plimbare, ca de obicei', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.','La final: un joc scurt pe care îl iubește, dacă vrea.']::text[], 'A mers liber; a ales sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z7-mental', '1-2', 26, 7, 'mental'::public.pillar, 'Cartea de la jumătatea anului', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','„Împreună. An.” pe scurt, fără evaluare.']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z7-resurse', '1-2', 26, 7, 'resurse'::public.pillar, 'Cartea și mingea la loc', 4, 'A'::public.completion_mode, ARRAY['carte', 'minge']::text[], ARRAY['Puneți cartea și mingea pe raft.', '„La loc. Gata.”']::text[], 'A ajutat să pună cartea sau mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele'),
('s26-2-3-z7-social', '1-2', 26, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Jumătate de an: repetăm favoritele')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s27-2-3-z1-fizic', '1-2', 27, 1, 'fizic'::public.pillar, 'Mâna pe geam, uităm vremea', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la geam. Atingeți sticla pe scurt.','„Geam.” 10–20 de secunde.']::text[], 'A atins geamul sau a privit afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z1-mental', '1-2', 27, 1, 'mental'::public.pillar, 'Ninge — sau plouă?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Priviți afară: „Zăpadă.” sau „Ploaie.”','Un singur cuvânt, fără grabă.']::text[], 'A auzit zăpadă sau ploaie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z1-resurse', '1-2', 27, 1, 'resurse'::public.pillar, 'Perdeaua la loc', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Trageți perdeaua ca să vedeți afară.','„Perdea. Geam.”']::text[], 'A ajutat să miște perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z1-social', '1-2', 27, 1, 'social'::public.pillar, 'Privim vremea împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam unul lângă altul.','„Împreună. Afară.” fără grabă.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z2-fizic', '1-2', 27, 2, 'fizic'::public.pillar, 'Urmărim picăturile pe geam', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă e ploaie: urmăriți o picătură cu degetul pe geam.','„Picătură.” pe scurt. Dacă e zăpadă: „Fulg.”']::text[], 'A urmărit cu degetul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z2-mental', '1-2', 27, 2, 'mental'::public.pillar, 'Picătura coboară', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Picătură.” sau „Fulg.”','Repetați o dată, fără forțare.']::text[], 'A auzit cuvântul și a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z2-resurse', '1-2', 27, 2, 'resurse'::public.pillar, 'Ștergem o picătură', 4, 'A'::public.completion_mode, ARRAY['cârpă uscată']::text[], ARRAY['Ștergeți un colț de geam pe scurt.','„Cârpă. La loc.”']::text[], 'A atins cârpa sau a ajutat la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s27-2-3-z2-social', '1-2', 27, 2, 'social'::public.pillar, 'Urmărim picăturile pe rând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Uite ploaia.” sau „Uite zăpada.”','Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z3-fizic', '1-2', 27, 3, 'fizic'::public.pillar, 'Cizmele la ușă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Apropiați urechea de geam pe scurt dacă e ploaie.','„Sunet. Ploaie.” 10–15 de secunde.']::text[], 'A ascultat sau a privit geamul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z3-mental', '1-2', 27, 3, 'mental'::public.pillar, 'Ieșim — sau stăm?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam: „Sunet.” pe scurt.','În cameră: „Liniște. Casă.”']::text[], 'A auzit sunet și liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z3-resurse', '1-2', 27, 3, 'resurse'::public.pillar, 'Cizmele după geam', 4, 'A'::public.completion_mode, ARRAY['cârpă']::text[], ARRAY['Puneți cârpa la loc după geam.','„La loc.”']::text[], 'A ajutat cu cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z3-social', '1-2', 27, 3, 'social'::public.pillar, 'Ne încălțăm împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam. Ascultați pe scurt.','„Împreună.” fără forțare.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z4-fizic', '1-2', 27, 4, 'fizic'::public.pillar, 'Suflăm pe geamul ud', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați 10 secunde la geam.','Mergeți în cameră: „Cald. Casă.”']::text[], 'A mers de la geam în cameră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z4-mental', '1-2', 27, 4, 'mental'::public.pillar, 'Abur și ploaie', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam: „Rece.” pe scurt.','În cameră: „Cald.”']::text[], 'A auzit rece și cald.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s27-2-3-z4-resurse', '1-2', 27, 4, 'resurse'::public.pillar, 'Cârpa de geam, la loc', 4, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Luați pătura. Așezați-o pe canapea.','„Pătură. La loc.”']::text[], 'A ajutat cu pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z4-social', '1-2', 27, 4, 'social'::public.pillar, 'Suflăm pe rând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe canapea unul lângă altul.','„Împreună. Cald.” fără forțare.']::text[], 'A șezut lângă voi pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z5-fizic', '1-2', 27, 5, 'fizic'::public.pillar, 'Haina de ploaie pe umeri', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Suflați blând pe geam o dată.','„Abur.” pe scurt, dacă apare.']::text[], 'A suflat sau a privit aburul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z5-mental', '1-2', 27, 5, 'mental'::public.pillar, 'Haină — sau fără?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați aburul: „Abur.”','Arătați afară: „Zăpadă.” sau „Ploaie.”']::text[], 'A privit aburul sau afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z5-resurse', '1-2', 27, 5, 'resurse'::public.pillar, 'Haina pe cârlig', 4, 'A'::public.completion_mode, ARRAY['cârpă uscată']::text[], ARRAY['Ștergeți aburul pe scurt.','„Cârpă. La loc.”']::text[], 'A ajutat să șteargă sau să pună cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z5-social', '1-2', 27, 5, 'social'::public.pillar, 'Te ajut la haină', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi suflați. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z6-fizic', '1-2', 27, 6, 'fizic'::public.pillar, 'Stăm la geam, vremea trece', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Unu.” pe scurt.','Dacă vrea: „Doi.” fără forțare.']::text[], 'A privit și a auzit unu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s27-2-3-z6-mental', '1-2', 27, 6, 'mental'::public.pillar, 'Zăpadă — sau ploaie?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Mult.” pe scurt.','„Zăpadă.” sau „Ploaie.”']::text[], 'A auzit mult și vremea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z6-resurse', '1-2', 27, 6, 'resurse'::public.pillar, 'Șosetele după geam', 4, 'A'::public.completion_mode, ARRAY['obiect de pe pervaz']::text[], ARRAY['Luați obiectul pe scurt. Puneți-l la loc.','„La loc. Pervaz.”']::text[], 'A ajutat cu obiectul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z6-social', '1-2', 27, 6, 'social'::public.pillar, 'Privim fulgii împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la adult: „Ploaie.” sau „Zăpadă.”','Stați pe scurt, fără grabă.']::text[], 'A participat la spus sau arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z7-fizic', '1-2', 27, 7, 'fizic'::public.pillar, 'Plimbare până la geam', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă pe scurt.','La final: o privire la geam dacă vrea.']::text[], 'A mers liber; a privit geamul sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z7-mental', '1-2', 27, 7, 'mental'::public.pillar, 'Cartea cu zăpadă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați zăpadă sau ploaie dacă e clar: „Uite.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z7-resurse', '1-2', 27, 7, 'resurse'::public.pillar, 'Haina și cartea la loc', 4, 'A'::public.completion_mode, ARRAY['carte','cârpă']::text[], ARRAY['Puneți cartea pe raft, cârpa la loc.','„La loc.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam'),
('s27-2-3-z7-social', '1-2', 27, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Zăpadă sau ploaie la geam')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s28-2-3-z1-fizic', '1-2', 28, 1, 'fizic'::public.pillar, 'Cizmele pe picioare', 5, 'A'::public.completion_mode, ARRAY['cizme de cauciuc']::text[], ARRAY['Așezați o cizmă lângă picior.','„Cizmă.” pe scurt, fără forțare să o încalțe.']::text[], 'A atins cizma sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z1-mental', '1-2', 28, 1, 'mental'::public.pillar, 'Cizme pentru noroi', 3, 'A'::public.completion_mode, ARRAY['cizmă']::text[], ARRAY['Arătați cizma: „Cizmă.”','Arătați piciorul: „Picior.”']::text[], 'A auzit cizmă și picior.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z1-resurse', '1-2', 28, 1, 'resurse'::public.pillar, 'Cizmele la ușă, gata de ieșit', 4, 'A'::public.completion_mode, ARRAY['pereche de cizme']::text[], ARRAY['Așezați cizmele lângă ușă.','„Cizme. La loc.”']::text[], 'A ajutat cu cizmele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z1-social', '1-2', 28, 1, 'social'::public.pillar, 'Ne încălțăm împreună', 3, 'A'::public.completion_mode, ARRAY['cizme']::text[], ARRAY['Stați lângă adult cu cizmele.','„Împreună. Cizme.” fără forțare.']::text[], 'A fost prezent lângă cizme.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z2-fizic', '1-2', 28, 2, 'fizic'::public.pillar, 'Pași în noroi, doi-trei', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['În curte sau la ușă: atingeți noroiul pe scurt cu degetul sau cizma.','„Noroi.” 10–15 de secunde.']::text[], 'A atins noroiul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z2-mental', '1-2', 28, 2, 'mental'::public.pillar, 'Noroi moale', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Noroi.”','„Moale.” sau „Tare.” pe scurt.']::text[], 'A auzit noroi și textura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z2-resurse', '1-2', 28, 2, 'resurse'::public.pillar, 'Cizmele se scutură', 4, 'A'::public.completion_mode, ARRAY['cârpă sau prosop vechi']::text[], ARRAY['Ștergeți pe scurt cizma sau degetul.','„Cârpă. La loc.”']::text[], 'A ajutat cu cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s28-2-3-z2-social', '1-2', 28, 2, 'social'::public.pillar, 'Pași în noroi, unul lângă altul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă noroi unul lângă altul.','„Împreună. Noroi.” fără grabă.']::text[], 'A stat lângă voi la noroi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z3-fizic', '1-2', 28, 3, 'fizic'::public.pillar, 'Mâna pe cizmă, uităm noroiul', 6, 'A'::public.completion_mode, ARRAY['cizme']::text[], ARRAY['Ieșiți în curte pe scurt, cu adult.','Câteva pași: „Curte. Cizme.”']::text[], 'A făcut câțiva pași în curte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z3-mental', '1-2', 28, 3, 'mental'::public.pillar, 'Murdar — sau curat?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară: „Curte.” pe scurt.','La ușă: „Casă.”']::text[], 'A auzit curte și casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z3-resurse', '1-2', 28, 3, 'resurse'::public.pillar, 'Cârpa de cizme, la loc', 4, 'A'::public.completion_mode, ARRAY['cizme']::text[], ARRAY['Scuturați cizmele pe scurt la ușă.','„Cizme. Gata.”']::text[], 'A ajutat să scuture sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z3-social', '1-2', 28, 3, 'social'::public.pillar, 'Arătăm cizma', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți câțiva pași lângă adult.','„Împreună. Curte.” fără forțare.']::text[], 'A mers lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z4-fizic', '1-2', 28, 4, 'fizic'::public.pillar, 'Băltoaca de dezgheț', 5, 'A'::public.completion_mode, ARRAY['pahar mic cu apă']::text[], ARRAY['Turnați puțină apă pe pământ în curte, cu adult.','„Apă. Pământ.” pe scurt.']::text[], 'A turnat sau a privit apa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z4-mental', '1-2', 28, 4, 'mental'::public.pillar, 'Apă pe pământ', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Apă.”','Arătați: „Pământ.” pe scurt.']::text[], 'A auzit apă și pământ.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s28-2-3-z4-resurse', '1-2', 28, 4, 'resurse'::public.pillar, 'Cizmele după băltoacă', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Puneți paharul la chiuvetă sau pe masă.','„Pahar. La loc.”']::text[], 'A ajutat cu paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z4-social', '1-2', 28, 4, 'social'::public.pillar, 'Sărim băltoaca împreună', 4, 'A'::public.completion_mode, ARRAY['pahar cu apă']::text[], ARRAY['Voi turnați puțin. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z5-fizic', '1-2', 28, 5, 'fizic'::public.pillar, 'Spălăm mâinile după noroi', 5, 'A'::public.completion_mode, ARRAY['cizme','preș']::text[], ARRAY['Frecați cizma pe preș pe scurt.','„Cizmă. Preș.”']::text[], 'A frecat cizma sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z5-mental', '1-2', 28, 5, 'mental'::public.pillar, 'Mâini curate', 3, 'A'::public.completion_mode, ARRAY['cizmă']::text[], ARRAY['Arătați cizma: „Murdar.” pe scurt.','După șters: „Curat.”']::text[], 'A auzit murdar și curat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z5-resurse', '1-2', 28, 5, 'resurse'::public.pillar, 'Prosopul la loc', 4, 'A'::public.completion_mode, ARRAY['cizme']::text[], ARRAY['Așezați cizmele curate lângă ușă.','„Cizme. La loc.”']::text[], 'A ajutat să așeze cizmele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z5-social', '1-2', 28, 5, 'social'::public.pillar, 'Spălăm mâinile împreună', 3, 'A'::public.completion_mode, ARRAY['preș']::text[], ARRAY['Voi ștergeți. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z6-fizic', '1-2', 28, 6, 'fizic'::public.pillar, 'Noroi, apoi apă', 5, 'A'::public.completion_mode, ARRAY['apă','săpun']::text[], ARRAY['Spălați mâinile pe scurt după curte.','„Mâini. Apă.” fără grabă.']::text[], 'A atins apa sau săpunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s28-2-3-z6-mental', '1-2', 28, 6, 'mental'::public.pillar, 'Moale, apoi ud', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noroi.” pe scurt, amintire.','La chiuvetă: „Apă. Curat.”']::text[], 'A auzit noroi și apă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z6-resurse', '1-2', 28, 6, 'resurse'::public.pillar, 'Cizmele la loc, după curte', 4, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Ștergeți mâinile. Puneți prosopul la loc.','„Prosop. La loc.”']::text[], 'A ajutat cu prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z6-social', '1-2', 28, 6, 'social'::public.pillar, 'Ne ștergem împreună', 4, 'A'::public.completion_mode, ARRAY['apă']::text[], ARRAY['Spălați pe rând la chiuvetă.','„Împreună.” fără forțare.']::text[], 'A spălat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z7-fizic', '1-2', 28, 7, 'fizic'::public.pillar, 'Plimbare cu cizmele', 7, 'A'::public.completion_mode, ARRAY['cizme dacă e noroi']::text[], ARRAY['El dictează direcția în curte pe scurt, cu adult.','La final: o privire la noroi sau iarbă dacă vrea.']::text[], 'A mers liber în curte pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z7-mental', '1-2', 28, 7, 'mental'::public.pillar, 'Cartea cu curtea', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați pământ, apă sau curte dacă e clar: „Curte.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z7-resurse', '1-2', 28, 7, 'resurse'::public.pillar, 'Cizmele și haina la loc', 4, 'A'::public.completion_mode, ARRAY['cizme','cârpă']::text[], ARRAY['Puneți cizmele lângă ușă, cârpa la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi'),
('s28-2-3-z7-social', '1-2', 28, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Dezgheț și noroi')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
