insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s29-2-3-z1-fizic', '1-2', 29, 1, 'fizic'::public.pillar, 'Degetul pe mugure', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['În curte sau pe pervaz: atingeți iarba sau o frunză verde pe scurt.','„Iarbă. Verde.” 10–20 de secunde.']::text[], 'A atins iarba sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z1-mental', '1-2', 29, 1, 'mental'::public.pillar, 'Uite iarba nouă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Verde.”','„Iarbă.” pe scurt.']::text[], 'A auzit verde și iarbă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z1-resurse', '1-2', 29, 1, 'resurse'::public.pillar, 'Ramura rămâne pe loc', 4, 'A'::public.completion_mode, ARRAY['ghiveci cu plantă']::text[], ARRAY['Așezați ghiveciul pe pervaz sau masă.','„Plantă. La loc.”']::text[], 'A ajutat să așeze ghiveciul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z1-social', '1-2', 29, 1, 'social'::public.pillar, 'Arătăm mugurele', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă iarbă sau plantă unul lângă altul.','„Împreună. Verde.” fără grabă.']::text[], 'A stat lângă voi la verde.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z2-fizic', '1-2', 29, 2, 'fizic'::public.pillar, 'Pași scurți pe iarbă', 4, 'A'::public.completion_mode, ARRAY['ramură cu muguri sau plantă']::text[], ARRAY['Atingeți un mugure pe scurt cu degetul.','„Mugure.” 10–15 de secunde.']::text[], 'A atins mugurele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z2-mental', '1-2', 29, 2, 'mental'::public.pillar, 'Verde, iarbă nouă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați mugurele: „Mugure.”','Arătați o frunză dacă e: „Frunză.”']::text[], 'A auzit mugure și frunză.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z2-resurse', '1-2', 29, 2, 'resurse'::public.pillar, 'Pantofii după iarbă', 4, 'A'::public.completion_mode, ARRAY['plantă sau ramură']::text[], ARRAY['Puneți planta sau ramura la loc pe scurt.','„La loc. Plantă.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s29-2-3-z2-social', '1-2', 29, 2, 'social'::public.pillar, 'Pași pe iarbă împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați mugurele adultului: „Uite.”','Stați pe scurt, fără forțare.']::text[], 'A arătat sau a privit mugurele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z3-fizic', '1-2', 29, 3, 'fizic'::public.pillar, 'Atingem o frunză mică', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['În curte: câțiva pași pe iarbă, cu adult.','„Iarbă. Pași.” pe scurt.']::text[], 'A făcut câțiva pași pe iarbă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z3-mental', '1-2', 29, 3, 'mental'::public.pillar, 'Mică — sau mare?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Iarbă.”','Arătați pământul: „Pământ.”']::text[], 'A auzit iarbă și pământ.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z3-resurse', '1-2', 29, 3, 'resurse'::public.pillar, 'Frunza rămâne pe plantă', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă după curte.','„Pantofi. La loc.”']::text[], 'A ajutat cu pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z3-social', '1-2', 29, 3, 'social'::public.pillar, 'Atingem frunza pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți câțiva pași lângă adult pe iarbă.','„Împreună. Iarbă.” fără forțare.']::text[], 'A mers lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z4-fizic', '1-2', 29, 4, 'fizic'::public.pillar, 'Udăm puțin la rădăcină', 4, 'A'::public.completion_mode, ARRAY['plantă fără spini']::text[], ARRAY['Apropiați nasul pe scurt de frunză.','„Miros. Verde.” fără a forța.']::text[], 'A mirosit sau a privit planta.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z4-mental', '1-2', 29, 4, 'mental'::public.pillar, 'Plantă verde', 3, 'A'::public.completion_mode, ARRAY['plantă']::text[], ARRAY['Arătați planta: „Plantă.”','„Verde.” pe scurt.']::text[], 'A auzit plantă și verde.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s29-2-3-z4-resurse', '1-2', 29, 4, 'resurse'::public.pillar, 'Stropitoarea la loc', 4, 'A'::public.completion_mode, ARRAY['ghiveci']::text[], ARRAY['Puneți planta pe pervaz.','„Plantă. La loc.”']::text[], 'A ajutat cu planta.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z4-social', '1-2', 29, 4, 'social'::public.pillar, 'Udăm împreună', 3, 'A'::public.completion_mode, ARRAY['plantă']::text[], ARRAY['Voi mirosiți. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z5-fizic', '1-2', 29, 5, 'fizic'::public.pillar, 'Ne aplecăm la mugure', 5, 'A'::public.completion_mode, ARRAY['stropitoare mică sau pahar cu apă']::text[], ARRAY['Turnați puțină apă la rădăcină, cu adult.','„Apă. Plantă.” pe scurt.']::text[], 'A turnat sau a privit apa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z5-mental', '1-2', 29, 5, 'mental'::public.pillar, 'Mugure și frunză', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați apa: „Apă.”','Arătați planta: „Plantă. Beată.” pe scurt.']::text[], 'A auzit apă și plantă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z5-resurse', '1-2', 29, 5, 'resurse'::public.pillar, 'Mâinile după plantă', 4, 'A'::public.completion_mode, ARRAY['stropitoare sau pahar']::text[], ARRAY['Puneți stropitoarea sau paharul la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z5-social', '1-2', 29, 5, 'social'::public.pillar, 'Privim planta împreună', 4, 'A'::public.completion_mode, ARRAY['stropitoare mică']::text[], ARRAY['Voi turnați puțin. „Acum tu.”','Așteptați fără forțare.']::text[], 'A turnat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z6-fizic', '1-2', 29, 6, 'fizic'::public.pillar, 'Trei pași printre fire de iarbă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Luați o frunză de pe pământ pe scurt.','„Frunză.” Arătați-o 10–15 de secunde.']::text[], 'A ținut frunza sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s29-2-3-z6-mental', '1-2', 29, 6, 'mental'::public.pillar, 'Iarbă nouă sub picior', 3, 'A'::public.completion_mode, ARRAY['frunză']::text[], ARRAY['Arătați frunza: „Frunză.”','Arătați iarba: „Iarbă.”']::text[], 'A auzit frunză și iarbă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z6-resurse', '1-2', 29, 6, 'resurse'::public.pillar, 'Pantofii la ușă după iarbă', 4, 'A'::public.completion_mode, ARRAY['coș sau găleată mică']::text[], ARRAY['Puneți frunza în coș sau înapoi afară.','„Frunză. La loc.”']::text[], 'A pus frunza sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z6-social', '1-2', 29, 6, 'social'::public.pillar, 'Iarba, unul lângă altul', 3, 'A'::public.completion_mode, ARRAY['frunză']::text[], ARRAY['Duceți frunza la adult: „Uite.”','Stați pe scurt, fără grabă.']::text[], 'A arătat frunza sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z7-fizic', '1-2', 29, 7, 'fizic'::public.pillar, 'Plimbare pe iarbă', 7, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția în curte pe scurt, cu adult.','La final: o privire la iarbă sau mugure dacă vrea.']::text[], 'A mers liber pe scurt în curte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z7-mental', '1-2', 29, 7, 'mental'::public.pillar, 'Cartea cu plante', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați iarbă, plantă sau verde dacă e clar: „Verde.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z7-resurse', '1-2', 29, 7, 'resurse'::public.pillar, 'Stropitoarea și pantofii la loc', 4, 'A'::public.completion_mode, ARRAY['ghiveci','stropitoare']::text[], ARRAY['Puneți planta pe pervaz, stropitoarea la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă'),
('s29-2-3-z7-social', '1-2', 29, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Muguri și iarbă nouă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s30-2-3-z1-fizic', '1-2', 30, 1, 'fizic'::public.pillar, 'Stăm la geam dimineața', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la geam dimineața pe scurt.','Stați liniștiți 10–20 de secunde: „Urechi. Afară.”']::text[], 'A stat la geam pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z1-mental', '1-2', 30, 1, 'mental'::public.pillar, 'Auzim o pasăre?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă auziți: „Pasăre.” pe scurt.','„Afară.” fără grabă.']::text[], 'A auzit pasăre sau afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z1-resurse', '1-2', 30, 1, 'resurse'::public.pillar, 'Perdeaua la loc după geam', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Trageți perdeaua ca să auziți afară.','„Perdea. Geam.”']::text[], 'A ajutat să tragă perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z1-social', '1-2', 30, 1, 'social'::public.pillar, 'Ascultăm împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam unul lângă altul.','„Împreună. Ascultăm.” fără grabă.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z2-fizic', '1-2', 30, 2, 'fizic'::public.pillar, 'Arătăm sus, pe creangă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam sau afară: arătați cu degetul spre cer sau copac.','„Uite. Sus.” pe scurt.']::text[], 'A arătat sau a privit sus.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z2-mental', '1-2', 30, 2, 'mental'::public.pillar, 'Pasărea e sus', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați sus: „Sus.”','„Pasăre.” dacă e vizibilă, pe scurt.']::text[], 'A auzit sus și pasăre.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z2-resurse', '1-2', 30, 2, 'resurse'::public.pillar, 'Mâna jos după arătat', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Lăsați geamul liber, fără obiecte pe pervaz pe scurt.','„Geam. Liber.”']::text[], 'A privit geamul liber.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s30-2-3-z2-social', '1-2', 30, 2, 'social'::public.pillar, 'Arătăm pasărea', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Uite.”','Adultul privește pe scurt, fără forțare.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z3-fizic', '1-2', 30, 3, 'fizic'::public.pillar, 'Ieșim scurt, urechile afară', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ieșiți în curte pe scurt, cu adult.','Stați 15–20 de secunde: „Urechi. Păsări.”']::text[], 'A ieșit pe scurt și a ascultat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z3-mental', '1-2', 30, 3, 'mental'::public.pillar, 'Sunet în casă — sau afară?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['În casă: „Casă.” pe scurt.','Afară: „Afară. Pasăre.”']::text[], 'A auzit casă și afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z3-resurse', '1-2', 30, 3, 'resurse'::public.pillar, 'Pantofii după ascultat', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Intrați. Închideți ușa pe scurt.','„Ușă. Gata.”']::text[], 'A ajutat la ușă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z3-social', '1-2', 30, 3, 'social'::public.pillar, 'Ascultăm afară împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați afară lângă adult pe scurt.','„Împreună. Ascultăm.” fără forțare.']::text[], 'A stat afară lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z4-fizic', '1-2', 30, 4, 'fizic'::public.pillar, 'Brațele ca aripile', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți un sunet scurt de pasăre: „Cip-cip.”','El poate imita dacă vrea, 10–15 de secunde.']::text[], 'A auzit sau a imitat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z4-mental', '1-2', 30, 4, 'mental'::public.pillar, 'Aripile se mișcă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Ciripit.” pe scurt.','Apoi: „Liniște.” câteva secunde.']::text[], 'A auzit ciripit și liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s30-2-3-z4-resurse', '1-2', 30, 4, 'resurse'::public.pillar, 'Facem loc pentru aripi', 4, 'A'::public.completion_mode, ARRAY['jucărie pasăre sau figurină']::text[], ARRAY['Așezați jucăria-pasăre pe raft după joacă.','„Pasăre. La loc.”']::text[], 'A pus jucăria la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z4-social', '1-2', 30, 4, 'social'::public.pillar, 'Aripile împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi faceți „cip-cip.” „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z5-fizic', '1-2', 30, 5, 'fizic'::public.pillar, 'Privim pasărea care zboară', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['La geam sau afară: priviți o pasăre dacă apare.','„Pasăre.” 10–20 de secunde, fără grabă.']::text[], 'A privit pasărea sau cerul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z5-mental', '1-2', 30, 5, 'mental'::public.pillar, 'Zboară', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Pasăre.”','„Zboară.” pe scurt, dacă e cazul.']::text[], 'A auzit pasăre și zboară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z5-resurse', '1-2', 30, 5, 'resurse'::public.pillar, 'Rămânem pe loc, privim', 4, 'A'::public.completion_mode, ARRAY['binoclu de jucărie sau tub de hârtie']::text[], ARRAY['Dacă ați privit prin el, puneți-l pe raft.','„La loc.” pe scurt.']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z5-social', '1-2', 30, 5, 'social'::public.pillar, 'Zborul, unul lângă altul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul la geam.','„Împreună. Pasăre.” fără grabă.']::text[], 'A privit împreună pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z6-fizic', '1-2', 30, 6, 'fizic'::public.pillar, 'Ciripim încet, ca pasărea', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați brațele și le coborâți pe scurt.','„Aripi.” 15–20 de secunde.']::text[], 'A mișcat brațele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s30-2-3-z6-mental', '1-2', 30, 6, 'mental'::public.pillar, 'Cioc, un sunet', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați brațele: „Aripi.”','Arătați corpul: „Corp.”']::text[], 'A auzit aripi și corp.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z6-resurse', '1-2', 30, 6, 'resurse'::public.pillar, 'Gura, apoi liniște', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți 1–2 obiecte la loc ca să fie loc.','„La loc. Liber.”']::text[], 'A ajutat să elibereze spațiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z6-social', '1-2', 30, 6, 'social'::public.pillar, 'Ciripim pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mișcați brațele împreună 20–30 de secunde.','„Împreună. Aripi.” fără forțare.']::text[], 'A mișcat brațele lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z7-fizic', '1-2', 30, 7, 'fizic'::public.pillar, 'Plimbare de dimineață', 7, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară sau la geam pe scurt.','La final: 10 secunde de ascultat dacă vrea.']::text[], 'A mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z7-mental', '1-2', 30, 7, 'mental'::public.pillar, 'Cartea cu păsări', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați o pasăre dacă e clar: „Pasăre.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z7-resurse', '1-2', 30, 7, 'resurse'::public.pillar, 'Cartea pe raft', 4, 'A'::public.completion_mode, ARRAY['carte','jucărie']::text[], ARRAY['Puneți cartea pe raft, jucăria la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața'),
('s30-2-3-z7-social', '1-2', 30, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Păsări dimineața')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s31-2-3-z1-fizic', '1-2', 31, 1, 'fizic'::public.pillar, 'Punem sămânța în pământ', 4, 'A'::public.completion_mode, ARRAY['sămânță mare: fasole sau floarea-soarelui']::text[], ARRAY['Puneți o sămânță în palmă pe scurt.','„Sămânță.” 10–15 de secunde.']::text[], 'A ținut sămânța sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z1-mental', '1-2', 31, 1, 'mental'::public.pillar, 'Sămânța e mică', 3, 'A'::public.completion_mode, ARRAY['sămânță']::text[], ARRAY['Arătați sămânța: „Sămânță.”','„Mică.” pe scurt.']::text[], 'A auzit sămânță și mică.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z1-resurse', '1-2', 31, 1, 'resurse'::public.pillar, 'Pământul acoperă sămânța', 4, 'A'::public.completion_mode, ARRAY['cutie mică','semințe']::text[], ARRAY['Puneți semințele în cutie.','„Semințe. La loc.”']::text[], 'A ajutat să pună semințele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z1-social', '1-2', 31, 1, 'social'::public.pillar, 'Punem sămânța împreună', 3, 'A'::public.completion_mode, ARRAY['sămânță']::text[], ARRAY['Arătați sămânța: „Uite.”','Stați pe scurt, fără grabă.']::text[], 'A arătat sămânța sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z2-fizic', '1-2', 31, 2, 'fizic'::public.pillar, 'Udăm sămânța', 6, 'A'::public.completion_mode, ARRAY['ghiveci','pământ','sămânță']::text[], ARRAY['Faceți o gaură mică în pământ, cu adult.','Puneți sămânța: „Sămânță. Pământ.”']::text[], 'A pus sămânța sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z2-mental', '1-2', 31, 2, 'mental'::public.pillar, 'Pământ ud — sau uscat?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați sămânța: „Sămânță.”','Arătați pământul: „Pământ.”']::text[], 'A auzit sămânță și pământ.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z2-resurse', '1-2', 31, 2, 'resurse'::public.pillar, 'Stropitoarea la loc', 4, 'A'::public.completion_mode, ARRAY['ghiveci']::text[], ARRAY['Așezați ghiveciul pe masă sau pervaz.','„Ghiveci. La loc.”']::text[], 'A ajutat cu ghiveciul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s31-2-3-z2-social', '1-2', 31, 2, 'social'::public.pillar, 'Udăm pe rând', 4, 'A'::public.completion_mode, ARRAY['sămânță','ghiveci']::text[], ARRAY['Voi puneți o sămânță. „Acum tu.”','Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z3-fizic', '1-2', 31, 3, 'fizic'::public.pillar, 'Așteptăm lângă ghiveci', 5, 'A'::public.completion_mode, ARRAY['pahar cu apă sau stropitoare mică']::text[], ARRAY['Turnați puțină apă pe pământ, cu adult.','„Apă. Udat.” pe scurt.']::text[], 'A turnat apa sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z3-mental', '1-2', 31, 3, 'mental'::public.pillar, 'Încă nu se vede', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați apa: „Apă.”','„Udat.” pe scurt.']::text[], 'A auzit apă și udat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z3-resurse', '1-2', 31, 3, 'resurse'::public.pillar, 'Ghiveciul pe pervaz', 4, 'A'::public.completion_mode, ARRAY['pahar sau stropitoare']::text[], ARRAY['Puneți paharul la chiuvetă sau pe masă.','„Pahar. La loc.”']::text[], 'A ajutat cu paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z3-social', '1-2', 31, 3, 'social'::public.pillar, 'Privim ghiveciul împreună', 4, 'A'::public.completion_mode, ARRAY['stropitoare mică']::text[], ARRAY['Țineți stropitoarea împreună pe scurt.','„Împreună. Apă.” fără forțare.']::text[], 'A ținut sau a privit udatul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z4-fizic', '1-2', 31, 4, 'fizic'::public.pillar, 'Degetul pe pământul ud', 4, 'A'::public.completion_mode, ARRAY['ghiveci cu pământ']::text[], ARRAY['Atingeți pământul umed cu degetul pe scurt.','„Pământ. Umed.” 10–15 de secunde.']::text[], 'A atins pământul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z4-mental', '1-2', 31, 4, 'mental'::public.pillar, 'Moale', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați pământul: „Umed.” pe scurt.','Dacă e uscat undeva: „Uscat.”']::text[], 'A auzit umed și uscat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s31-2-3-z4-resurse', '1-2', 31, 4, 'resurse'::public.pillar, 'Mâna pe prosop', 4, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Ștergeți degetele pe scurt.','„Prosop. La loc.”']::text[], 'A șters mâinile sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z4-social', '1-2', 31, 4, 'social'::public.pillar, 'Atingem pământul pe rând', 3, 'A'::public.completion_mode, ARRAY['ghiveci']::text[], ARRAY['Voi atingeți. „Acum tu.”','Așteptați fără forțare.']::text[], 'A atins sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z5-fizic', '1-2', 31, 5, 'fizic'::public.pillar, 'Cărăm stropitoarea', 5, 'A'::public.completion_mode, ARRAY['stropitoare mică cu puțină apă']::text[], ARRAY['El duce stropitoarea câțiva pași, cu adult aproape.','„Stropitoare. Apă.” pe scurt.']::text[], 'A cărat stropitoarea sau a ținut-o.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z5-mental', '1-2', 31, 5, 'mental'::public.pillar, 'Greu cu apă — sau ușor?', 3, 'A'::public.completion_mode, ARRAY['stropitoare']::text[], ARRAY['Arătați stropitoarea: „Stropitoare.”','„Grijă. Plantă.” pe scurt.']::text[], 'A auzit stropitoare și grijă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z5-resurse', '1-2', 31, 5, 'resurse'::public.pillar, 'Stropitoarea lângă plantă', 4, 'A'::public.completion_mode, ARRAY['stropitoare']::text[], ARRAY['Așezați stropitoarea lângă ghiveci.','„La loc. Stropitoare.”']::text[], 'A așezat stropitoarea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z5-social', '1-2', 31, 5, 'social'::public.pillar, 'Cărăm împreună', 4, 'A'::public.completion_mode, ARRAY['stropitoare']::text[], ARRAY['Voi cărați. „Acum tu.”','Așteptați fără forțare.']::text[], 'A cărat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z6-fizic', '1-2', 31, 6, 'fizic'::public.pillar, 'A crescut ceva?', 4, 'A'::public.completion_mode, ARRAY['ghiveci plantat']::text[], ARRAY['Priviți pământul din ghiveci pe scurt.','„Plantă.” 10–20 de secunde, fără așteptări.']::text[], 'A privit ghiveciul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s31-2-3-z6-mental', '1-2', 31, 6, 'mental'::public.pillar, 'Sămânță, apoi plantă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Sămânță.” pe scurt.','„Apoi. Plantă.” fără grabă.']::text[], 'A auzit sămânță și plantă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z6-resurse', '1-2', 31, 6, 'resurse'::public.pillar, 'Ghiveciul rămâne la loc', 4, 'A'::public.completion_mode, ARRAY['ghiveci']::text[], ARRAY['Mutăți ghiveciul la lumină pe pervaz.','„Lumină. La loc.”']::text[], 'A ajutat să mute ghiveciul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z6-social', '1-2', 31, 6, 'social'::public.pillar, 'Privim dacă a crescut', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă ghiveci unul lângă altul.','„Împreună. Plantă.” fără grabă.']::text[], 'A privit împreună pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z7-fizic', '1-2', 31, 7, 'fizic'::public.pillar, 'Plimbare până la ghiveci', 7, 'A'::public.completion_mode, ARRAY['stropitoare dacă vrea']::text[], ARRAY['El dictează direcția prin casă sau curte pe scurt.','La final: o stropire mică dacă vrea.']::text[], 'A mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z7-mental', '1-2', 31, 7, 'mental'::public.pillar, 'Cartea cu grădina', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați plantă, pământ sau apă dacă e clar: „Plantă.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z7-resurse', '1-2', 31, 7, 'resurse'::public.pillar, 'Stropitoarea la loc', 4, 'A'::public.completion_mode, ARRAY['cutie cu semințe','stropitoare']::text[], ARRAY['Puneți cutia și stropitoarea la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat'),
('s31-2-3-z7-social', '1-2', 31, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Semințe și udat')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s32-2-3-z1-fizic', '1-2', 32, 1, 'fizic'::public.pillar, 'Ținem balonul de sfoară', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['În curte: țineți sfoara împreună pe scurt.','„Balon.” 10–20 de secunde.']::text[], 'A ținut sfoara sau a atins balonul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z1-mental', '1-2', 32, 1, 'mental'::public.pillar, 'Balonul e ușor', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Arătați balonul: „Balon.”','„Ușor.” pe scurt.']::text[], 'A auzit balon și ușor.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z1-resurse', '1-2', 32, 1, 'resurse'::public.pillar, 'Balonul lângă ușă', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Așezați balonul (sfoara strânsă) lângă ușă înainte să ieșiți.','„Balon. Aici.”']::text[], 'A ajutat să așeze balonul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z1-social', '1-2', 32, 1, 'social'::public.pillar, 'Ținem balonul împreună', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Stați afară lângă adult, amândoi pe sfoară.','„Împreună. Balon.” fără forțare.']::text[], 'A fost prezent cu balonul afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z2-fizic', '1-2', 32, 2, 'fizic'::public.pillar, 'Bătem ușor în balon', 5, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Bateți ușor o dată în balon, cu adult.','„Balon. Bătut.” fără grabă.']::text[], 'A bătut în balon sau a atins-o.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z2-mental', '1-2', 32, 2, 'mental'::public.pillar, 'Balonul e moale', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Atingeți balonul: „Moale.” pe scurt.','„Balon.”']::text[], 'A auzit moale (și balon).', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z2-resurse', '1-2', 32, 2, 'resurse'::public.pillar, 'Balonul pe scaun, la loc', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Așezați balonul pe scaun când nu jucați (sfoara strânsă).','„Balon. Aici.”']::text[], 'A așezat balonul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s32-2-3-z2-social', '1-2', 32, 2, 'social'::public.pillar, 'Bătem pe rând', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Voi bateți ușor. „Acum tu.”','Așteptați fără forțare.']::text[], 'A bătut sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z3-fizic', '1-2', 32, 3, 'fizic'::public.pillar, 'Balonul sus, deasupra capului', 5, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Ridicați balonul deasupra capului pe scurt, cu adult.','„Sus. Balon.”']::text[], 'A privit balonul sus sau a ținut sfoara.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z3-mental', '1-2', 32, 3, 'mental'::public.pillar, 'Sus — sau jos?', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Ridicați: „Sus.”','Coborâți aproape de sol: „Jos.”']::text[], 'A auzit sus și jos.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z3-resurse', '1-2', 32, 3, 'resurse'::public.pillar, 'Sfoara strânsă în mână', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Înfășurați sfoara pe scurt în mână.','„Sfoară. Strâns.”']::text[], 'A atins sfoara strânsă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z3-social', '1-2', 32, 3, 'social'::public.pillar, 'Ridicăm balonul împreună', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Ridicați împreună pe scurt.','„Împreună. Sus.” fără forțare.']::text[], 'A ținut sfoara la ridicare sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z4-fizic', '1-2', 32, 4, 'fizic'::public.pillar, 'Umblăm cu balonul în curte', 5, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Mergeți câțiva pași ținând sfoara.','„Balon. Pași.”']::text[], 'A mers cu sfoara sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z4-mental', '1-2', 32, 4, 'mental'::public.pillar, 'Balonul pe iarbă', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Lăsați balonul să atingă iarba pe scurt. „Balon. Iarbă.”','Întrebați: „Unde e?”']::text[], 'A privit sau a arătat balonul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s32-2-3-z4-resurse', '1-2', 32, 4, 'resurse'::public.pillar, 'Balonul nu rămâne afară', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Aduceți balonul lângă ușă după joacă.','„Balon. La ușă.”']::text[], 'A adus balonul sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z4-social', '1-2', 32, 4, 'social'::public.pillar, 'Ne jucăm cu balonul', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Căutați / arătați balonul pe scurt lângă adult.','„Împreună. Unde e?” fără grabă.']::text[], 'A căutat sau a arătat balonul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z5-fizic', '1-2', 32, 5, 'fizic'::public.pillar, 'Mergem ținând sfoara', 5, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Mergeți ținând sfoara (nu loviți cu piciorul).','„Sfoară. Pași.”']::text[], 'A ținut sfoara la mers sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z5-mental', '1-2', 32, 5, 'mental'::public.pillar, 'Sfoară lungă — sau scurtă?', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Arătați sfoara desfășurată: „Lungă.”','Apoi strânsă: „Scurtă.”']::text[], 'A auzit lungă și scurtă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z5-resurse', '1-2', 32, 5, 'resurse'::public.pillar, 'Sfoara înfășurată, la loc', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară','cui sau cutie']::text[], ARRAY['Înfășurați sfoara; puneți balonul pe cui / în cutie.','„La loc.”']::text[], 'A ajutat să pună balonul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z5-social', '1-2', 32, 5, 'social'::public.pillar, 'Mergem cu balonul împreună', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Mergeți amândoi pe sfoară pe scurt.','„Împreună. Pași.” fără forțare.']::text[], 'A mers lângă adult cu sfoara sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z6-fizic', '1-2', 32, 6, 'fizic'::public.pillar, 'Balonul se leagănă', 5, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Legănați ușor balonul de sfoară pe scurt.','„Balon. Legăn.”']::text[], 'A privit legănatul sau a ținut sfoara.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s32-2-3-z6-mental', '1-2', 32, 6, 'mental'::public.pillar, 'Se mișcă în aer', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Arătați mișcarea: „Aer.”','„Balon.” pe scurt.']::text[], 'A auzit aer / balon.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z6-resurse', '1-2', 32, 6, 'resurse'::public.pillar, 'Balonul în casă, la loc', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară','cui sau cutie']::text[], ARRAY['Intrați; puneți balonul pe cui / în cutie.','„Balon. La loc.”']::text[], 'A pus balonul la loc sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z6-social', '1-2', 32, 6, 'social'::public.pillar, 'Arătăm balonul', 3, 'A'::public.completion_mode, ARRAY['balon cu sfoară']::text[], ARRAY['Intrați lângă adult cu balonul.','„Împreună. Uite.” fără grabă.']::text[], 'A intrat cu balonul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z7-fizic', '1-2', 32, 7, 'fizic'::public.pillar, 'Plimbare cu balonul', 7, 'A'::public.completion_mode, ARRAY['balon cu sfoară dacă vrea']::text[], ARRAY['El dictează direcția în curte pe scurt, cu adult.','La final: sfoara în mână dacă vrea.']::text[], 'A mers liber pe scurt în curte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z7-mental', '1-2', 32, 7, 'mental'::public.pillar, 'Cartea cu balonul', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați balon / sfoară / afară dacă e clar: „Balon.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z7-resurse', '1-2', 32, 7, 'resurse'::public.pillar, 'Balonul pe cui', 4, 'A'::public.completion_mode, ARRAY['balon cu sfoară','pantofi']::text[], ARRAY['Balonul pe cui; pantofii lângă ușă.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară'),
('s32-2-3-z7-social', '1-2', 32, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Balonul afară')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
