insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s33-2-3-z1-fizic', '1-2', 33, 1, 'fizic'::public.pillar, 'Lopățica în nisip', 5, 'A'::public.completion_mode, ARRAY['lopățică','nisip în cutie sau pe plajă mică']::text[], ARRAY['Luați lopățica. Scoateți puțin nisip pe scurt.','„Lopățică. Nisip.” 10–20 de secunde.']::text[], 'A atins lopățica / nisipul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z1-mental', '1-2', 33, 1, 'mental'::public.pillar, 'Nisipul e moale', 3, 'A'::public.completion_mode, ARRAY['nisip']::text[], ARRAY['Arătați nisipul: „Nisip.”','„Moale.” pe scurt.']::text[], 'A auzit nisip și moale.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z1-resurse', '1-2', 33, 1, 'resurse'::public.pillar, 'Găleata lângă nisip', 4, 'A'::public.completion_mode, ARRAY['găleată mică']::text[], ARRAY['Așezați găleata lângă nisip.','„Găleată. Aici.”']::text[], 'A ajutat să așeze găleata.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z1-social', '1-2', 33, 1, 'social'::public.pillar, 'Umplem împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă nisip unul lângă altul.','„Împreună. Nisip.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z2-fizic', '1-2', 33, 2, 'fizic'::public.pillar, 'Punem nisip în găleată', 5, 'A'::public.completion_mode, ARRAY['găleată mică','nisip']::text[], ARRAY['Puneți puțin nisip în găleată cu mâna, cu adult.','„Nisip. Găleată.” pe scurt.']::text[], 'A pus nisip sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z2-mental', '1-2', 33, 2, 'mental'::public.pillar, 'Plină — sau goală?', 3, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Arătați găleata cu nisip: „Plină.”','Goliți puțin: „Goală.” pe scurt.']::text[], 'A auzit plină și goală.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z2-resurse', '1-2', 33, 2, 'resurse'::public.pillar, 'Lopățica la loc', 4, 'A'::public.completion_mode, ARRAY['lopățică']::text[], ARRAY['Puneți lopățica pe raft sau lângă găleată.','„Lopățică. La loc.”']::text[], 'A ajutat să pună lopățica la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s33-2-3-z2-social', '1-2', 33, 2, 'social'::public.pillar, 'Umplem pe rând', 5, 'A'::public.completion_mode, ARRAY['găleată','nisip']::text[], ARRAY['Voi puneți puțin nisip.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a pus nisip.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z3-fizic', '1-2', 33, 3, 'fizic'::public.pillar, 'Săpăm o gropiță', 5, 'A'::public.completion_mode, ARRAY['găleată cu nisip']::text[], ARRAY['Înclinați găleata și turnați nisipul pe scurt, cu adult.','„Turnăm. Nisip.” 10–20 de secunde.']::text[], 'A turnat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z3-mental', '1-2', 33, 3, 'mental'::public.pillar, 'Adânc — sau la suprafață?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați nisipul pe pământ: „Jos.”','„Nisip.” pe scurt.']::text[], 'A auzit jos și nisip.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z3-resurse', '1-2', 33, 3, 'resurse'::public.pillar, 'Nisipul înapoi', 4, 'A'::public.completion_mode, ARRAY['cutie cu nisip','găleată']::text[], ARRAY['Puneți nisipul înapoi în cutie pe scurt.','„Nisip. La loc.”']::text[], 'A ajutat să strângă nisipul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z3-social', '1-2', 33, 3, 'social'::public.pillar, 'Săpăm unul lângă altul', 5, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Țineți găleata împreună și turnați puțin.','„Împreună. Turnăm.” fără forțare.']::text[], 'A ținut găleata sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z4-fizic', '1-2', 33, 4, 'fizic'::public.pillar, 'Facem o formă', 5, 'A'::public.completion_mode, ARRAY['nisip']::text[], ARRAY['Treceți degetele prin nisip pe scurt.','„Degete. Nisip.” 15–20 de secunde.']::text[], 'A mișcat degetele în nisip sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z4-mental', '1-2', 33, 4, 'mental'::public.pillar, 'Rotundă — sau lungă?', 3, 'A'::public.completion_mode, ARRAY['nisip']::text[], ARRAY['Arătați urma degetului: „Urmă.”','„Nisip.” pe scurt.']::text[], 'A auzit urmă și nisip.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s33-2-3-z4-resurse', '1-2', 33, 4, 'resurse'::public.pillar, 'Nisipul rămâne afară', 4, 'A'::public.completion_mode, ARRAY['lopată mică de nisip']::text[], ARRAY['Puneți lopata lângă găleată sau pe raft.','„Lopată. La loc.”']::text[], 'A ajutat să pună lopata la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z4-social', '1-2', 33, 4, 'social'::public.pillar, 'Arătăm forma', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați urma din nisip: „Uite.”','Adultul privește pe scurt, fără grabă.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z5-fizic', '1-2', 33, 5, 'fizic'::public.pillar, 'Cărăm găleata', 5, 'A'::public.completion_mode, ARRAY['găleată mică cu puțin nisip']::text[], ARRAY['Cărați găleata doi–trei pași, cu adult.','„Găleată. Pași.” pe scurt.']::text[], 'A cărat sau a mers lângă găleată.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z5-mental', '1-2', 33, 5, 'mental'::public.pillar, 'Greu — sau ușor?', 3, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Cu nisip: „Greu.” pe scurt.','Goală: „Ușor.”']::text[], 'A auzit greu și ușor.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z5-resurse', '1-2', 33, 5, 'resurse'::public.pillar, 'Turnăm nisipul înapoi', 4, 'A'::public.completion_mode, ARRAY['găleată','lopată mică']::text[], ARRAY['Puneți găleata și lopata împreună pe raft.','„La loc. Gata.”']::text[], 'A ajutat să strângă uneltele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z5-social', '1-2', 33, 5, 'social'::public.pillar, 'Cărăm împreună', 5, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Țineți găleata împreună câțiva pași.','„Împreună. Cărăm.” fără forțare.']::text[], 'A ținut găleata sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z6-fizic', '1-2', 33, 6, 'fizic'::public.pillar, 'Lopățica și găleata, apoi gata', 5, 'A'::public.completion_mode, ARRAY['lopățică','găleată','nisip']::text[], ARRAY['Cu lopățica, puneți puțin nisip în găleată.','Apoi: „Gata.” pe scurt, cu adult.']::text[], 'A folosit lopățica / găleata sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s33-2-3-z6-mental', '1-2', 33, 6, 'mental'::public.pillar, 'Nisip pe mână', 3, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Arătați urma rotundă: „Rotund.”','„Găleată.” pe scurt.']::text[], 'A auzit rotund și găleată.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z6-resurse', '1-2', 33, 6, 'resurse'::public.pillar, 'Mâinile pe prosop', 4, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Ștergeți mâinile pe prosop pe scurt.', '„Prosop. La loc.”']::text[], 'A atins prosopul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z6-social', '1-2', 33, 6, 'social'::public.pillar, 'La nisip, unul lângă altul', 5, 'A'::public.completion_mode, ARRAY['formă','nisip']::text[], ARRAY['Voi apăsați forma.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a apăsat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z7-fizic', '1-2', 33, 7, 'fizic'::public.pillar, 'Plimbare pe nisip', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția în curte pe scurt, cu adult.','La final: o privire sau atingere la nisip dacă vrea.']::text[], 'A mers liber pe scurt în curte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z7-mental', '1-2', 33, 7, 'mental'::public.pillar, 'Cartea cu plaja', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați nisip, găleată sau plajă dacă e clar: „Nisip.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z7-resurse', '1-2', 33, 7, 'resurse'::public.pillar, 'Lopățica și găleata la loc', 4, 'A'::public.completion_mode, ARRAY['găleată','lopată mică']::text[], ARRAY['Puneți găleata și lopata pe raft.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată'),
('s33-2-3-z7-social', '1-2', 33, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Nisip și găleată')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s34-2-3-z1-fizic', '1-2', 34, 1, 'fizic'::public.pillar, 'Mâna face umbră', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ieșiți în curte la soare pe scurt, cu adult.','„Soare. Afară.” 15–20 de secunde.']::text[], 'A ieșit afară sau a privit soarele blând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z1-mental', '1-2', 34, 1, 'mental'::public.pillar, 'Uite umbra', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați umbra pe pământ: „Umbră.”','„Pământ.” pe scurt.']::text[], 'A auzit umbră și pământ.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z1-resurse', '1-2', 34, 1, 'resurse'::public.pillar, 'Mâna jos, umbra dispare', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă după curte.','„Pantofi. La loc.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z1-social', '1-2', 34, 1, 'social'::public.pillar, 'Facem umbră împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă umbră unul lângă altul.','„Împreună. Umbră.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z2-fizic', '1-2', 34, 2, 'fizic'::public.pillar, 'Umbra pe perete', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Țineți mâna în soare și priviți umbra pe pământ.','„Mână. Umbră.” 10–20 de secunde.']::text[], 'A mișcat mâna sau a privit umbra.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z2-mental', '1-2', 34, 2, 'mental'::public.pillar, 'Mare — sau mică?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați mâna: „Mână.”','Arătați umbra: „Umbră.” pe scurt.']::text[], 'A auzit mână și umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z2-resurse', '1-2', 34, 2, 'resurse'::public.pillar, 'Ne dăm la o parte', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți 1–2 obiecte la loc ca să vedeți umbra.','„La loc. Liber.”']::text[], 'A ajutat să elibereze spațiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s34-2-3-z2-social', '1-2', 34, 2, 'social'::public.pillar, 'Umbra pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați umbra mâinii: „Uite.”','Adultul privește pe scurt, fără forțare.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z3-fizic', '1-2', 34, 3, 'fizic'::public.pillar, 'Umbra pe jos, lungă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți câțiva pași pe umbra voastră sau pe umbra adultului.','„Pași. Umbră.” pe scurt.']::text[], 'A făcut pași pe umbră sau lângă ea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z3-mental', '1-2', 34, 3, 'mental'::public.pillar, 'Lungă — sau scurtă?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați umbra: „Lungă.” dacă e.','„Scurtă.” pe scurt dacă se schimbă.']::text[], 'A auzit lungă sau scurtă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z3-resurse', '1-2', 34, 3, 'resurse'::public.pillar, 'Pașii lângă umbră', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Intrați. Închideți ușa pe scurt.','„Ușă. Gata.”']::text[], 'A ajutat la ușă sau a intrat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z3-social', '1-2', 34, 3, 'social'::public.pillar, 'Urmărim umbra împreună', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți câțiva pași lângă adult pe umbră.','„Împreună. Pași.” fără forțare.']::text[], 'A mers lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z4-fizic', '1-2', 34, 4, 'fizic'::public.pillar, 'Intrăm în umbră', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Priviți umbra unei frunze sau crengi pe pământ.','„Frunză. Umbră.” 10–20 de secunde.']::text[], 'A privit umbra frunzei.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z4-mental', '1-2', 34, 4, 'mental'::public.pillar, 'Soare — sau umbră?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați copacul: „Copac.”','Arătați umbra: „Umbră.” pe scurt.']::text[], 'A auzit copac și umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s34-2-3-z4-resurse', '1-2', 34, 4, 'resurse'::public.pillar, 'Ieșim din umbră', 4, 'A'::public.completion_mode, ARRAY['coș mic']::text[], ARRAY['Puneți o frunză în coș dacă e pe pământ.','„Frunză. Coș.”']::text[], 'A pus frunza sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z4-social', '1-2', 34, 4, 'social'::public.pillar, 'Stăm în umbră împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați sub umbra copacului pe scurt.','„Împreună. Umbră.” fără grabă.']::text[], 'A stat pe scurt sub umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z5-fizic', '1-2', 34, 5, 'fizic'::public.pillar, 'Umbra merge cu noi', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați în soare: priviți umbra corpului pe pământ.','„Corp. Umbră.” 15–20 de secunde.']::text[], 'A privit umbra corpului.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z5-mental', '1-2', 34, 5, 'mental'::public.pillar, 'Umbra se mișcă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați copilul: „Tu.”','Arătați umbra: „Umbra ta.” pe scurt.']::text[], 'A auzit tu și umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z5-resurse', '1-2', 34, 5, 'resurse'::public.pillar, 'Ne oprim, umbra stă', 4, 'A'::public.completion_mode, ARRAY['pălărie sau șapcă']::text[], ARRAY['După soare: puneți pălăria pe cuier.','„Pălărie. La loc.”']::text[], 'A ajutat să pună pălăria la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z5-social', '1-2', 34, 5, 'social'::public.pillar, 'Mergem cu umbra', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul: două umbre pe pământ.','„Împreună. Umbre.” fără forțare.']::text[], 'A privit umbrele împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z6-fizic', '1-2', 34, 6, 'fizic'::public.pillar, 'Umbra unui copac', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mișcați mâna sau un obiect: urmăriți umbra pe scurt.','„Mișcă. Umbră.” 15–20 de secunde.']::text[], 'A urmărit umbra care se mișcă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s34-2-3-z6-mental', '1-2', 34, 6, 'mental'::public.pillar, 'Stă — sau se mișcă?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Umbra nemișcată: „Stă.”','Când mișcați: „Se mișcă.” pe scurt.']::text[], 'A auzit stă și se mișcă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z6-resurse', '1-2', 34, 6, 'resurse'::public.pillar, 'Ieșim de sub copac', 4, 'A'::public.completion_mode, ARRAY['obiect mic']::text[], ARRAY['Puneți obiectul pe raft după joacă.','„La loc.” pe scurt.']::text[], 'A ajutat să pună obiectul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z6-social', '1-2', 34, 6, 'social'::public.pillar, 'Sub copac, unul lângă altul', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi mișcați mâna.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a mișcat mâna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z7-fizic', '1-2', 34, 7, 'fizic'::public.pillar, 'Plimbare după umbră', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.','La final: o privire la umbră pe pământ dacă vrea.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z7-mental', '1-2', 34, 7, 'mental'::public.pillar, 'Cartea cu soarele', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați soare, umbră sau pământ dacă e clar: „Umbră.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z7-resurse', '1-2', 34, 7, 'resurse'::public.pillar, 'Pălăria la loc', 4, 'A'::public.completion_mode, ARRAY['pantofi','pălărie']::text[], ARRAY['Puneți pantofii lângă ușă, pălăria pe cuier.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ'),
('s34-2-3-z7-social', '1-2', 34, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbre pe pământ')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s35-2-3-z1-fizic', '1-2', 35, 1, 'fizic'::public.pillar, 'Stropi pe mână, afară', 5, 'A'::public.completion_mode, ARRAY['vas mic cu apă afară']::text[], ARRAY['Afară: atingeți apa din vas pe scurt, cu adult.','„Apă.” 10–20 de secunde.']::text[], 'A atins apa sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z1-mental', '1-2', 35, 1, 'mental'::public.pillar, 'E ud', 3, 'A'::public.completion_mode, ARRAY['vas cu apă']::text[], ARRAY['Arătați apa: „Apă.”','„Udă.” pe scurt.']::text[], 'A auzit apă și udă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z1-resurse', '1-2', 35, 1, 'resurse'::public.pillar, 'Prosopul afară, apoi la loc', 4, 'A'::public.completion_mode, ARRAY['prosop']::text[], ARRAY['Prosopul afară pe scurt, apoi la loc.', '„Prosop. La loc.”']::text[], 'A ajutat cu prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z1-social', '1-2', 35, 1, 'social'::public.pillar, 'Stropi împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă vas unul lângă altul.','„Împreună. Apă.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z2-fizic', '1-2', 35, 2, 'fizic'::public.pillar, 'Turnăm puțin pe pământ', 5, 'A'::public.completion_mode, ARRAY['pahar mic cu puțină apă']::text[], ARRAY['Turnați puțină apă pe pământ sau în vas, cu adult.','„Turnăm. Apă.” pe scurt.']::text[], 'A turnat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z2-mental', '1-2', 35, 2, 'mental'::public.pillar, 'Pahar plin — sau gol?', 3, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Cu apă: „Plin.” pe scurt.','După turnat: „Gol.”']::text[], 'A auzit plin și gol.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z2-resurse', '1-2', 35, 2, 'resurse'::public.pillar, 'Paharul la loc', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Puneți paharul pe masă sau în chiuvetă.','„Pahar. La loc.”']::text[], 'A ajutat să pună paharul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s35-2-3-z2-social', '1-2', 35, 2, 'social'::public.pillar, 'Turnăm pe rând', 5, 'A'::public.completion_mode, ARRAY['pahar cu apă']::text[], ARRAY['Voi turnați puțin.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a turnat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z3-fizic', '1-2', 35, 3, 'fizic'::public.pillar, 'O băltoacă mică', 5, 'A'::public.completion_mode, ARRAY['stropitoare mică sau pahar cu apă']::text[], ARRAY['Turnați puțină apă la rădăcina unei plante afară, cu adult.','„Apă. Plantă.” pe scurt.']::text[], 'A udat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z3-mental', '1-2', 35, 3, 'mental'::public.pillar, 'Adâncă — sau mică?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați planta: „Plantă.”','„Bea. Apă.” pe scurt.']::text[], 'A auzit plantă și apă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z3-resurse', '1-2', 35, 3, 'resurse'::public.pillar, 'Cizmele după băltoacă', 4, 'A'::public.completion_mode, ARRAY['stropitoare mică']::text[], ARRAY['Puneți stropitoarea lângă ușă sau pe raft.','„Stropitoare. La loc.”']::text[], 'A ajutat să pună stropitoarea la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z3-social', '1-2', 35, 3, 'social'::public.pillar, 'Sărim băltoaca', 5, 'A'::public.completion_mode, ARRAY['stropitoare']::text[], ARRAY['Țineți stropitoarea împreună și turnați puțin.','„Împreună. Udăm.” fără forțare.']::text[], 'A ținut stropitoarea sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z4-fizic', '1-2', 35, 4, 'fizic'::public.pillar, 'Udăm o plantă afară', 5, 'A'::public.completion_mode, ARRAY['pahar sau stropitoare cu puțină apă']::text[], ARRAY['Stropiți puțin pământ afară, cu adult.','„Stropim. Pământ.” 10–20 de secunde.']::text[], 'A stropit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z4-mental', '1-2', 35, 4, 'mental'::public.pillar, 'Planta bea apă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați pământul ud: „Ud.”','Arătați uscat dacă e: „Uscat.” pe scurt.']::text[], 'A auzit ud și uscat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s35-2-3-z4-resurse', '1-2', 35, 4, 'resurse'::public.pillar, 'Stropitoarea la loc', 4, 'A'::public.completion_mode, ARRAY['vas','pahar']::text[], ARRAY['Turnați apa rămasă înapoi în vas.','„Apă. Vas.”']::text[], 'A ajutat să toarne apa înapoi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z4-social', '1-2', 35, 4, 'social'::public.pillar, 'Udăm împreună', 5, 'A'::public.completion_mode, ARRAY['stropitoare']::text[], ARRAY['Voi stropiți puțin.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a stropit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z5-fizic', '1-2', 35, 5, 'fizic'::public.pillar, 'Apa e rece afară', 5, 'A'::public.completion_mode, ARRAY['vas cu apă afară']::text[], ARRAY['Puneți mâinile în vas pe scurt, cu adult.','„Mâini. Apă.” 15–20 de secunde.']::text[], 'A pus mâinile în apă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z5-mental', '1-2', 35, 5, 'mental'::public.pillar, 'Apa e rece', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți apa: „Rece.” pe scurt.','„Apă.”']::text[], 'A auzit rece și apă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z5-resurse', '1-2', 35, 5, 'resurse'::public.pillar, 'Mâinile pe prosop', 4, 'A'::public.completion_mode, ARRAY['prosop mic']::text[], ARRAY['Ștergeți mâinile. Puneți prosopul pe cuier.','„Prosop. La loc.”']::text[], 'A ajutat să pună prosopul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z5-social', '1-2', 35, 5, 'social'::public.pillar, 'Atingem apa pe rând', 5, 'A'::public.completion_mode, ARRAY['vas cu apă']::text[], ARRAY['Voi puneți mâinile.','„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a atins apa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z6-fizic', '1-2', 35, 6, 'fizic'::public.pillar, 'O picătură pe frunză', 5, 'A'::public.completion_mode, ARRAY['pahar cu puțină apă', 'frunză']::text[], ARRAY['Lăsați o picătură pe o frunză, cu adult.', '„Picătură. Frunză.” pe scurt.']::text[], 'A lăsat picătura pe frunză sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s35-2-3-z6-mental', '1-2', 35, 6, 'mental'::public.pillar, 'Picătura e mică', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați picătura: „Picătură.”','„Mică.” pe scurt.']::text[], 'A auzit picătură și mică.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z6-resurse', '1-2', 35, 6, 'resurse'::public.pillar, 'Frunza rămâne afară', 4, 'A'::public.completion_mode, ARRAY['frunză afară']::text[], ARRAY['Frunza rămâne afară — nu o aduceți în casă.', '„Frunză. Afară.”']::text[], 'A lăsat frunza afară sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z6-social', '1-2', 35, 6, 'social'::public.pillar, 'Uităm picătura împreună', 5, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Țineți paharul împreună și lăsați o picătură.','„Împreună. Picătură.” fără forțare.']::text[], 'A ținut paharul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z7-fizic', '1-2', 35, 7, 'fizic'::public.pillar, 'Plimbare lângă apă', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.','La final: o privire sau atingere la vasul cu apă dacă vrea.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z7-mental', '1-2', 35, 7, 'mental'::public.pillar, 'Cartea cu apa', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați apă, ploaie sau plantă udată dacă e clar: „Apă.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z7-resurse', '1-2', 35, 7, 'resurse'::public.pillar, 'Paharul și prosopul la loc', 4, 'A'::public.completion_mode, ARRAY['pahar', 'prosop']::text[], ARRAY['Puneți paharul și prosopul la loc.', '„La loc. Gata.”']::text[], 'A ajutat cu paharul sau prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)'),
('s35-2-3-z7-social', '1-2', 35, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Apă afară (joc scurt)')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s36-2-3-z1-fizic', '1-2', 36, 1, 'fizic'::public.pillar, 'Ieșim și privim', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ieșiți în curte pe scurt, cu adult. Stați liniștiți.','„Privim. Afară.” 15–20 de secunde.']::text[], 'A ieșit și a privit pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z1-mental', '1-2', 36, 1, 'mental'::public.pillar, 'E mic, gândăcelul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă vedeți una: „Insectă.” pe scurt.','„Mică.” fără grabă.']::text[], 'A auzit insectă și mică.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z1-resurse', '1-2', 36, 1, 'resurse'::public.pillar, 'Rămânem pe loc, departe', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă după curte.','„Pantofi. La loc.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z1-social', '1-2', 36, 1, 'social'::public.pillar, 'Privim împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul. Priviți de departe.','„Împreună. De departe.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z2-fizic', '1-2', 36, 2, 'fizic'::public.pillar, 'Arătăm gândăcelul', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați cu degetul spre o insectă sau floare, fără a atinge.','„Uite. Departe.” pe scurt.']::text[], 'A arătat cu degetul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z2-mental', '1-2', 36, 2, 'mental'::public.pillar, 'Pe frunză', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați pe frunză: „Pe frunză.”', 'Privire scurtă, fără atingere dacă e insectă.']::text[], 'A auzit pe frunză.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z2-resurse', '1-2', 36, 2, 'resurse'::public.pillar, 'Mâna jos, nu-l luăm', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Țineți mâinile pe lângă corp. Fără a prinde.','„Mâini. Privim.” pe scurt.']::text[], 'A ținut mâinile pe scurt sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s36-2-3-z2-social', '1-2', 36, 2, 'social'::public.pillar, 'Arătăm pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Uite.”','Adultul privește de departe pe scurt, fără forțare.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z3-fizic', '1-2', 36, 3, 'fizic'::public.pillar, 'Gândăcelul merge', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Urmăriți cu ochii o insectă pe frunză sau pe pământ, de departe.','„Ochii. Insectă.” 10–20 de secunde.']::text[], 'A urmărit cu ochii sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z3-mental', '1-2', 36, 3, 'mental'::public.pillar, 'Merge încet', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă se mișcă: „Merge.” pe scurt.','„Insectă.”']::text[], 'A auzit merge și insectă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z3-resurse', '1-2', 36, 3, 'resurse'::public.pillar, 'Nu-l atingem', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți 1 obiect la loc ca să fie loc pe potecă.','„La loc. Liber.”']::text[], 'A ajutat să elibereze poteca.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z3-social', '1-2', 36, 3, 'social'::public.pillar, 'Îl urmărim din ochi', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă adult și urmăriți pe scurt.','„Împreună. Privim.” fără forțare.']::text[], 'A privit lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z4-fizic', '1-2', 36, 4, 'fizic'::public.pillar, 'Unul zboară', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați afară liniștiți 15–20 de secunde.','„Urechi. Zumzet.” dacă se aude.']::text[], 'A ascultat pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z4-mental', '1-2', 36, 4, 'mental'::public.pillar, 'Zumzet și liniște', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Zumzet.” pe scurt dacă e.','Apoi: „Liniște.” câteva secunde.']::text[], 'A auzit zumzet sau liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s36-2-3-z4-resurse', '1-2', 36, 4, 'resurse'::public.pillar, 'Rămânem pe iarbă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Intrați. Închideți ușa pe scurt.','„Ușă. Gata.”']::text[], 'A ajutat la ușă sau a intrat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z4-social', '1-2', 36, 4, 'social'::public.pillar, 'Privim zborul împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul afară pe scurt.','„Împreună. Ascultăm.” fără grabă.']::text[], 'A ascultat lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z5-fizic', '1-2', 36, 5, 'fizic'::public.pillar, 'Doar ne uităm, de departe', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă apare: priviți de departe, fără a alerga după ea.','„Fluture.” sau „Albină.” 10–20 de secunde.']::text[], 'A privit de departe sau a așteptat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z5-mental', '1-2', 36, 5, 'mental'::public.pillar, 'Avem grijă, nu atingem', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Zboară.” pe scurt.','„Sus.” dacă e cazul.']::text[], 'A auzit zboară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z5-resurse', '1-2', 36, 5, 'resurse'::public.pillar, 'Ne dăm un pas înapoi', 4, 'A'::public.completion_mode, ARRAY['binoclu de jucărie']::text[], ARRAY['Dacă ați privit prin el, puneți-l pe raft.','„La loc.” pe scurt.']::text[], 'A ajutat să pună binoclul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z5-social', '1-2', 36, 5, 'social'::public.pillar, 'Privim de departe împreună', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul. Priviți de departe.','„Împreună. De departe.” fără forțare.']::text[], 'A privit lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z6-fizic', '1-2', 36, 6, 'fizic'::public.pillar, 'Uite, pe pământ', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți câțiva pași moi pe potecă, fără a călca pe insectă.','„Pași moi.” pe scurt, cu adult.']::text[], 'A făcut pași moi sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s36-2-3-z6-mental', '1-2', 36, 6, 'mental'::public.pillar, 'Pământ — sau frunză?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați pământul: „Pământ.”', 'Arătați o frunză: „Frunză.” pe scurt.']::text[], 'A auzit pământ și frunză.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z6-resurse', '1-2', 36, 6, 'resurse'::public.pillar, 'Pământul rămâne, noi plecăm', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Lăsați poteca liberă. Puneți un obiect la loc dacă e.','„Potecă. Liber.”']::text[], 'A lăsat poteca liberă sau a ajutat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z6-social', '1-2', 36, 6, 'social'::public.pillar, 'Arătăm pământul', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți câțiva pași moi lângă adult.','„Împreună. Pași moi.” fără forțare.']::text[], 'A mers lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z7-fizic', '1-2', 36, 7, 'fizic'::public.pillar, 'Plimbare, ochii pe jos', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.','La final: 10 secunde de privit de departe dacă vrea.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z7-mental', '1-2', 36, 7, 'mental'::public.pillar, 'Cartea cu gândăcei', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.','Arătați o insectă dacă e clar: „Insectă.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z7-resurse', '1-2', 36, 7, 'resurse'::public.pillar, 'Cartea pe raft', 4, 'A'::public.completion_mode, ARRAY['carte','binoclu de jucărie']::text[], ARRAY['Puneți cartea pe raft, binoclul la loc.','„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe'),
('s36-2-3-z7-social', '1-2', 36, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”','Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Insecte de departe')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
