insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s37-2-3-z1-fizic', '1-2', 37, 1, 'fizic'::public.pillar, 'Intrăm în umbră pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară: treceți din soare în umbră pe scurt, cu adult.', '„Umbră. Răcoare.” 15–20 de secunde.']::text[], 'A intrat în umbră sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z1-mental', '1-2', 37, 1, 'mental'::public.pillar, 'Umbră: răcoare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați locul umbrit: „Umbră.”', '„Răcoare.” pe scurt.']::text[], 'A auzit umbră și răcoare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z1-resurse', '1-2', 37, 1, 'resurse'::public.pillar, 'Paharul cu apă la umbră', 4, 'A'::public.completion_mode, ARRAY['pahar cu puțină apă']::text[], ARRAY['Așezați paharul la umbră, pe treaptă sau masă.', '„Apă. Umbră.”']::text[], 'A ajutat să așeze paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z1-social', '1-2', 37, 1, 'social'::public.pillar, 'Stăm la umbră împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul la umbră.', '„Împreună. Răcoare.” fără grabă.']::text[], 'A stat pe scurt lângă adult la umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z2-fizic', '1-2', 37, 2, 'fizic'::public.pillar, 'Așezăm pe scaun la umbră', 5, 'A'::public.completion_mode, ARRAY['scaun mic sau bancă']::text[], ARRAY['Așezați-vă pe scaun la umbră pe scurt, cu adult.', '„Jos. Umbră.” 15–20 de secunde.']::text[], 'S-a așezat sau a privit scaunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z2-mental', '1-2', 37, 2, 'mental'::public.pillar, 'Soare și umbră', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați soarele: „Soare. Cald.”', 'Arătați umbra: „Umbră. Răcoare.” pe scurt.']::text[], 'A auzit soare și umbră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z2-resurse', '1-2', 37, 2, 'resurse'::public.pillar, 'Pălăria pe scaun la umbră', 4, 'A'::public.completion_mode, ARRAY['pălărie sau șapcă']::text[], ARRAY['Puneți pălăria pe scaun la umbră.', '„Pălărie. Aici.”']::text[], 'A ajutat să pună pălăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s37-2-3-z2-social', '1-2', 37, 2, 'social'::public.pillar, 'Pauză scurtă cu adultul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați așezați la umbră unul lângă altul.', '„Pauză. Împreună.” fără forțare.']::text[], 'A făcut pauză pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z3-fizic', '1-2', 37, 3, 'fizic'::public.pillar, 'Bem apă la umbră', 5, 'A'::public.completion_mode, ARRAY['pahar cu puțină apă']::text[], ARRAY['La umbră: oferiți puțină apă, cu adult.', '„Apă. Răcoare.” pe scurt.']::text[], 'A băut sau a atins paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z3-mental', '1-2', 37, 3, 'mental'::public.pillar, 'Apă: rece', 3, 'A'::public.completion_mode, ARRAY['pahar cu apă']::text[], ARRAY['Arătați paharul: „Apă.”', '„Rece.” pe scurt, dacă e.']::text[], 'A auzit apă și rece.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z3-resurse', '1-2', 37, 3, 'resurse'::public.pillar, 'Paharul gol pe masă', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['După băut: puneți paharul pe masă la umbră.', '„Pahar. La loc.”']::text[], 'A ajutat să pună paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z3-social', '1-2', 37, 3, 'social'::public.pillar, 'Bem pe rând la umbră', 4, 'A'::public.completion_mode, ARRAY['pahar cu apă']::text[], ARRAY['Voi beți puțin. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a băut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z4-fizic', '1-2', 37, 4, 'fizic'::public.pillar, 'Din soare în umbră, doi pași', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți doi–trei pași din soare în umbră, cu adult.', '„Soare. Umbră.” pe scurt.']::text[], 'A făcut pași spre umbră sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z4-mental', '1-2', 37, 4, 'mental'::public.pillar, 'Cald și răcoare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['În soare: „Cald.” pe scurt.', 'În umbră: „Răcoare.”']::text[], 'A auzit cald și răcoare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s37-2-3-z4-resurse', '1-2', 37, 4, 'resurse'::public.pillar, 'Pantofii la umbră lângă ușă', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii la umbră, lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z4-social', '1-2', 37, 4, 'social'::public.pillar, 'Mergem în umbră cu adultul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți împreună câțiva pași spre umbră.', '„Împreună. Umbră.” fără forțare.']::text[], 'A mers pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z5-fizic', '1-2', 37, 5, 'fizic'::public.pillar, 'Aer pe față la umbră', 5, 'A'::public.completion_mode, ARRAY['evantai mic sau foaie']::text[], ARRAY['La umbră: faceți puțin aer pe față cu evantaiul, cu adult.', '„Aer. Răcoare.” 10–20 de secunde.']::text[], 'A simțit aerul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z5-mental', '1-2', 37, 5, 'mental'::public.pillar, 'Aer: blând', 3, 'A'::public.completion_mode, ARRAY['evantai mic']::text[], ARRAY['Arătați evantaiul: „Aer.”', '„Blând.” pe scurt.']::text[], 'A auzit aer și blând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z5-resurse', '1-2', 37, 5, 'resurse'::public.pillar, 'Evantaiul pe masă după', 4, 'A'::public.completion_mode, ARRAY['evantai mic']::text[], ARRAY['Puneți evantaiul pe masă sau pe raft.', '„Evantai. La loc.”']::text[], 'A ajutat să pună evantaiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z5-social', '1-2', 37, 5, 'social'::public.pillar, 'Facem aer pe rând', 4, 'A'::public.completion_mode, ARRAY['evantai mic']::text[], ARRAY['Voi faceți puțin aer. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a încercat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z6-fizic', '1-2', 37, 6, 'fizic'::public.pillar, 'Odihnă scurtă pe pătură la umbră', 6, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Așezați pătura la umbră; stați pe ea pe scurt, cu adult.', '„Pătură. Răcoare.” 20–30 de secunde.']::text[], 'S-a așezat pe pătură sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s37-2-3-z6-mental', '1-2', 37, 6, 'mental'::public.pillar, 'Loc răcoros: aici', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați locul: „Aici.”', '„Loc răcoros.” pe scurt.']::text[], 'A auzit loc răcoros.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z6-resurse', '1-2', 37, 6, 'resurse'::public.pillar, 'Pătura rulată la loc', 4, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Rulați pătura și puneți-o pe raft sau în coș.', '„Pătură. La loc.”']::text[], 'A ajutat să pună pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z6-social', '1-2', 37, 6, 'social'::public.pillar, 'Pe pătură unul lângă altul', 4, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Stați pe pătură unul lângă altul la umbră.', '„Împreună. Pauză.” fără grabă.']::text[], 'A stat pe scurt pe pătură cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z7-fizic', '1-2', 37, 7, 'fizic'::public.pillar, 'Plimbare liberă, umbră la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.', 'La final: o pauză scurtă la umbră dacă vrea.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z7-mental', '1-2', 37, 7, 'mental'::public.pillar, 'Carte: umbră și răcoare', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați umbră, copac sau apă dacă e clar: „Umbră.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z7-resurse', '1-2', 37, 7, 'resurse'::public.pillar, 'Paharul și pălăria la loc', 4, 'A'::public.completion_mode, ARRAY['pahar', 'pălărie']::text[], ARRAY['Puneți paharul pe masă, pălăria pe cuier.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros'),
('s37-2-3-z7-social', '1-2', 37, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Umbră și loc răcoros')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s38-2-3-z1-fizic', '1-2', 38, 1, 'fizic'::public.pillar, 'Piciorul pe iarbă pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară: puneți piciorul pe iarbă pe scurt, cu adult.', '„Iarbă. Picior.” 10–20 de secunde.']::text[], 'A atins iarba cu piciorul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z1-mental', '1-2', 38, 1, 'mental'::public.pillar, 'Iarbă: verde', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Iarbă.”', '„Verde.” pe scurt.']::text[], 'A auzit iarbă și verde.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z1-resurse', '1-2', 38, 1, 'resurse'::public.pillar, 'Pantofii lângă iarbă', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă iarbă, pe piatră sau treaptă.', '„Pantofi. Aici.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z1-social', '1-2', 38, 1, 'social'::public.pillar, 'Privim iarba împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă iarbă unul lângă altul.', '„Împreună. Iarbă.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z2-fizic', '1-2', 38, 2, 'fizic'::public.pillar, 'Desculț pe iarbă, dacă e potrivit', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă iarba e uscată și potrivită: un picior desculț pe scurt, cu adult.', '„Desculț. Iarbă.” 10–20 de secunde.']::text[], 'A atins iarba desculț sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z2-mental', '1-2', 38, 2, 'mental'::public.pillar, 'Moale: iarba', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Iarbă.”', '„Moale.” pe scurt.']::text[], 'A auzit iarbă și moale.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z2-resurse', '1-2', 38, 2, 'resurse'::public.pillar, 'Șosetele în pantofi', 4, 'A'::public.completion_mode, ARRAY['șosete', 'pantofi']::text[], ARRAY['După: puneți șosetele în pantofi sau pe treaptă.', '„Șosete. La loc.”']::text[], 'A ajutat să pună șosetele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s38-2-3-z2-social', '1-2', 38, 2, 'social'::public.pillar, 'Desculți pe rând pe iarbă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi puneți piciorul. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a încercat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z3-fizic', '1-2', 38, 3, 'fizic'::public.pillar, 'Degetele de la picioare pe iarbă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mișcați degetele de la picioare pe iarbă pe scurt, cu adult.', '„Degete. Iarbă.” 15–20 de secunde.']::text[], 'A mișcat degetele pe iarbă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z3-mental', '1-2', 38, 3, 'mental'::public.pillar, 'Gâdilă: iarba', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba la picior: „Iarbă.”', '„Gâdilă.” pe scurt, dacă simte.']::text[], 'A auzit iarbă și gâdilă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z3-resurse', '1-2', 38, 3, 'resurse'::public.pillar, 'Prosopul mic lângă pantofi', 4, 'A'::public.completion_mode, ARRAY['prosop mic']::text[], ARRAY['Așezați prosopul lângă pantofi pentru picioare.', '„Prosop. Aici.”']::text[], 'A ajutat să așeze prosopul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z3-social', '1-2', 38, 3, 'social'::public.pillar, 'Arătăm iarba adultului', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Uite.”', 'Adultul privește pe scurt, fără forțare.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z4-fizic', '1-2', 38, 4, 'fizic'::public.pillar, 'Pași scurți pe iarbă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți câțiva pași pe iarbă, cu adult.', '„Pași. Iarbă.” pe scurt.']::text[], 'A făcut pași pe iarbă sau lângă ea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z4-mental', '1-2', 38, 4, 'mental'::public.pillar, 'Iarbă și drum', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați iarba: „Iarbă.”', 'Arătați drumul sau piatra: „Drum.” pe scurt.']::text[], 'A auzit iarbă și drum.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s38-2-3-z4-resurse', '1-2', 38, 4, 'resurse'::public.pillar, 'Ușa închisă după iarbă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Intrați. Închideți ușa pe scurt.', '„Ușă. Gata.”']::text[], 'A ajutat la ușă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z4-social', '1-2', 38, 4, 'social'::public.pillar, 'Pași pe iarbă cu adultul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți câțiva pași pe iarbă unul lângă altul.', '„Împreună. Pași.” fără forțare.']::text[], 'A mers pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z5-fizic', '1-2', 38, 5, 'fizic'::public.pillar, 'Ne așezăm pe iarbă pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Așezați-vă pe iarbă pe scurt, cu adult.', '„Jos. Iarbă.” 15–20 de secunde.']::text[], 'S-a așezat pe iarbă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z5-mental', '1-2', 38, 5, 'mental'::public.pillar, 'Jos pe iarbă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați: „Jos.”', '„Iarbă.” pe scurt.']::text[], 'A auzit jos și iarbă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z5-resurse', '1-2', 38, 5, 'resurse'::public.pillar, 'Pătura pe iarbă, apoi la loc', 4, 'A'::public.completion_mode, ARRAY['pătură mică']::text[], ARRAY['Așezați pătura pe iarbă; după: rulați-o.', '„Pătură. La loc.”']::text[], 'A ajutat cu pătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z5-social', '1-2', 38, 5, 'social'::public.pillar, 'Pe iarbă unul lângă altul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe iarbă unul lângă altul.', '„Împreună. Iarbă.” fără grabă.']::text[], 'A stat pe scurt pe iarbă cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z6-fizic', '1-2', 38, 6, 'fizic'::public.pillar, 'Picior pe iarbă, picior pe piatră', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Un picior pe iarbă, unul pe piatră sau drum, cu adult.', '„Iarbă. Piatră.” pe scurt.']::text[], 'A simțit ambele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s38-2-3-z6-mental', '1-2', 38, 6, 'mental'::public.pillar, 'Moale și tare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Pe iarbă: „Moale.” pe scurt.', 'Pe piatră: „Tare.”']::text[], 'A auzit moale și tare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z6-resurse', '1-2', 38, 6, 'resurse'::public.pillar, 'Pantofii pe raft după iarbă', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['După curte: pantofii pe raft sau lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z6-social', '1-2', 38, 6, 'social'::public.pillar, 'Simțim pe rând: iarbă și piatră', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi puneți piciorul. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a încercat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z7-fizic', '1-2', 38, 7, 'fizic'::public.pillar, 'Plimbare liberă, iarbă la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.', 'La final: o atingere cu piciorul pe iarbă dacă vrea.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z7-mental', '1-2', 38, 7, 'mental'::public.pillar, 'Carte: iarbă și picioare', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați iarbă sau picioare dacă e clar: „Iarbă.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z7-resurse', '1-2', 38, 7, 'resurse'::public.pillar, 'Pantofii și prosopul la loc', 4, 'A'::public.completion_mode, ARRAY['pantofi', 'prosop mic']::text[], ARRAY['Puneți pantofii lângă ușă, prosopul la loc.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă'),
('s38-2-3-z7-social', '1-2', 38, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Piciorul pe iarbă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s39-2-3-z1-fizic', '1-2', 39, 1, 'fizic'::public.pillar, 'Ținem un fruct pe scurt', 5, 'A'::public.completion_mode, ARRAY['un fruct spălat (măr sau roșie)']::text[], ARRAY['Oferiți fructul în mână pe scurt, cu adult.', '„Fruct.” 10–20 de secunde.']::text[], 'A ținut fructul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z1-mental', '1-2', 39, 1, 'mental'::public.pillar, 'Fruct: rotund', 3, 'A'::public.completion_mode, ARRAY['un fruct']::text[], ARRAY['Arătați fructul: „Fruct.”', '„Rotund.” pe scurt, dacă e.']::text[], 'A auzit fruct și rotund.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z1-resurse', '1-2', 39, 1, 'resurse'::public.pillar, 'Fructul în bol pe masă', 4, 'A'::public.completion_mode, ARRAY['bol', 'fruct']::text[], ARRAY['Puneți fructul în bol pe masă.', '„Bol. Fruct.”']::text[], 'A ajutat să pună fructul în bol.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z1-social', '1-2', 39, 1, 'social'::public.pillar, 'Privim fructul împreună', 4, 'A'::public.completion_mode, ARRAY['un fruct']::text[], ARRAY['Stați lângă bol unul lângă altul.', '„Împreună. Fruct.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z2-fizic', '1-2', 39, 2, 'fizic'::public.pillar, 'Arătăm fructul cu degetul', 4, 'A'::public.completion_mode, ARRAY['fruct în bol sau pe masă']::text[], ARRAY['Arătați fructul cu degetul pe scurt.', '„Uite. Fruct.” 10–15 de secunde.']::text[], 'A arătat sau a privit fructul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z2-mental', '1-2', 39, 2, 'mental'::public.pillar, 'Nume: măr sau roșie', 3, 'A'::public.completion_mode, ARRAY['un fruct cunoscut']::text[], ARRAY['Arătați fructul: spuneți numele clar, pe scurt.', '„Măr.” sau „Roșie.” după ce e.']::text[], 'A auzit numele fructului.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z2-resurse', '1-2', 39, 2, 'resurse'::public.pillar, 'Bolul pe masă, la locul lui', 4, 'A'::public.completion_mode, ARRAY['bol']::text[], ARRAY['Așezați bolul pe masă la locul lui.', '„Bol. Aici.”']::text[], 'A ajutat să așeze bolul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s39-2-3-z2-social', '1-2', 39, 2, 'social'::public.pillar, 'Arătăm fructul adultului', 4, 'A'::public.completion_mode, ARRAY['un fruct']::text[], ARRAY['Arătați fructul: „Uite.”', 'Adultul privește pe scurt, fără forțare.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z3-fizic', '1-2', 39, 3, 'fizic'::public.pillar, 'Mirosim fructul pe scurt', 5, 'A'::public.completion_mode, ARRAY['fruct spălat']::text[], ARRAY['Apropiați fructul de nas pe scurt, cu adult.', '„Miros. Fruct.” 10–15 de secunde.']::text[], 'A mirosit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z3-mental', '1-2', 39, 3, 'mental'::public.pillar, 'Miros dulce', 3, 'A'::public.completion_mode, ARRAY['fruct']::text[], ARRAY['Arătați fructul: „Miros.”', '„Dulce.” pe scurt, dacă e.']::text[], 'A auzit miros și dulce.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z3-resurse', '1-2', 39, 3, 'resurse'::public.pillar, 'Fructul înapoi în bol', 4, 'A'::public.completion_mode, ARRAY['bol', 'fruct']::text[], ARRAY['După miros: fructul înapoi în bol.', '„Fruct. La loc.”']::text[], 'A ajutat să pună fructul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z3-social', '1-2', 39, 3, 'social'::public.pillar, 'Mirosim pe rând', 4, 'A'::public.completion_mode, ARRAY['fruct']::text[], ARRAY['Voi mirosiți. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a mirosit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z4-fizic', '1-2', 39, 4, 'fizic'::public.pillar, 'Atingem coaja fructului', 5, 'A'::public.completion_mode, ARRAY['fruct spălat']::text[], ARRAY['Treceți degetul pe coajă pe scurt, cu adult.', '„Coajă. Fruct.” 10–20 de secunde.']::text[], 'A atins coaja sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z4-mental', '1-2', 39, 4, 'mental'::public.pillar, 'Netedă: coaja', 3, 'A'::public.completion_mode, ARRAY['fruct']::text[], ARRAY['Arătați coaja: „Coajă.”', '„Netedă.” pe scurt, dacă e.']::text[], 'A auzit coajă și netedă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s39-2-3-z4-resurse', '1-2', 39, 4, 'resurse'::public.pillar, 'Șervețelul lângă bol', 4, 'A'::public.completion_mode, ARRAY['șervețel', 'bol']::text[], ARRAY['Puneți șervețelul lângă bol pe masă.', '„Șervețel. Aici.”']::text[], 'A ajutat să pună șervețelul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z4-social', '1-2', 39, 4, 'social'::public.pillar, 'Atingem fructul împreună', 4, 'A'::public.completion_mode, ARRAY['fruct']::text[], ARRAY['Țineți fructul împreună pe scurt.', '„Împreună. Fruct.” fără forțare.']::text[], 'A atins fructul cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z5-fizic', '1-2', 39, 5, 'fizic'::public.pillar, 'Gust mic de fruct', 5, 'A'::public.completion_mode, ARRAY['bucățică mică de fruct spălat']::text[], ARRAY['Oferiți o bucățică mică, cu adult; fără forțare.', '„Gust. Fruct.” pe scurt.']::text[], 'A gustat sau a refuzat blând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z5-mental', '1-2', 39, 5, 'mental'::public.pillar, 'Dulce: gustul', 3, 'A'::public.completion_mode, ARRAY['bucățică de fruct']::text[], ARRAY['Arătați bucățica: „Gust.”', '„Dulce.” pe scurt, dacă e.']::text[], 'A auzit gust și dulce.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z5-resurse', '1-2', 39, 5, 'resurse'::public.pillar, 'Farfuria mică la chiuvetă', 4, 'A'::public.completion_mode, ARRAY['farfurie mică']::text[], ARRAY['După gust: farfuria la chiuvetă sau pe masă.', '„Farfurie. La loc.”']::text[], 'A ajutat cu farfuria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z5-social', '1-2', 39, 5, 'social'::public.pillar, 'Gustăm pe rând', 4, 'A'::public.completion_mode, ARRAY['bucățică de fruct']::text[], ARRAY['Voi gustați. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a gustat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z6-fizic', '1-2', 39, 6, 'fizic'::public.pillar, 'Spălăm fructul pe scurt', 5, 'A'::public.completion_mode, ARRAY['fruct', 'apă la chiuvetă']::text[], ARRAY['Țineți fructul sub puțină apă, cu adult.', '„Spălăm. Fruct.” 15–20 de secunde.']::text[], 'A atins apa sau fructul la spălat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s39-2-3-z6-mental', '1-2', 39, 6, 'mental'::public.pillar, 'Ud: fructul spălat', 3, 'A'::public.completion_mode, ARRAY['fruct']::text[], ARRAY['Arătați fructul ud: „Ud.”', '„Curat.” pe scurt.']::text[], 'A auzit ud și curat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z6-resurse', '1-2', 39, 6, 'resurse'::public.pillar, 'Fructul pe prosopul de bucătărie', 4, 'A'::public.completion_mode, ARRAY['prosop de bucătărie', 'fruct']::text[], ARRAY['Puneți fructul pe prosop să se usuce puțin.', '„Fruct. Prosop.”']::text[], 'A ajutat să pună fructul pe prosop.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z6-social', '1-2', 39, 6, 'social'::public.pillar, 'Spălăm împreună', 4, 'A'::public.completion_mode, ARRAY['fruct', 'apă']::text[], ARRAY['Țineți fructul împreună sub apă pe scurt.', '„Împreună. Spălăm.” fără forțare.']::text[], 'A spălat pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z7-fizic', '1-2', 39, 7, 'fizic'::public.pillar, 'Plimbare liberă, fruct la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția în casă sau curte pe scurt, cu adult.', 'La final: o privire la bolul cu fruct dacă vrea.']::text[], 'A mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z7-mental', '1-2', 39, 7, 'mental'::public.pillar, 'Carte: fructe', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați un fruct dacă e clar: „Fruct.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z7-resurse', '1-2', 39, 7, 'resurse'::public.pillar, 'Bolul și farfuria la loc', 4, 'A'::public.completion_mode, ARRAY['bol', 'farfurie mică']::text[], ARRAY['Puneți bolul și farfuria la loc pe masă sau în dulap.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem'),
('s39-2-3-z7-social', '1-2', 39, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Fructe pe care le vedem')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s40-2-3-z1-fizic', '1-2', 40, 1, 'fizic'::public.pillar, 'Cărăm un obiect doi pași', 5, 'A'::public.completion_mode, ARRAY['obiect ușor (prosop sau jucărie)']::text[], ARRAY['Cărați obiectul doi–trei pași, cu adult.', '„Cărăm. Pași.” pe scurt.']::text[], 'A cărat sau a ținut obiectul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z1-mental', '1-2', 40, 1, 'mental'::public.pillar, 'Ajutor: da', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați obiectul: „Ajutor.”', '„Da.” pe scurt, dacă vrea să ajute.']::text[], 'A auzit ajutor.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z1-resurse', '1-2', 40, 1, 'resurse'::public.pillar, 'Obiectul pe masă după cărat', 4, 'A'::public.completion_mode, ARRAY['obiect ușor']::text[], ARRAY['Puneți obiectul pe masă sau pe raft.', '„Aici. La loc.”']::text[], 'A ajutat să pună obiectul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z1-social', '1-2', 40, 1, 'social'::public.pillar, 'Cărăm împreună', 4, 'A'::public.completion_mode, ARRAY['obiect ușor']::text[], ARRAY['Țineți obiectul împreună câțiva pași.', '„Împreună. Cărăm.” fără forțare.']::text[], 'A cărat pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z2-fizic', '1-2', 40, 2, 'fizic'::public.pillar, 'Punem două lucruri la loc', 5, 'A'::public.completion_mode, ARRAY['2 obiecte mici']::text[], ARRAY['Puneți două obiecte pe raft sau în coș, cu adult.', '„La loc.” pe scurt.']::text[], 'A pus cel puțin un obiect la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z2-mental', '1-2', 40, 2, 'mental'::public.pillar, 'Unu și doi: la loc', 3, 'A'::public.completion_mode, ARRAY['2 obiecte']::text[], ARRAY['Arătați: „Unu.” puneți.', '„Doi.” puneți pe scurt.']::text[], 'A auzit unu și doi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z2-resurse', '1-2', 40, 2, 'resurse'::public.pillar, 'Coșul pe raft după treabă', 4, 'A'::public.completion_mode, ARRAY['coș mic']::text[], ARRAY['Puneți coșul pe raft sau lângă ușă.', '„Coș. La loc.”']::text[], 'A ajutat să pună coșul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s40-2-3-z2-social', '1-2', 40, 2, 'social'::public.pillar, 'Punem pe rând la loc', 4, 'A'::public.completion_mode, ARRAY['2 obiecte']::text[], ARRAY['Voi puneți unul. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a pus.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z3-fizic', '1-2', 40, 3, 'fizic'::public.pillar, 'Ștergem masa pe scurt', 5, 'A'::public.completion_mode, ARRAY['cârpă umedă']::text[], ARRAY['Ștergeți masa cu cârpa pe scurt, cu adult.', '„Ștergem. Masă.” 15–20 de secunde.']::text[], 'A șters sau a ținut cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z3-mental', '1-2', 40, 3, 'mental'::public.pillar, 'Curat: masa', 3, 'A'::public.completion_mode, ARRAY['cârpă']::text[], ARRAY['Arătați masa: „Masă.”', '„Curat.” pe scurt.']::text[], 'A auzit masă și curat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z3-resurse', '1-2', 40, 3, 'resurse'::public.pillar, 'Cârpa la chiuvetă', 4, 'A'::public.completion_mode, ARRAY['cârpă']::text[], ARRAY['Puneți cârpa la chiuvetă sau pe cârlig.', '„Cârpă. La loc.”']::text[], 'A ajutat să pună cârpa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z3-social', '1-2', 40, 3, 'social'::public.pillar, 'Ștergem pe rând', 4, 'A'::public.completion_mode, ARRAY['cârpă']::text[], ARRAY['Voi ștergeți. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a șters.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z4-fizic', '1-2', 40, 4, 'fizic'::public.pillar, 'Aducem șervețelul', 5, 'A'::public.completion_mode, ARRAY['șervețel']::text[], ARRAY['Luați șervețelul și aduceți-l pe masă, cu adult.', '„Șervețel. Masă.” pe scurt.']::text[], 'A adus șervețelul sau a ținut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z4-mental', '1-2', 40, 4, 'mental'::public.pillar, 'Unde e șervețelul', 3, 'A'::public.completion_mode, ARRAY['șervețel']::text[], ARRAY['Întrebați: „Unde e?” pe scurt.', 'Arătați: „Aici. Șervețel.”']::text[], 'A auzit unde și aici.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s40-2-3-z4-resurse', '1-2', 40, 4, 'resurse'::public.pillar, 'Șervețelul în suport', 4, 'A'::public.completion_mode, ARRAY['șervețel', 'suport sau cutie']::text[], ARRAY['Puneți șervețelul în suport sau cutie.', '„Șervețel. La loc.”']::text[], 'A ajutat să pună șervețelul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z4-social', '1-2', 40, 4, 'social'::public.pillar, 'Dăm șervețelul adultului', 4, 'A'::public.completion_mode, ARRAY['șervețel']::text[], ARRAY['Oferiți șervețelul: „Ține.” pe scurt.', 'Fără forțare.']::text[], 'A dat sau a oferit șervețelul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z5-fizic', '1-2', 40, 5, 'fizic'::public.pillar, 'Așezăm lingura pe masă', 5, 'A'::public.completion_mode, ARRAY['lingură']::text[], ARRAY['Așezați lingura pe masă lângă farfurie, cu adult.', '„Lingură. Masă.” pe scurt.']::text[], 'A așezat lingura sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z5-mental', '1-2', 40, 5, 'mental'::public.pillar, 'Lingură lângă farfurie', 3, 'A'::public.completion_mode, ARRAY['lingură', 'farfurie']::text[], ARRAY['Arătați: „Lingură.”', '„Lângă farfurie.” pe scurt.']::text[], 'A auzit lingură și farfurie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z5-resurse', '1-2', 40, 5, 'resurse'::public.pillar, 'Lingura în sertar după', 4, 'A'::public.completion_mode, ARRAY['lingură']::text[], ARRAY['După: lingura în sertar sau pe suport.', '„Lingură. La loc.”']::text[], 'A ajutat să pună lingura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z5-social', '1-2', 40, 5, 'social'::public.pillar, 'Pregătim masa pe rând', 4, 'A'::public.completion_mode, ARRAY['lingură', 'farfurie']::text[], ARRAY['Voi așezați. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A văzut rândul sau a așezat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z6-fizic', '1-2', 40, 6, 'fizic'::public.pillar, 'Sortăm trei lucruri pe scurt', 5, 'A'::public.completion_mode, ARRAY['3 obiecte mici', 'coș sau raft']::text[], ARRAY['Puneți trei obiecte în coș sau pe raft, cu adult.', '„Trei. La loc.” pe scurt.']::text[], 'A mutat cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s40-2-3-z6-mental', '1-2', 40, 6, 'mental'::public.pillar, 'Trei: la loc', 3, 'A'::public.completion_mode, ARRAY['3 obiecte']::text[], ARRAY['Numărați pe scurt: „Unu. Doi. Trei.”', '„La loc.”']::text[], 'A auzit trei și la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z6-resurse', '1-2', 40, 6, 'resurse'::public.pillar, 'Coșul plin pe raft', 4, 'A'::public.completion_mode, ARRAY['coș mic']::text[], ARRAY['Puneți coșul pe raft după sortat.', '„Coș. Gata.”']::text[], 'A ajutat să pună coșul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z6-social', '1-2', 40, 6, 'social'::public.pillar, 'Sortăm împreună', 4, 'A'::public.completion_mode, ARRAY['3 obiecte']::text[], ARRAY['Puneți obiectele împreună pe scurt.', '„Împreună. La loc.” fără forțare.']::text[], 'A sortat pe scurt cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z7-fizic', '1-2', 40, 7, 'fizic'::public.pillar, 'Plimbare liberă, treabă scurtă la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția în casă pe scurt, cu adult.', 'La final: un obiect la loc dacă vrea.']::text[], 'A mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z7-mental', '1-2', 40, 7, 'mental'::public.pillar, 'Carte: ajutor acasă', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați casă, masă sau coș dacă e clar: „Ajutor.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z7-resurse', '1-2', 40, 7, 'resurse'::public.pillar, 'Trei lucruri la loc, gata', 4, 'A'::public.completion_mode, ARRAY['2–3 obiecte']::text[], ARRAY['Puneți 2–3 obiecte pe raft sau în coș.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă'),
('s40-2-3-z7-social', '1-2', 40, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Ajutor la treabă scurtă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
