insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s41-2-3-z1-fizic', '1-2', 41, 1, 'fizic'::public.pillar, 'Pași spre poartă pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară: mergeți câțiva pași spre poartă sau gard, cu adult.', '„Drum. Poartă.” 15–20 de secunde.']::text[], 'A făcut câțiva pași spre poartă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z1-mental', '1-2', 41, 1, 'mental'::public.pillar, 'Drum: acolo', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați drumul înainte: „Drum.”', '„Acolo.” pe scurt.']::text[], 'A auzit drum și acolo.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z1-resurse', '1-2', 41, 1, 'resurse'::public.pillar, 'Pantofii lângă ușă înainte', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă înainte de ieșire.', '„Pantofi. Ușă.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z1-social', '1-2', 41, 1, 'social'::public.pillar, 'Mergem pe drum împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți unul lângă altul pe drumul scurt.', '„Împreună. Drum.” fără grabă.']::text[], 'A mers pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z2-fizic', '1-2', 41, 2, 'fizic'::public.pillar, 'Pași pe potecă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți pe potecă sau pe drumul din curte, cu adult.', '„Potecă. Pași.” pe scurt.']::text[], 'A făcut câțiva pași pe potecă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z2-mental', '1-2', 41, 2, 'mental'::public.pillar, 'Aproape și departe', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați un loc aproape: „Aproape.”', 'Arătați poarta: „Departe.” pe scurt.']::text[], 'A auzit aproape și departe.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z2-resurse', '1-2', 41, 2, 'resurse'::public.pillar, 'Pălăria pe cuier după drum', 4, 'A'::public.completion_mode, ARRAY['pălărie sau șapcă']::text[], ARRAY['După ieșire: puneți pălăria pe cuier sau pe scaun.', '„Pălărie. La loc.”']::text[], 'A ajutat să pună pălăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s41-2-3-z2-social', '1-2', 41, 2, 'social'::public.pillar, 'Pași pe rând pe potecă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi faceți doi pași. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A făcut pași pe rând sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z3-fizic', '1-2', 41, 3, 'fizic'::public.pillar, 'Atingem poarta pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ajungeți la poartă sau gard; atingeți pe scurt, cu adult.', '„Poartă. Uite.” 10–20 de secunde.']::text[], 'A atins poarta sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z3-mental', '1-2', 41, 3, 'mental'::public.pillar, 'Poartă: închisă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați poarta: „Poartă.”', '„Închisă.” pe scurt, dacă e.']::text[], 'A auzit poartă și închisă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z3-resurse', '1-2', 41, 3, 'resurse'::public.pillar, 'Mâna jos, poarta rămâne', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['După atingere: coborâți mâna. Nu deschideți fără adult.', '„Mână. Gata.”']::text[], 'A lăsat poarta și a coborât mâna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z3-social', '1-2', 41, 3, 'social'::public.pillar, 'Arătăm poarta adultului', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați poarta: „Uite.” pe scurt.', 'Adultul privește, fără forțare.']::text[], 'A arătat poarta sau a privit cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z4-fizic', '1-2', 41, 4, 'fizic'::public.pillar, 'Cărăm un obiect până la poartă', 5, 'A'::public.completion_mode, ARRAY['o jucărie ușoară sau găleată goală']::text[], ARRAY['Cărați obiectul ușor câțiva pași spre poartă, cu adult.', '„Cărăm. Poartă.” pe scurt.']::text[], 'A cărat obiectul câțiva pași sau a ținut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z4-mental', '1-2', 41, 4, 'mental'::public.pillar, 'Înainte pe drum', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați înainte: „Înainte.”', 'Faceți un pas: „Drum.” pe scurt.']::text[], 'A auzit înainte și drum.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s41-2-3-z4-resurse', '1-2', 41, 4, 'resurse'::public.pillar, 'Obiectul înapoi lângă ușă', 4, 'A'::public.completion_mode, ARRAY['jucăria sau găleata']::text[], ARRAY['Aduceți obiectul înapoi lângă ușă sau pe treaptă.', '„La loc. Gata.”']::text[], 'A ajutat să aducă obiectul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z4-social', '1-2', 41, 4, 'social'::public.pillar, 'Cărăm împreună spre poartă', 4, 'A'::public.completion_mode, ARRAY['obiect ușor']::text[], ARRAY['Țineți împreună obiectul pe scurt, pe drum.', '„Împreună. Cărăm.” fără forțare.']::text[], 'A ținut împreună sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z5-fizic', '1-2', 41, 5, 'fizic'::public.pillar, 'Pauză la poartă, apoi înapoi', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la poartă pe scurt, apoi întoarceți-vă spre casă, cu adult.', '„Poartă. Înapoi.” 15–20 de secunde la pauză.']::text[], 'A făcut pauză sau a mers înapoi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z5-mental', '1-2', 41, 5, 'mental'::public.pillar, 'Casă și poartă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați casa: „Casă.”', 'Arătați poarta: „Poartă.” pe scurt.']::text[], 'A auzit casă și poartă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z5-resurse', '1-2', 41, 5, 'resurse'::public.pillar, 'Pantofii pe raft după drum', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['După întoarcere: pantofii pe raft sau lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z5-social', '1-2', 41, 5, 'social'::public.pillar, 'Pauză la poartă cu adultul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul la poartă pe scurt.', '„Împreună. Pauză.” fără grabă.']::text[], 'A stat pe scurt lângă adult la poartă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z6-fizic', '1-2', 41, 6, 'fizic'::public.pillar, 'Privim dincolo de poartă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['La poartă: priviți pe scurt afară, fără a ieși singuri, cu adult.', '„Afară. Uite.” 15–20 de secunde.']::text[], 'A privit dincolo de poartă sau a rămas lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s41-2-3-z6-mental', '1-2', 41, 6, 'mental'::public.pillar, 'Curte și drum', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați curtea: „Curte.”', 'Arătați drumul: „Drum.” pe scurt.']::text[], 'A auzit curte și drum.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z6-resurse', '1-2', 41, 6, 'resurse'::public.pillar, 'Haina pe cuier după plimbare', 4, 'A'::public.completion_mode, ARRAY['haină sau jachetă']::text[], ARRAY['Agățați haina pe cuier împreună.', '„Haină. La loc.”']::text[], 'A ajutat să pună haina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z6-social', '1-2', 41, 6, 'social'::public.pillar, 'Joacă paralel pe drumul scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți lângă el pe potecă. Comentați pașii lui.', 'Fără a prelua direcția.']::text[], 'A mers lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z7-fizic', '1-2', 41, 7, 'fizic'::public.pillar, 'Plimbare liberă, poarta la final', 8, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.', 'La final: o privire sau un pas spre poartă dacă vrea.']::text[], 'A explorat liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z7-mental', '1-2', 41, 7, 'mental'::public.pillar, 'Carte: drum și casă', 5, 'A'::public.completion_mode, ARRAY['carte cartonată']::text[], ARRAY['El întoarce pagina.', 'Arătați drum, casă sau poartă dacă e clar: „Drum.”']::text[], 'A rămas la câteva pagini.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z7-resurse', '1-2', 41, 7, 'resurse'::public.pillar, 'Pantofii și haina la loc', 4, 'A'::public.completion_mode, ARRAY['pantofi', 'haină']::text[], ARRAY['Puneți pantofii lângă ușă, haina pe cuier.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă'),
('s41-2-3-z7-social', '1-2', 41, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Drumul până la poartă')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s42-2-3-z1-fizic', '1-2', 42, 1, 'fizic'::public.pillar, 'Pași pe frunze din nou', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară: pășiți pe frunze căzute pe scurt, cu adult.', '„Frunze. Din nou.” 15–20 de secunde.']::text[], 'A pășit pe frunze sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z1-mental', '1-2', 42, 1, 'mental'::public.pillar, 'Vânt și frunză', 3, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Arătați frunza: „Frunză.”', '„Vânt.” pe scurt, dacă se mișcă.']::text[], 'A auzit frunză și vânt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z1-resurse', '1-2', 42, 1, 'resurse'::public.pillar, 'Frunza jos la loc', 4, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Țineți frunza pe scurt, apoi lăsați-o pe pământ.', '„Frunză. La loc.”']::text[], 'A ținut frunza și a lăsat-o jos.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z1-social', '1-2', 42, 1, 'social'::public.pillar, 'Simțim vântul împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați afară unul lângă altul. Ridicați mâna în aer.', '„Împreună. Vânt.” fără grabă.']::text[], 'A stat pe scurt lângă adult afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z2-fizic', '1-2', 42, 2, 'fizic'::public.pillar, 'Culegem o frunză căzută', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Culegeți împreună o frunză de pe jos, cu adult.', '„Frunză. Sus.” pe scurt.']::text[], 'A cules frunza sau a ținut-o.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z2-mental', '1-2', 42, 2, 'mental'::public.pillar, 'Frunza se mișcă', 3, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Arătați frunza care se mișcă: „Se mișcă.”', '„Vânt.” pe scurt.']::text[], 'A privit frunza care se mișcă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z2-resurse', '1-2', 42, 2, 'resurse'::public.pillar, 'Frunza în coș, apoi afară', 4, 'A'::public.completion_mode, ARRAY['o frunză', 'coș mic']::text[], ARRAY['Puneți frunza în coș pe scurt. Apoi lăsați-o afară.', '„Coș. La loc afară.”']::text[], 'A ajutat să pună frunza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s42-2-3-z2-social', '1-2', 42, 2, 'social'::public.pillar, 'Dăm frunza din mână în mână', 4, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['„Ține.” Apoi: „Dă înapoi.” pe scurt.', 'Fără forțare.']::text[], 'A dat sau a primit frunza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z3-fizic', '1-2', 42, 3, 'fizic'::public.pillar, 'Aruncăm frunze în sus pe scurt', 5, 'A'::public.completion_mode, ARRAY['câteva frunze']::text[], ARRAY['Aruncați ușor frunzele în sus, cu adult. Priviți cum cad.', '„Sus. Jos.” pe scurt.']::text[], 'A aruncat sau a privit frunzele.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z3-mental', '1-2', 42, 3, 'mental'::public.pillar, 'Frunză galbenă sau maro', 3, 'A'::public.completion_mode, ARRAY['două frunze']::text[], ARRAY['Arătați: „Galbenă.” pe scurt.', 'Arătați: „Maro.” dacă e.']::text[], 'A auzit culorile frunzelor.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z3-resurse', '1-2', 42, 3, 'resurse'::public.pillar, 'Maturăm trei frunze', 4, 'A'::public.completion_mode, ARRAY['mătură mică']::text[], ARRAY['Adunați câteva frunze într-un colț cu mătura mică.', 'Mătura la loc după: „La loc.”']::text[], 'A ajutat la măturat sau a pus mătura.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z3-social', '1-2', 42, 3, 'social'::public.pillar, 'Aruncăm frunza pe rând', 4, 'A'::public.completion_mode, ARRAY['frunze']::text[], ARRAY['Voi aruncați o frunză. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A aruncat pe rând sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z4-fizic', '1-2', 42, 4, 'fizic'::public.pillar, 'Eșarfa în vânt pe scurt', 5, 'A'::public.completion_mode, ARRAY['eșarfă ușoară']::text[], ARRAY['Țineți eșarfa în aer afară sau la fereastră, cu adult.', '„Eșarfă. Vânt.” 15–20 de secunde.']::text[], 'A ținut eșarfa sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z4-mental', '1-2', 42, 4, 'mental'::public.pillar, 'Eșarfa zboară puțin', 3, 'A'::public.completion_mode, ARRAY['eșarfă']::text[], ARRAY['Lăsați eșarfa să cadă lent: „Jos.”', '„Aer.” pe scurt.']::text[], 'A privit eșarfa care cade.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s42-2-3-z4-resurse', '1-2', 42, 4, 'resurse'::public.pillar, 'Eșarfa pe cârlig', 4, 'A'::public.completion_mode, ARRAY['eșarfă']::text[], ARRAY['Duceți eșarfa la cârlig împreună.', '„Eșarfă. La loc.”']::text[], 'A ajutat să pună eșarfa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z4-social', '1-2', 42, 4, 'social'::public.pillar, 'Ținem eșarfa doi', 4, 'A'::public.completion_mode, ARRAY['eșarfă']::text[], ARRAY['Țineți fiecare un capăt. Mișcați ușor.', '„Împreună.” fără forțare.']::text[], 'A ținut un capăt pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z5-fizic', '1-2', 42, 5, 'fizic'::public.pillar, 'Suflăm pe o frunză', 5, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Puneți frunza pe masă sau pe jos. Suflați ușor, cu adult.', '„Aer. Se mișcă.” pe scurt.']::text[], 'A suflat sau a privit frunza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z5-mental', '1-2', 42, 5, 'mental'::public.pillar, 'Aer pe față', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Afară sau la fereastră: „Aer.”', '„Pe față.” pe scurt.']::text[], 'A simțit sau a auzit aer pe față.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z5-resurse', '1-2', 42, 5, 'resurse'::public.pillar, 'Frunza înapoi afară', 4, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Duceți frunza la ușă sau afară. Lăsați-o.', '„La loc afară.”']::text[], 'A ajutat să ducă frunza afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z5-social', '1-2', 42, 5, 'social'::public.pillar, 'Suflăm pe rând', 4, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Voi suflați o dată. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A suflat pe rând sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z6-fizic', '1-2', 42, 6, 'fizic'::public.pillar, 'Plimbare scurtă cu vânt și frunze', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ieșiți 2–3 minute. Mergeți liber pe unde sunt frunze, cu adult.', '„Vânt.” doar dacă simte.']::text[], 'A mers liber pe scurt afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s42-2-3-z6-mental', '1-2', 42, 6, 'mental'::public.pillar, 'Copacul se mișcă din nou', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați crengile: „Copac.”', '„Vânt.” pe scurt. Stați 20–30 de secunde.']::text[], 'A privit copacul pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z6-resurse', '1-2', 42, 6, 'resurse'::public.pillar, 'Găleata la loc după frunze', 4, 'A'::public.completion_mode, ARRAY['găleată']::text[], ARRAY['Dacă ați folosit găleata: duceți-o pe treaptă sau în casă.', '„Găleată. La loc.”']::text[], 'A ajutat să pună găleata.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z6-social', '1-2', 42, 6, 'social'::public.pillar, 'Joacă paralel cu frunze', 5, 'A'::public.completion_mode, ARRAY['frunze']::text[], ARRAY['Culegeți frunze lângă el. Comentați ce face.', 'Fără a prelua jocul.']::text[], 'A jucat lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z7-fizic', '1-2', 42, 7, 'fizic'::public.pillar, 'Plimbare liberă, frunză la final', 8, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția afară pe scurt, cu adult.', 'La final: o frunză pe jos dacă vrea.']::text[], 'A explorat liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z7-mental', '1-2', 42, 7, 'mental'::public.pillar, 'Carte: vânt și frunze', 5, 'A'::public.completion_mode, ARRAY['carte cartonată']::text[], ARRAY['El întoarce pagina.', 'Arătați frunză, copac sau cer dacă e clar: „Frunză.”']::text[], 'A rămas la câteva pagini.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z7-resurse', '1-2', 42, 7, 'resurse'::public.pillar, 'Haina de afară pe cârlig', 4, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['Agățați haina pe cârlig împreună.', '„Haină. La loc.”']::text[], 'A ajutat să pună haina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou'),
('s42-2-3-z7-social', '1-2', 42, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Vânt și frunze din nou')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s43-2-3-z1-fizic', '1-2', 43, 1, 'fizic'::public.pillar, 'Punem trei lucruri în coș', 5, 'A'::public.completion_mode, ARRAY['coș mic', 'trei obiecte ușoare']::text[], ARRAY['Puneți împreună trei lucruri în coș, cu adult.', '„Unu. Doi. Trei.” pe scurt.']::text[], 'A pus măcar un obiect în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z1-mental', '1-2', 43, 1, 'mental'::public.pillar, 'Trei în coș', 3, 'A'::public.completion_mode, ARRAY['coș cu obiecte']::text[], ARRAY['Arătați coșul: „Coș.”', '„Trei.” pe scurt.']::text[], 'A auzit coș și trei.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z1-resurse', '1-2', 43, 1, 'resurse'::public.pillar, 'Coșul pe raft', 4, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Puneți coșul pe raft sau pe locul lui.', '„Coș. La loc.”']::text[], 'A ajutat să așeze coșul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z1-social', '1-2', 43, 1, 'social'::public.pillar, 'Dăm un obiect din coș', 4, 'A'::public.completion_mode, ARRAY['obiect din coș']::text[], ARRAY['Oferiți obiectul: „Ține.” pe scurt.', 'Fără forțare.']::text[], 'A dat sau a primit obiectul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z2-fizic', '1-2', 43, 2, 'fizic'::public.pillar, 'Cărăm coșul cinci pași', 5, 'A'::public.completion_mode, ARRAY['coș ușor']::text[], ARRAY['El ține coșul (sau pe jumătate cu voi). Mergeți 5 pași.', '„Cărăm. Coș.” pe scurt.']::text[], 'A cărat coșul câțiva pași sau a ținut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z2-mental', '1-2', 43, 2, 'mental'::public.pillar, 'Plin și gol', 3, 'A'::public.completion_mode, ARRAY['coș', 'un obiect']::text[], ARRAY['Cu obiect: „Plin.” pe scurt.', 'Fără obiect: „Gol.”']::text[], 'A auzit plin și gol.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z2-resurse', '1-2', 43, 2, 'resurse'::public.pillar, 'Golim coșul pe masă, apoi la loc', 4, 'A'::public.completion_mode, ARRAY['coș', 'obiecte']::text[], ARRAY['Scoateți obiectele pe masă pe scurt. Apoi totul înapoi în coș.', '„La loc.”']::text[], 'A ajutat să golească sau să umple coșul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s43-2-3-z2-social', '1-2', 43, 2, 'social'::public.pillar, 'Cărăm coșul împreună', 4, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Țineți coșul împreună pe scurt.', '„Împreună. Coș.” fără forțare.']::text[], 'A ținut coșul împreună sau a mers lângă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z3-fizic', '1-2', 43, 3, 'fizic'::public.pillar, 'Strângem jucării în coș', 5, 'A'::public.completion_mode, ARRAY['coș', 'jucării de pe jos']::text[], ARRAY['Culegeți două–trei jucării de pe jos în coș, cu adult.', '„Strângem. Coș.” pe scurt.']::text[], 'A pus măcar o jucărie în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z3-mental', '1-2', 43, 3, 'mental'::public.pillar, 'Unde e coșul', 3, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Întrebați: „Unde e?” pe scurt.', 'Arătați: „Aici. Coș.”']::text[], 'A auzit unde și aici.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z3-resurse', '1-2', 43, 3, 'resurse'::public.pillar, 'Coșul lângă jucării, pe raft', 4, 'A'::public.completion_mode, ARRAY['coș cu jucării']::text[], ARRAY['Duceți coșul lângă raftul de jucării.', '„Coș. Raft.”']::text[], 'A ajutat să ducă coșul la raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z3-social', '1-2', 43, 3, 'social'::public.pillar, 'Arătăm coșul adultului', 4, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Arătați coșul: „Uite.” pe scurt.', 'Adultul privește, fără forțare.']::text[], 'A arătat coșul sau a privit cu adultul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z4-fizic', '1-2', 43, 4, 'fizic'::public.pillar, 'Două grămezi în coș', 5, 'A'::public.completion_mode, ARRAY['coș', 'obiecte de două feluri']::text[], ARRAY['Faceți două grămezi pe masă. Puneți pe rând în coș, cu adult.', '„Aici. Coș.” pe scurt.']::text[], 'A pus măcar un obiect în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z4-mental', '1-2', 43, 4, 'mental'::public.pillar, 'Aici și aici', 3, 'A'::public.completion_mode, ARRAY['două locuri pe masă']::text[], ARRAY['Arătați: „Aici.” pe un loc.', '„Aici.” pe celălalt, pe scurt.']::text[], 'A auzit aici de două ori.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s43-2-3-z4-resurse', '1-2', 43, 4, 'resurse'::public.pillar, 'Totul în coș după sortare', 4, 'A'::public.completion_mode, ARRAY['coș', 'obiecte']::text[], ARRAY['Adunați totul în coș.', '„În coș. La loc.”']::text[], 'A ajutat să adune totul în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z4-social', '1-2', 43, 4, 'social'::public.pillar, 'Punem în coș pe rând', 4, 'A'::public.completion_mode, ARRAY['coș', 'obiecte']::text[], ARRAY['Voi puneți un obiect. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A pus pe rând sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z5-fizic', '1-2', 43, 5, 'fizic'::public.pillar, 'Culegem afară în coș', 5, 'A'::public.completion_mode, ARRAY['coș mic']::text[], ARRAY['Ieșiți scurt. Culegeți două–trei frunze sau pietre în coș, cu adult.', '„Coș. Afară.” pe scurt.']::text[], 'A pus ceva în coș afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z5-mental', '1-2', 43, 5, 'mental'::public.pillar, 'Piatră sau frunză în coș', 3, 'A'::public.completion_mode, ARRAY['piatră', 'frunză']::text[], ARRAY['Arătați: „Piatră.” pe scurt.', 'Arătați: „Frunză.”']::text[], 'A auzit piatră și frunză.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z5-resurse', '1-2', 43, 5, 'resurse'::public.pillar, 'Lăsăm afară ce am cules', 4, 'A'::public.completion_mode, ARRAY['coș cu frunze sau pietre']::text[], ARRAY['Puneți pietrele sau frunzele înapoi pe jos.', '„La loc afară.” Coșul gol pe treaptă.']::text[], 'A ajutat să lase afară și să așeze coșul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z5-social', '1-2', 43, 5, 'social'::public.pillar, 'Arătăm ce am cules', 4, 'A'::public.completion_mode, ARRAY['un obiect din coș']::text[], ARRAY['Arătați obiectul unui adult din casă: „Uite.”', 'pe scurt, fără forțare.']::text[], 'A arătat obiectul sau a ținut lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z6-fizic', '1-2', 43, 6, 'fizic'::public.pillar, 'Strângem camera cu coșul', 6, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Mergeți prin cameră cu coșul. Puneți două–trei lucruri, cu adult.', '„Strângem.” pe scurt.']::text[], 'A pus măcar un lucru în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s43-2-3-z6-mental', '1-2', 43, 6, 'mental'::public.pillar, 'Mult și puțin', 3, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Cu câteva obiecte: „Mult.” pe scurt.', 'Cu unul: „Puțin.”']::text[], 'A auzit mult și puțin.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z6-resurse', '1-2', 43, 6, 'resurse'::public.pillar, 'Coșul pe locul lui acasă', 4, 'A'::public.completion_mode, ARRAY['coș']::text[], ARRAY['Duceți coșul pe locul lui cunoscut.', '„Coș. La loc.”']::text[], 'A ajutat să pună coșul la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z6-social', '1-2', 43, 6, 'social'::public.pillar, 'Strângem paralel cu adultul', 5, 'A'::public.completion_mode, ARRAY['coș sau cutie']::text[], ARRAY['Voi strângeți lângă el. Comentați ce pune el.', 'Fără a prelua totul.']::text[], 'A strâns lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z7-fizic', '1-2', 43, 7, 'fizic'::public.pillar, 'Plimbare liberă, coș dacă vrea', 8, 'A'::public.completion_mode, ARRAY['coș opțional']::text[], ARRAY['El dictează direcția pe scurt, cu adult.', 'Culegeți ceva în coș doar dacă arată el.']::text[], 'A explorat liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z7-mental', '1-2', 43, 7, 'mental'::public.pillar, 'Carte: multe obiecte', 5, 'A'::public.completion_mode, ARRAY['carte cartonată']::text[], ARRAY['El întoarce pagina.', 'Arătați două lucruri din imagine dacă e clar: „Uite.”']::text[], 'A rămas la câteva pagini.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z7-resurse', '1-2', 43, 7, 'resurse'::public.pillar, 'Jucăriile în coș', 4, 'A'::public.completion_mode, ARRAY['coș', 'jucării']::text[], ARRAY['Adunați două–trei jucării în coș.', '„La loc.”']::text[], 'A ajutat să pună jucăriile în coș.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul'),
('s43-2-3-z7-social', '1-2', 43, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Coșul și strânsul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s44-2-3-z1-fizic', '1-2', 44, 1, 'fizic'::public.pillar, 'Mână ridicată: bună pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați mâna o dată: „Bună.” Coborâți mâna, cu adult.', '10–15 de secunde, fără forțare.']::text[], 'A ridicat mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z1-mental', '1-2', 44, 1, 'mental'::public.pillar, 'Bună — cuvânt scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Spuneți blând: „Bună.”', 'Arătați mâna: „Salut.” pe scurt.']::text[], 'A auzit bună și salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z1-resurse', '1-2', 44, 1, 'resurse'::public.pillar, 'Jucăria-oaspete pe raft', 4, 'A'::public.completion_mode, ARRAY['o jucărie moale']::text[], ARRAY['Luați jucăria pe scurt ca „oaspete”. Puneți-o pe raft.', '„Jucărie. La loc.”']::text[], 'A ajutat să pună jucăria pe raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z1-social', '1-2', 44, 1, 'social'::public.pillar, 'Stăm unul lângă altul pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați unul lângă altul pe scaun sau pe covor.', '„Împreună. Familie.” fără grabă.']::text[], 'A stat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z2-fizic', '1-2', 44, 2, 'fizic'::public.pillar, 'Arătăm poza de familie', 5, 'A'::public.completion_mode, ARRAY['o poză de familie']::text[], ARRAY['Arătați poza. Atingeți cu degetul pe scurt, cu adult.', '„Familie.” 15–20 de secunde.']::text[], 'A atins poza sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z2-mental', '1-2', 44, 2, 'mental'::public.pillar, 'Mama, tata, tu', 3, 'A'::public.completion_mode, ARRAY['poză opțională']::text[], ARRAY['Arătați: „Mama.” sau „Tata.” pe scurt.', 'Arătați-l pe el: „Tu.”']::text[], 'A auzit numele din familie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z2-resurse', '1-2', 44, 2, 'resurse'::public.pillar, 'Poza pe raft sau pe masă', 4, 'A'::public.completion_mode, ARRAY['poză']::text[], ARRAY['Puneți poza pe raft sau pe masă la loc.', '„Poză. La loc.”']::text[], 'A ajutat să așeze poza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s44-2-3-z2-social', '1-2', 44, 2, 'social'::public.pillar, 'Privim poza împreună', 4, 'A'::public.completion_mode, ARRAY['poză']::text[], ARRAY['Stați unul lângă altul și priviți poza pe scurt.', '„Împreună. Familie.” fără forțare.']::text[], 'A privit poza lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z3-fizic', '1-2', 44, 3, 'fizic'::public.pillar, 'Dăm jucăria-prieten din mână', 5, 'A'::public.completion_mode, ARRAY['jucărie moale']::text[], ARRAY['Treceți jucăria din mână în mână pe scurt, cu adult.', '„Prieten. Ține.” 10–20 de secunde.']::text[], 'A ținut sau a dat jucăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z3-mental', '1-2', 44, 3, 'mental'::public.pillar, 'Prieten: jucăria', 3, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['Arătați jucăria: „Prieten.”', 'Sau numele ei pe scurt, dacă are.']::text[], 'A auzit prieten.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z3-resurse', '1-2', 44, 3, 'resurse'::public.pillar, 'Jucăria pe pat sau pe raft', 4, 'A'::public.completion_mode, ARRAY['jucărie moale']::text[], ARRAY['Puneți jucăria pe pat sau pe raft.', '„Prieten. La loc.”']::text[], 'A ajutat să pună jucăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z3-social', '1-2', 44, 3, 'social'::public.pillar, 'Oferim jucăria adultului', 4, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['Oferiți jucăria: „Ține.” pe scurt.', 'Fără forțare.']::text[], 'A oferit jucăria sau a ținut-o lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z4-fizic', '1-2', 44, 4, 'fizic'::public.pillar, 'Pași până la ușă: salut', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți până la ușă pe scurt, cu adult. Ridicați mâna.', '„Bună.” sau „La revedere.” pe scurt.']::text[], 'A mers la ușă sau a ridicat mâna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z4-mental', '1-2', 44, 4, 'mental'::public.pillar, 'La revedere pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Spuneți blând: „La revedere.”', 'Coborâți mâna: „Gata.” pe scurt.']::text[], 'A auzit la revedere.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s44-2-3-z4-resurse', '1-2', 44, 4, 'resurse'::public.pillar, 'Pantofii lângă ușă după salut', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z4-social', '1-2', 44, 4, 'social'::public.pillar, 'Salut la ușă cu adultul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['La ușă, lângă adult: „Bună.” pe scurt.', 'Fără forțare dacă nu vrea să vorbească.']::text[], 'A fost la ușă lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z5-fizic', '1-2', 44, 5, 'fizic'::public.pillar, 'Batem din palme o dată împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Bateți din palme o dată, cu adult. Apoi mâinile jos.', '„Împreună.” pe scurt, fără forțare.']::text[], 'A bătut din palme sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z5-mental', '1-2', 44, 5, 'mental'::public.pillar, 'Prieten și familie', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Spuneți: „Prieten.” pe scurt.', 'Spuneți: „Familie.”']::text[], 'A auzit prieten și familie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z5-resurse', '1-2', 44, 5, 'resurse'::public.pillar, 'Paharul de oaspete pe masă, apoi la loc', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Așezați paharul pe masă pe scurt ca pentru oaspete.', 'Apoi: „Pahar. La loc.”']::text[], 'A ajutat să așeze și să pună paharul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z5-social', '1-2', 44, 5, 'social'::public.pillar, 'Salut pe rând cu mâna', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi ridicați mâna. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A ridicat mâna pe rând sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z6-fizic', '1-2', 44, 6, 'fizic'::public.pillar, 'Joacă liberă lângă jucăria-prieten', 6, 'A'::public.completion_mode, ARRAY['jucărie moale']::text[], ARRAY['Stați pe covor cu jucăria lângă el, cu adult.', 'El dictează joaca pe scurt.']::text[], 'A jucat liber pe scurt lângă jucărie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s44-2-3-z6-mental', '1-2', 44, 6, 'mental'::public.pillar, 'Familie în carte', 4, 'A'::public.completion_mode, ARRAY['carte cartonată']::text[], ARRAY['El întoarce pagina.', 'Arătați o familie din imagine dacă e clar: „Familie.”']::text[], 'A privit pagina cu familie sau a rămas la carte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z6-resurse', '1-2', 44, 6, 'resurse'::public.pillar, 'Jucăriile la loc după joacă', 4, 'A'::public.completion_mode, ARRAY['jucării', 'coș sau raft']::text[], ARRAY['Puneți două–trei jucării la loc.', '„La loc. Gata.”']::text[], 'A ajutat să pună jucăriile.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z6-social', '1-2', 44, 6, 'social'::public.pillar, 'Joacă paralel cu adultul', 5, 'A'::public.completion_mode, ARRAY['jucării']::text[], ARRAY['Stați lângă el cu jucăriile voastre. Comentați ce face.', 'Fără a prelua jocul.']::text[], 'A jucat lângă adult pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z7-fizic', '1-2', 44, 7, 'fizic'::public.pillar, 'Plimbare liberă, salut la final', 8, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția prin casă sau curte pe scurt, cu adult.', 'La final: o mână ridicată „Bună.” dacă vrea.']::text[], 'A explorat liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z7-mental', '1-2', 44, 7, 'mental'::public.pillar, 'Carte: familie și casă', 5, 'A'::public.completion_mode, ARRAY['carte cartonată']::text[], ARRAY['El întoarce pagina.', 'Arătați o familie din imagine: „Familie.”']::text[], 'A rămas la câteva pagini.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z7-resurse', '1-2', 44, 7, 'resurse'::public.pillar, 'Haina și jucăria la loc', 4, 'A'::public.completion_mode, ARRAY['haină', 'jucărie']::text[], ARRAY['Puneți haina pe cuier, jucăria pe raft.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie'),
('s44-2-3-z7-social', '1-2', 44, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Prieteni și familie')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
