insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s45-2-3-z1-fizic', '1-2', 45, 1, 'fizic'::public.pillar, 'Pași mulți în casă pe scurt', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['În casă: faceți mulți pași pe scurt, cu adult.', '„Pași. Puternic.” fără grabă.']::text[], 'A făcut câțiva pași sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z1-mental', '1-2', 45, 1, 'mental'::public.pillar, 'Corp: puternic', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Corp.” pe scurt.', '„Puternic.” fără forțare.']::text[], 'A auzit corp și puternic.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z1-resurse', '1-2', 45, 1, 'resurse'::public.pillar, 'Pantofii înainte de pași', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă pe scurt.', '„Pantofi. Aici.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z1-social', '1-2', 45, 1, 'social'::public.pillar, 'Pași puternici împreună', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți unul lângă altul pe scurt.', '„Împreună. Pași.” fără forțare.']::text[], 'A mers pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z2-fizic', '1-2', 45, 2, 'fizic'::public.pillar, 'Sărituri mici pe loc', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Țineți mâinile: două–cinci sărituri mici, cu adult.', '„Sărim.” pe scurt, fără grabă.']::text[], 'A sărit sau a încercat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z2-mental', '1-2', 45, 2, 'mental'::public.pillar, 'Sus și jos: corp', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Sus.” pe scurt când ridicați brațele.', '„Jos.” fără forțare.']::text[], 'A auzit sus și jos.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z2-resurse', '1-2', 45, 2, 'resurse'::public.pillar, 'Mingea ușoară în palmă', 4, 'A'::public.completion_mode, ARRAY['minge ușoară']::text[], ARRAY['Țineți mingea pe scurt în palmă.', '„Minge. Palmă.”']::text[], 'A ținut mingea sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s45-2-3-z2-social', '1-2', 45, 2, 'social'::public.pillar, 'Sărim pe rând pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi săriți o dată pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a sărit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z3-fizic', '1-2', 45, 3, 'fizic'::public.pillar, 'Cărăm ceva ușor câțiva pași', 5, 'A'::public.completion_mode, ARRAY['obiect ușor (jucărie, pernă)']::text[], ARRAY['Cărați obiectul ușor 5–10 pași, cu adult.', '„Cărăm. Puternic.” pe scurt.']::text[], 'A cărat obiectul sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z3-mental', '1-2', 45, 3, 'mental'::public.pillar, 'Greu și ușor pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Ușor.” pe scurt.', '„Greu.” fără grabă, fără forțare.']::text[], 'A auzit ușor și greu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z3-resurse', '1-2', 45, 3, 'resurse'::public.pillar, 'Obiectul pe masă după cărat', 4, 'A'::public.completion_mode, ARRAY['obiect ușor']::text[], ARRAY['Așezați obiectul pe masă pe scurt.', '„Aici. Gata.”']::text[], 'A ajutat să așeze obiectul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z3-social', '1-2', 45, 3, 'social'::public.pillar, 'Cărăm pe rând', 5, 'A'::public.completion_mode, ARRAY['obiect ușor']::text[], ARRAY['Voi cărați pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a cărat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z4-fizic', '1-2', 45, 4, 'fizic'::public.pillar, 'Brațe sus, corp puternic', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați brațele sus pe scurt, cu adult.', '„Brațe. Puternic.” 10–20 de secunde.']::text[], 'A ridicat brațele sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z4-mental', '1-2', 45, 4, 'mental'::public.pillar, 'Brațe și picioare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Brațe.” pe scurt.', '„Picioare.” fără forțare.']::text[], 'A auzit brațe și picioare.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s45-2-3-z4-resurse', '1-2', 45, 4, 'resurse'::public.pillar, 'Mâinile pe genunchi, apoi jos', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți mâinile pe genunchi pe scurt.', '„Mâini. Jos.” apoi mâinile jos.']::text[], 'A atins genunchii sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z4-social', '1-2', 45, 4, 'social'::public.pillar, 'Brațe sus împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați brațele unul lângă altul pe scurt.', '„Împreună. Brațe.” fără forțare.']::text[], 'A ridicat brațele sau a stat lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z5-fizic', '1-2', 45, 5, 'fizic'::public.pillar, 'Pași pe loc, apoi înainte', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['Pași pe loc pe scurt, apoi câțiva pași înainte, cu adult.', '„Pe loc. Înainte.” fără grabă.']::text[], 'A făcut pași pe loc sau înainte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z5-mental', '1-2', 45, 5, 'mental'::public.pillar, 'Înainte și pe loc', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Pe loc.” pe scurt.', '„Înainte.” fără forțare.']::text[], 'A auzit pe loc și înainte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z5-resurse', '1-2', 45, 5, 'resurse'::public.pillar, 'Calea liberă pe podea', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Îndepărtați un obiect din cale pe scurt.', '„Cale. Liber.”']::text[], 'A ajutat să elibereze calea sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z5-social', '1-2', 45, 5, 'social'::public.pillar, 'Pași înainte cu adultul', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți înainte unul lângă altul pe scurt.', '„Împreună. Înainte.” fără forțare.']::text[], 'A mers pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z6-fizic', '1-2', 45, 6, 'fizic'::public.pillar, 'Pași mulți dus-întors pe scurt', 7, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți până la perete sau ușă, apoi înapoi, cu adult.', '„Dus. Întors.” pe scurt.']::text[], 'A făcut drumul dus-întors pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s45-2-3-z6-mental', '1-2', 45, 6, 'mental'::public.pillar, 'Mulți pași: unu și doi', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Pași.” pe scurt.', '„Unu. Doi.” fără forțare.']::text[], 'A auzit pași și numere scurte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z6-resurse', '1-2', 45, 6, 'resurse'::public.pillar, 'Pantofii la loc după pași', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['După pași: puneți pantofii lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z6-social', '1-2', 45, 6, 'social'::public.pillar, 'Dus-întors cu adultul', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți drumul împreună, fără grabă.', '„Împreună. Pași.” fără forțare.']::text[], 'A mers pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z7-fizic', '1-2', 45, 7, 'fizic'::public.pillar, 'Plimbare liberă cu pași mulți, pe scurt', 7, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează ritmul pașilor pe scurt, cu adult.', 'La final: brațe sus dacă vrea.']::text[], 'A mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z7-mental', '1-2', 45, 7, 'mental'::public.pillar, 'Carte: corp și pași', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați corp, picioare sau pași dacă e clar: „Pași.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z7-resurse', '1-2', 45, 7, 'resurse'::public.pillar, 'Mingea și pantofii la loc', 4, 'A'::public.completion_mode, ARRAY['minge', 'pantofi']::text[], ARRAY['Puneți mingea și pantofii la loc pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună cel puțin un lucru la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți'),
('s45-2-3-z7-social', '1-2', 45, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Corp puternic, pași mulți')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s46-2-3-z1-fizic', '1-2', 46, 1, 'fizic'::public.pillar, 'Arătăm cu degetul pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Întindeți degetul și arătați un obiect, cu adult.', '„Uite.” 10–20 de secunde.']::text[], 'A arătat sau a privit degetul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z1-mental', '1-2', 46, 1, 'mental'::public.pillar, 'Unde e mingea?', 4, 'A'::public.completion_mode, ARRAY['minge']::text[], ARRAY['„Unde e mingea?” pe scurt.', 'Arătați mingea: „Aici.” fără forțare.']::text[], 'A auzit unde e și aici.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z1-resurse', '1-2', 46, 1, 'resurse'::public.pillar, 'Mingea pe masă, la vedere', 4, 'A'::public.completion_mode, ARRAY['minge']::text[], ARRAY['Așezați mingea pe masă pe scurt.', '„Minge. Aici.”']::text[], 'A ajutat să așeze mingea sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z1-social', '1-2', 46, 1, 'social'::public.pillar, 'Arătăm mingea adultului', 4, 'A'::public.completion_mode, ARRAY['minge']::text[], ARRAY['Arătați mingea: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z2-fizic', '1-2', 46, 2, 'fizic'::public.pillar, 'Căutăm pe scurt în cameră', 5, 'A'::public.completion_mode, ARRAY['jucărie la vedere']::text[], ARRAY['Mergeți câțiva pași și căutați jucăria, cu adult.', '„Căutăm.” pe scurt, fără grabă.']::text[], 'A căutat sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z2-mental', '1-2', 46, 2, 'mental'::public.pillar, 'Unde e jucăria?', 4, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['„Unde e jucăria?” pe scurt.', 'Arătați: „Acolo.” fără forțare.']::text[], 'A auzit unde e și acolo.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z2-resurse', '1-2', 46, 2, 'resurse'::public.pillar, 'Jucăria pe scaun la vedere', 4, 'A'::public.completion_mode, ARRAY['jucărie', 'scaun']::text[], ARRAY['Puneți jucăria pe scaun pe scurt.', '„Jucărie. Scaun.”']::text[], 'A ajutat să pună jucăria sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s46-2-3-z2-social', '1-2', 46, 2, 'social'::public.pillar, 'Căutăm pe rând pe scurt', 5, 'A'::public.completion_mode, ARRAY['jucărie']::text[], ARRAY['Voi arătați jucăria pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z3-fizic', '1-2', 46, 3, 'fizic'::public.pillar, 'Arătăm ușa cu degetul', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați ușa cu degetul, cu adult.', '„Ușă.” pe scurt.']::text[], 'A arătat ușa sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z3-mental', '1-2', 46, 3, 'mental'::public.pillar, 'Unde e ușa?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Unde e ușa?” pe scurt.', 'Arătați: „Aici.” fără forțare.']::text[], 'A auzit unde e ușa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z3-resurse', '1-2', 46, 3, 'resurse'::public.pillar, 'Mâna pe ușă pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți ușa pe scurt, cu adult.', '„Ușă. Mână.” apoi mâna jos.']::text[], 'A atins ușa sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z3-social', '1-2', 46, 3, 'social'::public.pillar, 'Arătăm ușa împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați ușa unul lângă altul pe scurt.', '„Împreună. Ușă.” fără forțare.']::text[], 'A arătat sau a stat lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z4-fizic', '1-2', 46, 4, 'fizic'::public.pillar, 'Arătăm fereastra pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați fereastra cu degetul, cu adult.', '„Fereastră.” 10–20 de secunde.']::text[], 'A arătat fereastra sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z4-mental', '1-2', 46, 4, 'mental'::public.pillar, 'Unde e fereastra?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Unde e fereastra?” pe scurt.', 'Arătați: „Acolo.” fără forțare.']::text[], 'A auzit unde e fereastra.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s46-2-3-z4-resurse', '1-2', 46, 4, 'resurse'::public.pillar, 'Perdeaua sau geamul pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți perdea sau geam pe scurt, cu adult.', '„Geam. Aici.”']::text[], 'A atins geamul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z4-social', '1-2', 46, 4, 'social'::public.pillar, 'Privim pe fereastră împreună', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la fereastră unul lângă altul pe scurt.', '„Împreună. Uite.” fără forțare.']::text[], 'A privit pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z5-fizic', '1-2', 46, 5, 'fizic'::public.pillar, 'Arătăm scaunul și masa', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați scaunul, apoi masa, cu adult.', '„Scaun. Masă.” pe scurt.']::text[], 'A arătat sau a privit cele două.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z5-mental', '1-2', 46, 5, 'mental'::public.pillar, 'Unde e scaunul?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Unde e scaunul?” pe scurt.', 'Arătați: „Aici.” fără forțare.']::text[], 'A auzit unde e scaunul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z5-resurse', '1-2', 46, 5, 'resurse'::public.pillar, 'Paharul pe masă, arătat', 4, 'A'::public.completion_mode, ARRAY['pahar']::text[], ARRAY['Așezați paharul pe masă pe scurt.', '„Pahar. Masă.”']::text[], 'A ajutat să așeze paharul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z5-social', '1-2', 46, 5, 'social'::public.pillar, 'Arătăm pe rând: scaun, masă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi arătați scaunul pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z6-fizic', '1-2', 46, 6, 'fizic'::public.pillar, 'Căutăm pantofii pe scurt', 5, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Căutați pantofii lângă ușă, cu adult.', '„Pantofi. Unde?” pe scurt.']::text[], 'A căutat pantofii sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s46-2-3-z6-mental', '1-2', 46, 6, 'mental'::public.pillar, 'Unde sunt pantofii?', 3, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['„Unde sunt pantofii?” pe scurt.', 'Arătați: „Aici.” fără forțare.']::text[], 'A auzit unde sunt pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z6-resurse', '1-2', 46, 6, 'resurse'::public.pillar, 'Pantofii la loc după arătat', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Puneți pantofii lângă ușă pe scurt.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z6-social', '1-2', 46, 6, 'social'::public.pillar, 'Arătăm pantofii adultului', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Arătați pantofii: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z7-fizic', '1-2', 46, 7, 'fizic'::public.pillar, 'Plimbare liberă cu arătatul, pe scurt', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează ce arată pe scurt, cu adult.', 'La final: un „Uite.” dacă vrea.']::text[], 'A arătat sau a mers liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z7-mental', '1-2', 46, 7, 'mental'::public.pillar, 'Carte: unde e?', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', '„Unde e…?” Arătați o imagine clară: „Aici.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z7-resurse', '1-2', 46, 7, 'resurse'::public.pillar, 'Jucăria și cartea la loc', 4, 'A'::public.completion_mode, ARRAY['jucărie', 'carte']::text[], ARRAY['Puneți jucăria și cartea la loc pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună cel puțin un lucru la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul'),
('s46-2-3-z7-social', '1-2', 46, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Întrebări cu arătatul')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s47-2-3-z1-fizic', '1-2', 47, 1, 'fizic'::public.pillar, 'Luăm o jucărie pe scurt', 4, 'A'::public.completion_mode, ARRAY['1 jucărie']::text[], ARRAY['Luați o jucărie în mână pe scurt, cu adult.', '„Jucărie.” 10–20 de secunde.']::text[], 'A ținut jucăria sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z1-mental', '1-2', 47, 1, 'mental'::public.pillar, 'Al meu: jucăria', 3, 'A'::public.completion_mode, ARRAY['1 jucărie']::text[], ARRAY['„Al meu.” pe scurt, arătând jucăria.', '„Jucărie.” fără forțare.']::text[], 'A auzit al meu și jucărie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z1-resurse', '1-2', 47, 1, 'resurse'::public.pillar, 'Jucăria pe masă, a mea', 4, 'A'::public.completion_mode, ARRAY['1 jucărie']::text[], ARRAY['Așezați jucăria pe masă pe scurt.', '„A mea. Aici.”']::text[], 'A ajutat să așeze jucăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z1-social', '1-2', 47, 1, 'social'::public.pillar, 'Arătăm jucăria: a mea', 4, 'A'::public.completion_mode, ARRAY['1 jucărie']::text[], ARRAY['Arătați jucăria adultului: „A mea.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A arătat sau a privit împreună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z2-fizic', '1-2', 47, 2, 'fizic'::public.pillar, 'Purtăm jucăria până la cutie', 5, 'A'::public.completion_mode, ARRAY['1 jucărie', 'cutie']::text[], ARRAY['Cărați jucăria până la cutie, cu adult.', '„Până la cutie.” pe scurt.']::text[], 'A cărat jucăria sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z2-mental', '1-2', 47, 2, 'mental'::public.pillar, 'La loc: cutie', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„La loc.” pe scurt.', '„Cutie.” fără forțare.']::text[], 'A auzit la loc și cutie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z2-resurse', '1-2', 47, 2, 'resurse'::public.pillar, 'Jucăria în cutie pe scurt', 5, 'A'::public.completion_mode, ARRAY['1 jucărie', 'cutie']::text[], ARRAY['Puneți jucăria în cutie pe scurt.', '„În cutie. La loc.”']::text[], 'A ajutat să pună jucăria în cutie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s47-2-3-z2-social', '1-2', 47, 2, 'social'::public.pillar, 'Punem la loc pe rând', 5, 'A'::public.completion_mode, ARRAY['jucărie', 'cutie']::text[], ARRAY['Voi puneți jucăria în cutie pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a pus la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z3-fizic', '1-2', 47, 3, 'fizic'::public.pillar, 'Strângem două lucruri pe scurt', 5, 'A'::public.completion_mode, ARRAY['2 obiecte mici']::text[], ARRAY['Adunați două obiecte de pe jos, cu adult.', '„Una. Alta.” pe scurt.']::text[], 'A adunat sau a ajutat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z3-mental', '1-2', 47, 3, 'mental'::public.pillar, 'Una și alta: la loc', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Una.” pe scurt.', '„Alta. La loc.” fără forțare.']::text[], 'A auzit una, alta și la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z3-resurse', '1-2', 47, 3, 'resurse'::public.pillar, 'Două lucruri în cutie', 5, 'A'::public.completion_mode, ARRAY['2 obiecte', 'cutie']::text[], ARRAY['Puneți cele două obiecte în cutie.', '„În cutie. Gata.”']::text[], 'A ajutat să pună cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z3-social', '1-2', 47, 3, 'social'::public.pillar, 'Strângem împreună pe scurt', 5, 'A'::public.completion_mode, ARRAY['2 obiecte', 'cutie']::text[], ARRAY['Strângeți unul lângă altul pe scurt.', '„Împreună. La loc.” fără forțare.']::text[], 'A strâns pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z4-fizic', '1-2', 47, 4, 'fizic'::public.pillar, 'Haina pe cuier pe scurt', 4, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['Luați haina și duceți-o la cuier, cu adult.', '„Haină. Cuier.” pe scurt.']::text[], 'A ajutat să ducă haina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z4-mental', '1-2', 47, 4, 'mental'::public.pillar, 'Haina: a mea, la loc', 3, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['„A mea.” pe scurt, arătând haina.', '„La loc.” fără forțare.']::text[], 'A auzit a mea și la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s47-2-3-z4-resurse', '1-2', 47, 4, 'resurse'::public.pillar, 'Haina pe cuier, grijă', 4, 'A'::public.completion_mode, ARRAY['haină', 'cuier']::text[], ARRAY['Puneți haina pe cuier pe scurt.', '„Haină. La loc.”']::text[], 'A ajutat să pună haina pe cuier.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z4-social', '1-2', 47, 4, 'social'::public.pillar, 'Punem haina împreună', 4, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['Puneți haina pe cuier unul lângă altul.', '„Împreună. Haină.” fără forțare.']::text[], 'A ajutat pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z5-fizic', '1-2', 47, 5, 'fizic'::public.pillar, 'Cartea pe raft pe scurt', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Duceți cartea până la raft, cu adult.', '„Carte. Raft.” pe scurt.']::text[], 'A dus cartea sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z5-mental', '1-2', 47, 5, 'mental'::public.pillar, 'Cartea: unde stă?', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['„Unde stă cartea?” pe scurt.', 'Arătați raftul: „Aici. La loc.”']::text[], 'A auzit unde stă și la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z5-resurse', '1-2', 47, 5, 'resurse'::public.pillar, 'Cartea pe raft, grijă', 4, 'A'::public.completion_mode, ARRAY['carte', 'raft']::text[], ARRAY['Puneți cartea pe raft pe scurt.', '„Carte. La loc.”']::text[], 'A ajutat să pună cartea pe raft.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z5-social', '1-2', 47, 5, 'social'::public.pillar, 'Cartea la loc pe rând', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Voi puneți cartea pe raft pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a pus cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z6-fizic', '1-2', 47, 6, 'fizic'::public.pillar, 'Trei lucruri la loc pe scurt', 6, 'A'::public.completion_mode, ARRAY['3 obiecte mici']::text[], ARRAY['Adunați trei obiecte și duceți-le la loc, cu adult.', '„Una. Două. Trei.” pe scurt.']::text[], 'A ajutat la cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s47-2-3-z6-mental', '1-2', 47, 6, 'mental'::public.pillar, 'Grijă: al meu, la loc', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Grijă.” pe scurt.', '„Al meu. La loc.” fără forțare.']::text[], 'A auzit grijă, al meu și la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z6-resurse', '1-2', 47, 6, 'resurse'::public.pillar, 'Cutia cu lucruri la loc', 5, 'A'::public.completion_mode, ARRAY['cutie', 'obiecte']::text[], ARRAY['Puneți cutia pe raft sau pe jos la loc.', '„Cutie. La loc.”']::text[], 'A ajutat să așeze cutia.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z6-social', '1-2', 47, 6, 'social'::public.pillar, 'Grijă de lucruri împreună', 5, 'A'::public.completion_mode, ARRAY['cutie']::text[], ARRAY['Strângeți pe scurt unul lângă altul.', '„Împreună. Grijă.” fără forțare.']::text[], 'A strâns pe scurt lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z7-fizic', '1-2', 47, 7, 'fizic'::public.pillar, 'Plimbare liberă și un lucru la loc', 6, 'A'::public.completion_mode, ARRAY['1 jucărie']::text[], ARRAY['El dictează pe scurt, cu adult.', 'La final: un lucru la loc dacă vrea.']::text[], 'A mers liber sau a pus un lucru la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z7-mental', '1-2', 47, 7, 'mental'::public.pillar, 'Carte: grijă de lucruri', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați cutie sau jucărie dacă e clar: „La loc.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z7-resurse', '1-2', 47, 7, 'resurse'::public.pillar, 'Jucăria și haina la loc', 4, 'A'::public.completion_mode, ARRAY['jucărie', 'haină']::text[], ARRAY['Puneți jucăria în cutie, haina pe cuier dacă e.', '„La loc. Gata.”']::text[], 'A ajutat să pună cel puțin un lucru la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri'),
('s47-2-3-z7-social', '1-2', 47, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Grijă de lucruri')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s48-2-3-z1-fizic', '1-2', 48, 1, 'fizic'::public.pillar, 'Mâna sus: salut pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ridicați mâna: „Salut.” pe scurt, cu adult.', '10–15 de secunde, fără forțare.']::text[], 'A ridicat mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z1-mental', '1-2', 48, 1, 'mental'::public.pillar, 'Salut: bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Salut.” pe scurt.', '„Bună.” fără forțare.']::text[], 'A auzit salut și bună.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z1-resurse', '1-2', 48, 1, 'resurse'::public.pillar, 'Ușa deschisă pe scurt, salut', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['La ușă: deschideți pe scurt, cu adult.', '„Ușă. Salut.”']::text[], 'A privit ușa sau a auzit salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z1-social', '1-2', 48, 1, 'social'::public.pillar, 'Salutăm împreună pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Spuneți „Salut.” unul lângă altul pe scurt.', '„Împreună. Salut.” fără forțare.']::text[], 'A auzit salut lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z2-fizic', '1-2', 48, 2, 'fizic'::public.pillar, 'Pași până la ușă, salut', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți până la ușă pe scurt, cu adult.', '„Salut.” la ușă, fără grabă.']::text[], 'A mers până la ușă sau a auzit salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z2-mental', '1-2', 48, 2, 'mental'::public.pillar, 'Cine e la ușă?', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Cine e?” pe scurt.', '„Salut.” fără forțare.']::text[], 'A auzit cine e și salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z2-resurse', '1-2', 48, 2, 'resurse'::public.pillar, 'Haina pe cuier înainte de ieșire', 4, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['Dacă ieșiți: haina pe cuier sau pe scaun pe scurt.', '„Haină. Aici.”']::text[], 'A ajutat să așeze haina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s48-2-3-z2-social', '1-2', 48, 2, 'social'::public.pillar, 'Salut mamei sau tatălui', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Bună, mama.” sau „Bună, tata.” pe scurt.', 'Fără forțare; el poate doar privi.']::text[], 'A auzit salutul sau a încercat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z3-fizic', '1-2', 48, 3, 'fizic'::public.pillar, 'Mâna flutură: la revedere', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Fluturați mâna pe scurt: „La revedere.” cu adult.', '10–15 de secunde, fără forțare.']::text[], 'A fluturat mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z3-mental', '1-2', 48, 3, 'mental'::public.pillar, 'La revedere pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„La revedere.” pe scurt.', '„Pa.” fără forțare.']::text[], 'A auzit la revedere.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z3-resurse', '1-2', 48, 3, 'resurse'::public.pillar, 'Ușa închisă după la revedere', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Închideți ușa pe scurt, cu adult.', '„Ușă. Gata.”']::text[], 'A privit ușa sau a ajutat pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z3-social', '1-2', 48, 3, 'social'::public.pillar, 'La revedere împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți la revedere pe scurt unul lângă altul.', '„Împreună. La revedere.” fără forțare.']::text[], 'A făcut gestul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z4-fizic', '1-2', 48, 4, 'fizic'::public.pillar, 'Salut, apoi câțiva pași', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Salut.” pe scurt, apoi câțiva pași în casă, cu adult.', 'Fără grabă.']::text[], 'A auzit salut sau a mers pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z4-mental', '1-2', 48, 4, 'mental'::public.pillar, 'Salut și la revedere', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Salut.” pe scurt.', '„La revedere.” fără grabă.']::text[], 'A auzit salut și la revedere.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s48-2-3-z4-resurse', '1-2', 48, 4, 'resurse'::public.pillar, 'Pantofii lângă ușă la salut', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă pe scurt.', '„Pantofi. Aici.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z4-social', '1-2', 48, 4, 'social'::public.pillar, 'Salut pe rând pe scurt', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi spuneți „Salut.” pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a spus salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z5-fizic', '1-2', 48, 5, 'fizic'::public.pillar, 'La revedere la fereastră pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['La fereastră: fluturați mâna pe scurt, cu adult.', '„La revedere.” 10–20 de secunde.']::text[], 'A fluturat mâna sau a privit pe fereastră.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z5-mental', '1-2', 48, 5, 'mental'::public.pillar, 'Aici și acolo: salut', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați locul vostru: „Aici. Salut.”', 'Arătați afară: „Acolo.” fără forțare.']::text[], 'A auzit aici, acolo și salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z5-resurse', '1-2', 48, 5, 'resurse'::public.pillar, 'Perdeaua trasă după la revedere', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Trageți perdeaua pe scurt, cu adult.', '„Perdea. Gata.”']::text[], 'A ajutat la perdea sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z5-social', '1-2', 48, 5, 'social'::public.pillar, 'La revedere pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi faceți la revedere pe scurt.', '„Acum tu.” Așteptați fără forțare.']::text[], 'A auzit rândul sau a făcut gestul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z6-fizic', '1-2', 48, 6, 'fizic'::public.pillar, 'Salut oaspetelui pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă e cineva: ridicați mâna „Salut.” pe scurt, cu adult.', 'Dacă nu: practicați la ușă, fără forțare.']::text[], 'A ridicat mâna sau a auzit salut.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s48-2-3-z6-mental', '1-2', 48, 6, 'mental'::public.pillar, 'Mulțumesc pe scurt', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Mulțumesc.” pe scurt.', 'Fără grabă, fără forțare.']::text[], 'A auzit mulțumesc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z6-resurse', '1-2', 48, 6, 'resurse'::public.pillar, 'Haina pe cuier după oaspete', 4, 'A'::public.completion_mode, ARRAY['haină']::text[], ARRAY['Dacă ați fost afară sau a venit cineva: haina pe cuier.', '„Haină. La loc.”']::text[], 'A ajutat să pună haina la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z6-social', '1-2', 48, 6, 'social'::public.pillar, 'Salut și mulțumesc împreună', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Salut.” apoi „Mulțumesc.” pe scurt, unul lângă altul.', '„Împreună.” fără forțare.']::text[], 'A auzit salut și mulțumesc lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z7-fizic', '1-2', 48, 7, 'fizic'::public.pillar, 'Plimbare liberă, salut la final', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează direcția în casă pe scurt, cu adult.', 'La final: un salut scurt dacă vrea.']::text[], 'A mers liber pe scurt în casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z7-mental', '1-2', 48, 7, 'mental'::public.pillar, 'Carte: salut și la revedere', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați oameni care se salută dacă e clar: „Salut.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z7-resurse', '1-2', 48, 7, 'resurse'::public.pillar, 'Haina și pantofii la loc', 4, 'A'::public.completion_mode, ARRAY['haină', 'pantofi']::text[], ARRAY['Puneți pantofii lângă ușă, haina pe cuier dacă e.', '„La loc. Gata.”']::text[], 'A ajutat să pună cel puțin un lucru la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere'),
('s48-2-3-z7-social', '1-2', 48, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Salut și la revedere')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
