insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s49-2-3-z1-fizic', '1-2', 49, 1, 'fizic'::public.pillar, 'Alegem mingea favorită pe scurt', 5, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['El alege mingea dacă vrea; țineți-o pe scurt, cu adult.', '„Minge. Favorită.” fără grabă.']::text[], 'A atins sau a ținut mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z1-mental', '1-2', 49, 1, 'mental'::public.pillar, 'Prima favorită: minge', 3, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Arătați mingea: „Minge.”', '„Una. Favorită.” pe scurt.']::text[], 'A privit mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z1-resurse', '1-2', 49, 1, 'resurse'::public.pillar, 'Mingea pe masă, aleasă', 4, 'A'::public.completion_mode, ARRAY['minge']::text[], ARRAY['Așezați mingea pe masă pe scurt.', '„Aici. Aleasă.”']::text[], 'A ajutat să așeze mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z1-social', '1-2', 49, 1, 'social'::public.pillar, 'Arătăm mingea favorită adultului', 3, 'A'::public.completion_mode, ARRAY['minge']::text[], ARRAY['Arătați mingea: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z2-fizic', '1-2', 49, 2, 'fizic'::public.pillar, 'Alegem cartea iubită: pagina lui', 5, 'A'::public.completion_mode, ARRAY['carte preferată']::text[], ARRAY['El alege cartea dacă vrea; întoarce o pagină, cu adult.', '„Carte. Favorită.” pe scurt.']::text[], 'A ales sau a întors pagina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z2-mental', '1-2', 49, 2, 'mental'::public.pillar, 'A doua favorită: carte', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Arătați cartea: „Carte.”', '„Două. Favorită.” pe scurt.']::text[], 'A privit cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z2-resurse', '1-2', 49, 2, 'resurse'::public.pillar, 'Cartea pe raft, aleasă', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Puneți cartea pe raft pe scurt.', '„Carte. La loc.”']::text[], 'A ajutat să pună cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s49-2-3-z2-social', '1-2', 49, 2, 'social'::public.pillar, 'Citim favorita împreună din nou', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Stați cu cartea lângă adult pe scurt.', '„Împreună. Din nou.” fără forțare.']::text[], 'A șezut lângă voi cu cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z3-fizic', '1-2', 49, 3, 'fizic'::public.pillar, 'A treia favorită: dans pe loc', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați corpul stânga-dreapta pe scurt, cu adult.', '„Dans. Favorit.” 15–20 de secunde.']::text[], 'A balansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z3-mental', '1-2', 49, 3, 'mental'::public.pillar, 'Trei favorite: unu, doi, trei', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Unu. Două. Trei.” pe scurt.', '„Favorite.” fără forțare.']::text[], 'A auzit unu, doi, trei.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z3-resurse', '1-2', 49, 3, 'resurse'::public.pillar, 'Spațiu liber pentru dansul ales', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți 1–2 obiecte la loc pe scurt.', '„La loc. Liber.”']::text[], 'A ajutat să elibereze spațiul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z3-social', '1-2', 49, 3, 'social'::public.pillar, 'Dansăm din nou pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi balansați pe scurt. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A dansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z4-fizic', '1-2', 49, 4, 'fizic'::public.pillar, 'Repetăm mingea: dat pe scurt', 5, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Dați mingea pe scurt o dată, cu adult.', '„Din nou. Minge.” fără grabă.']::text[], 'A atins sau a dat mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z4-mental', '1-2', 49, 4, 'mental'::public.pillar, 'Ne amintim: minge din nou', 3, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Arătați mingea: „Minge.”', '„Din nou.” pe scurt.']::text[], 'A privit mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s49-2-3-z4-resurse', '1-2', 49, 4, 'resurse'::public.pillar, 'Mingea în cutie din nou', 4, 'A'::public.completion_mode, ARRAY['minge', 'cutie']::text[], ARRAY['Puneți mingea în cutie pe scurt.', '„La loc. În cutie.”']::text[], 'A ajutat să pună mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z4-social', '1-2', 49, 4, 'social'::public.pillar, 'Mingea pe rând, ca înainte', 4, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Voi dați. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z5-fizic', '1-2', 49, 5, 'fizic'::public.pillar, 'Trei obiecte favorite pe masă', 5, 'A'::public.completion_mode, ARRAY['3 obiecte cunoscute']::text[], ARRAY['Așezați trei obiecte pe masă pe scurt.', 'El atinge unul: „Uite.” fără grabă.']::text[], 'A atins cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z5-mental', '1-2', 49, 5, 'mental'::public.pillar, 'Alege una din trei', 3, 'A'::public.completion_mode, ARRAY['3 obiecte']::text[], ARRAY['Arătați cele trei: „Una?”', 'El arată sau atinge; „Asta.” pe scurt.']::text[], 'A arătat sau a atins unul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z5-resurse', '1-2', 49, 5, 'resurse'::public.pillar, 'Trei favorite la loc pe rând', 5, 'A'::public.completion_mode, ARRAY['3 obiecte', 'cutie sau raft']::text[], ARRAY['Puneți cele trei la loc pe rând.', '„La loc.” după fiecare.']::text[], 'A ajutat cu cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z5-social', '1-2', 49, 5, 'social'::public.pillar, 'Arătăm alegerea adultului', 3, 'A'::public.completion_mode, ARRAY['1 obiect ales']::text[], ARRAY['Duceți obiectul ales: „Uite.”', 'Stați pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z6-fizic', '1-2', 49, 6, 'fizic'::public.pillar, 'Repetăm pașii favoriți pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Faceți câțiva pași pe care îi iubește, cu adult.', '„Pași. Din nou.” fără grabă.']::text[], 'A făcut câțiva pași sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s49-2-3-z6-mental', '1-2', 49, 6, 'mental'::public.pillar, 'Ne amintim: pași și favorit', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Pași.” pe scurt.', '„Favorit.” fără forțare.']::text[], 'A auzit pași și favorit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z6-resurse', '1-2', 49, 6, 'resurse'::public.pillar, 'Pantofii la loc după pașii aleși', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['După pași: puneți pantofii lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z6-social', '1-2', 49, 6, 'social'::public.pillar, 'Pași favoriți împreună din nou', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți unul lângă altul pe scurt.', '„Împreună. Din nou.” fără forțare.']::text[], 'A mers lângă voi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z7-fizic', '1-2', 49, 7, 'fizic'::public.pillar, 'Plimbare liberă: alege un favorit', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează ritmul pe scurt, cu adult.', 'La final: un joc scurt pe care îl iubește, dacă vrea.']::text[], 'A mers liber; a ales sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z7-mental', '1-2', 49, 7, 'mental'::public.pillar, 'Carte: trei favorite în an', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', '„Trei. Favorite.” pe scurt, fără evaluare.']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z7-resurse', '1-2', 49, 7, 'resurse'::public.pillar, 'Favoritele pe raft la final', 4, 'A'::public.completion_mode, ARRAY['2–3 jucării sau cărți']::text[], ARRAY['Puneți obiectele folosite pe raft.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite'),
('s49-2-3-z7-social', '1-2', 49, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Repetăm 3 favorite')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s50-2-3-z1-fizic', '1-2', 50, 1, 'fizic'::public.pillar, 'Pași moi în casă pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți încet prin casă, cu adult.', '„Pași. Moale.” fără grabă.']::text[], 'A făcut câțiva pași moi sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z1-mental', '1-2', 50, 1, 'mental'::public.pillar, 'Liniște: casă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Casă.” pe scurt.', '„Liniște.” fără forțare.']::text[], 'A auzit casă și liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z1-resurse', '1-2', 50, 1, 'resurse'::public.pillar, 'Ușa închisă blând', 4, 'A'::public.completion_mode, ARRAY['ușă']::text[], ARRAY['Închideți ușa încet pe scurt, cu adult.', '„Ușă. Blând.”']::text[], 'A ajutat sau a privit ușa.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z1-social', '1-2', 50, 1, 'social'::public.pillar, 'Stați liniștiți unul lângă altul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe scurt unul lângă altul, fără grabă.', '„Împreună. Liniște.”']::text[], 'A stat lângă voi pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z2-fizic', '1-2', 50, 2, 'fizic'::public.pillar, 'Așezare blândă pe pernă', 4, 'A'::public.completion_mode, ARRAY['pernă']::text[], ARRAY['Așezați-vă pe pernă pe scurt, cu adult.', '„Jos. Blând.” fără grabă.']::text[], 'A șezut sau a atins perna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z2-mental', '1-2', 50, 2, 'mental'::public.pillar, 'Calm: pernă și corp', 3, 'A'::public.completion_mode, ARRAY['pernă']::text[], ARRAY['Arătați perna: „Pernă.”', '„Calm.” pe scurt.']::text[], 'A privit perna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z2-resurse', '1-2', 50, 2, 'resurse'::public.pillar, 'Perna la loc după așezare', 4, 'A'::public.completion_mode, ARRAY['pernă']::text[], ARRAY['Puneți perna la loc pe scurt.', '„Pernă. La loc.”']::text[], 'A ajutat să pună perna.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s50-2-3-z2-social', '1-2', 50, 2, 'social'::public.pillar, 'Pernă liniștită cu adultul', 3, 'A'::public.completion_mode, ARRAY['pernă']::text[], ARRAY['Stați pe pernă unul lângă altul pe scurt.', '„Împreună. Calm.” fără forțare.']::text[], 'A șezut sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z3-fizic', '1-2', 50, 3, 'fizic'::public.pillar, 'Carte pe genunchi, pe scurt', 5, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Țineți cartea pe genunchi pe scurt, cu adult.', '„Carte. Liniște.” fără grabă.']::text[], 'A ținut sau a atins cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z3-mental', '1-2', 50, 3, 'mental'::public.pillar, 'Imagini blânde din carte', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Arătați o imagine: „Uite.”', 'Un cuvânt scurt, fără grabă.']::text[], 'A privit imaginea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z3-resurse', '1-2', 50, 3, 'resurse'::public.pillar, 'Cartea pe raft după liniște', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Puneți cartea pe raft pe scurt.', '„Carte. La loc.”']::text[], 'A ajutat să pună cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z3-social', '1-2', 50, 3, 'social'::public.pillar, 'Citim liniștiți împreună', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Stați cu cartea lângă adult pe scurt.', '„Împreună. Carte.” fără forțare.']::text[], 'A șezut lângă voi cu cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z4-fizic', '1-2', 50, 4, 'fizic'::public.pillar, 'Mâini pe genunchi, respirație blândă', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Puneți mâinile pe genunchi pe scurt, cu adult.', '„Mâini. Jos.” 10–20 de secunde.']::text[], 'A pus mâinile sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z4-mental', '1-2', 50, 4, 'mental'::public.pillar, 'Liniște: mâini și corp', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Mâini.” pe scurt.', '„Liniște.” fără forțare.']::text[], 'A auzit mâini și liniște.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s50-2-3-z4-resurse', '1-2', 50, 4, 'resurse'::public.pillar, 'Lumina mică în cameră', 4, 'A'::public.completion_mode, ARRAY['lampă sau întrerupător']::text[], ARRAY['Aprindeți o lumină mică pe scurt, cu adult.', '„Lumină. Mică.”']::text[], 'A văzut sau a ajutat la lumină.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z4-social', '1-2', 50, 4, 'social'::public.pillar, 'Lumină mică împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Priviti lumina mică unul lângă altul pe scurt.', '„Împreună. Calm.” fără grabă.']::text[], 'A privit lângă voi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z5-fizic', '1-2', 50, 5, 'fizic'::public.pillar, 'Pași la geam, fără grabă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți încet până la geam, cu adult.', '„Geam. Liniște.” pe scurt.']::text[], 'A mers la geam sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z5-mental', '1-2', 50, 5, 'mental'::public.pillar, 'Afară e, în casă e calm', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Afară.”', 'Arătați camera: „Casă. Calm.”']::text[], 'A privit afară și în casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z5-resurse', '1-2', 50, 5, 'resurse'::public.pillar, 'Perdeaua trasă blând', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Trageți perdeaua pe scurt, cu adult.', '„Perdea. Blând.”']::text[], 'A ajutat cu perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z5-social', '1-2', 50, 5, 'social'::public.pillar, 'Privim geamul liniștiți', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam unul lângă altul pe scurt.', '„Împreună. Liniște.” fără forțare.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z6-fizic', '1-2', 50, 6, 'fizic'::public.pillar, 'Balans blând pe loc', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați corpul foarte încet pe scurt, cu adult.', '„Blând. Calm.” 10–20 de secunde.']::text[], 'A balansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s50-2-3-z6-mental', '1-2', 50, 6, 'mental'::public.pillar, 'Sunete mici în casă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Ascultați pe scurt: „Urechi.”', '„Liniște.” fără forțare.']::text[], 'A auzit sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z6-resurse', '1-2', 50, 6, 'resurse'::public.pillar, 'Jucăriile la loc, casă liniștită', 5, 'A'::public.completion_mode, ARRAY['2–3 jucării']::text[], ARRAY['Puneți 2–3 jucării la loc pe scurt.', '„La loc. Liniște.”']::text[], 'A ajutat cu cel puțin o jucărie.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z6-social', '1-2', 50, 6, 'social'::public.pillar, 'Casă liniștită împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe scurt unul lângă altul în cameră.', '„Împreună. Casă.” fără grabă.']::text[], 'A stat lângă voi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z7-fizic', '1-2', 50, 7, 'fizic'::public.pillar, 'Plimbare liberă blândă în casă', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează ritmul încet pe scurt, cu adult.', 'La final: așezare pe pernă dacă vrea.']::text[], 'A mers liber; s-a așezat sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z7-mental', '1-2', 50, 7, 'mental'::public.pillar, 'Carte: casă liniștită', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', '„Casă. Calm.” pe scurt.']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z7-resurse', '1-2', 50, 7, 'resurse'::public.pillar, 'Cartea și perna la loc', 4, 'A'::public.completion_mode, ARRAY['carte', 'pernă']::text[], ARRAY['Puneți cartea și perna la loc pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită'),
('s50-2-3-z7-social', '1-2', 50, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Casă liniștită')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s51-2-3-z1-fizic', '1-2', 51, 1, 'fizic'::public.pillar, 'Pași în curtea cunoscută', 6, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Ieșiți în curte; faceți câțiva pași, cu adult.', '„Curte. Cunoscută.” fără grabă.']::text[], 'A făcut câțiva pași afară sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z1-mental', '1-2', 51, 1, 'mental'::public.pillar, 'Curte: locul nostru', 3, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Arătați curtea: „Curte.”', '„Aici. Noastră.” pe scurt.']::text[], 'A privit curtea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z1-resurse', '1-2', 51, 1, 'resurse'::public.pillar, 'Pantofii la ușă înainte de curte', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Așezați pantofii lângă ușă pe scurt.', '„Pantofi. Aici.”']::text[], 'A ajutat să așeze pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z1-social', '1-2', 51, 1, 'social'::public.pillar, 'Ieșim în curte împreună', 3, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Mergeți unul lângă altul în curte pe scurt.', '„Împreună. Curte.” fără forțare.']::text[], 'A mers lângă voi afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z2-fizic', '1-2', 51, 2, 'fizic'::public.pillar, 'Mâna pe gardul cunoscut', 5, 'A'::public.completion_mode, ARRAY['gard sau poartă']::text[], ARRAY['Atingeți gardul sau poarta pe scurt, cu adult.', '„Gard. Cunoscut.” 10–20 de secunde.']::text[], 'A atins gardul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z2-mental', '1-2', 51, 2, 'mental'::public.pillar, 'Cuvânt nou: gard', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați gardul: „Gard.”', 'Repetați o dată: „Gard.” pe scurt.']::text[], 'A auzit și a privit gardul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z2-resurse', '1-2', 51, 2, 'resurse'::public.pillar, 'Mâna jos după gard', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['După atins: mâna jos pe scurt.', '„Mână. Jos.”']::text[], 'A coborât mâna sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s51-2-3-z2-social', '1-2', 51, 2, 'social'::public.pillar, 'Arătăm gardul adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați gardul: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z3-fizic', '1-2', 51, 3, 'fizic'::public.pillar, 'Pași până la copacul cunoscut', 6, 'A'::public.completion_mode, ARRAY['curte', 'copac sau plantă']::text[], ARRAY['Mergeți până la copac sau plantă, cu adult.', '„Copac. Cunoscut.” fără grabă.']::text[], 'A mers până la plantă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z3-mental', '1-2', 51, 3, 'mental'::public.pillar, 'Cuvânt nou: frunză', 3, 'A'::public.completion_mode, ARRAY['frunză sau plantă']::text[], ARRAY['Arătați frunza: „Frunză.”', '„Verde.” pe scurt dacă e clar.']::text[], 'A privit frunza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z3-resurse', '1-2', 51, 3, 'resurse'::public.pillar, 'O frunză ținută, apoi la loc', 4, 'A'::public.completion_mode, ARRAY['o frunză']::text[], ARRAY['Țineți o frunză pe scurt, apoi o puneți jos.', '„Frunză. La loc.”']::text[], 'A ținut sau a pus frunza.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z3-social', '1-2', 51, 3, 'social'::public.pillar, 'Privim copacul împreună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați lângă copac unul lângă altul pe scurt.', '„Împreună. Copac.” fără forțare.']::text[], 'A stat lângă voi la plantă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z4-fizic', '1-2', 51, 4, 'fizic'::public.pillar, 'Atingem pământul cunoscut', 5, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Atingeți pământul sau iarba pe scurt, cu adult.', '„Pământ. Aici.” fără grabă.']::text[], 'A atins pământul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z4-mental', '1-2', 51, 4, 'mental'::public.pillar, 'Cuvânt nou: pământ', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați pământul: „Pământ.”', '„Jos.” pe scurt.']::text[], 'A auzit pământ și jos.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s51-2-3-z4-resurse', '1-2', 51, 4, 'resurse'::public.pillar, 'Mâinile curate după pământ', 4, 'A'::public.completion_mode, ARRAY['apă sau șervețel']::text[], ARRAY['Ștergeți sau spălați mâinile pe scurt, cu adult.', '„Mâini. Curate.”']::text[], 'A ajutat la mâini.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z4-social', '1-2', 51, 4, 'social'::public.pillar, 'Atingem pământul pe rând', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Voi atingeți pe scurt. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A atins sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z5-fizic', '1-2', 51, 5, 'fizic'::public.pillar, 'Drumul scurt la poarta cunoscută', 6, 'A'::public.completion_mode, ARRAY['curte', 'poartă']::text[], ARRAY['Mergeți până la poartă pe scurt, cu adult.', '„Poartă. Cunoscută.” fără grabă.']::text[], 'A mers până la poartă sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z5-mental', '1-2', 51, 5, 'mental'::public.pillar, 'Cuvânt nou: poartă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați poarta: „Poartă.”', '„Acolo.” pe scurt.']::text[], 'A privit poarta.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z5-resurse', '1-2', 51, 5, 'resurse'::public.pillar, 'Mâna pe poartă, apoi jos', 4, 'A'::public.completion_mode, ARRAY['poartă']::text[], ARRAY['Atingeți poarta pe scurt, cu adult.', '„Poartă. Jos.” apoi mâna jos.']::text[], 'A atins poarta sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z5-social', '1-2', 51, 5, 'social'::public.pillar, 'Arătăm poarta adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați poarta: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z6-fizic', '1-2', 51, 6, 'fizic'::public.pillar, 'Urechi afară: sunete cunoscute', 5, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Stați în curte pe scurt; ascultați, cu adult.', '„Urechi. Afară.” fără grabă.']::text[], 'A ascultat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s51-2-3-z6-mental', '1-2', 51, 6, 'mental'::public.pillar, 'Cuvânt nou: pasăre sau mașină', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Dacă auziți: „Pasăre.” sau „Mașină.”', 'Un cuvânt scurt, fără forțare.']::text[], 'A auzit cuvântul numit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z6-resurse', '1-2', 51, 6, 'resurse'::public.pillar, 'Înapoi la ușă, pantofii la loc', 4, 'A'::public.completion_mode, ARRAY['pantofi']::text[], ARRAY['Intrați; puneți pantofii lângă ușă.', '„Pantofi. La loc.”']::text[], 'A ajutat să pună pantofii.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z6-social', '1-2', 51, 6, 'social'::public.pillar, 'Ascultăm afară împreună', 3, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['Stați unul lângă altul în curte pe scurt.', '„Împreună. Urechi.” fără forțare.']::text[], 'A stat lângă voi afară.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z7-fizic', '1-2', 51, 7, 'fizic'::public.pillar, 'Plimbare liberă în curtea cunoscută', 7, 'A'::public.completion_mode, ARRAY['curte']::text[], ARRAY['El dictează ritmul în curte pe scurt, cu adult.', 'La final: arătați un loc cunoscut dacă vrea.']::text[], 'A explorat liber pe scurt.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z7-mental', '1-2', 51, 7, 'mental'::public.pillar, 'Carte: curte și locuri', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', 'Arătați plantă, casă sau curte dacă e clar: „Curte.”']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z7-resurse', '1-2', 51, 7, 'resurse'::public.pillar, 'Haina și pantofii la loc', 4, 'A'::public.completion_mode, ARRAY['haină', 'pantofi']::text[], ARRAY['După curte: haina și pantofii la loc pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună cel puțin un lucru.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută'),
('s51-2-3-z7-social', '1-2', 51, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Curtea cunoscută')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s52-2-3-z1-fizic', '1-2', 52, 1, 'fizic'::public.pillar, 'Pași blânzi prin casă pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți încet prin casă, cu adult.', '„Pași. Blând.” fără grabă.']::text[], 'A făcut câțiva pași sau a mers lângă adult.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z1-mental', '1-2', 52, 1, 'mental'::public.pillar, 'Anul: blând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„An.” pe scurt.', '„Blând.” fără evaluare.']::text[], 'A auzit an și blând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z1-resurse', '1-2', 52, 1, 'resurse'::public.pillar, 'O jucărie pe masă, fără grabă', 4, 'A'::public.completion_mode, ARRAY['o jucărie']::text[], ARRAY['Așezați o jucărie pe masă pe scurt.', '„Aici. Blând.”']::text[], 'A ajutat să așeze jucăria.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z1-social', '1-2', 52, 1, 'social'::public.pillar, 'Stați blând unul lângă altul', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați pe scurt unul lângă altul.', '„Împreună. Blând.” fără forțare.']::text[], 'A stat lângă voi.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z2-fizic', '1-2', 52, 2, 'fizic'::public.pillar, 'Atingem trei locuri din casă', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Atingeți ușă, scaun, masă pe rând, cu adult.', '„Ușă. Scaun. Masă.” pe scurt.']::text[], 'A atins cel puțin un loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z2-mental', '1-2', 52, 2, 'mental'::public.pillar, 'Ne amintim casa', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați camera: „Casă.”', '„Ne amintim.” pe scurt, fără evaluare.']::text[], 'A privit camera.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z2-resurse', '1-2', 52, 2, 'resurse'::public.pillar, 'Trei lucruri la loc blând', 5, 'A'::public.completion_mode, ARRAY['2–3 obiecte']::text[], ARRAY['Puneți 2–3 obiecte la loc pe scurt.', '„La loc.” după fiecare, fără grabă.']::text[], 'A ajutat cu cel puțin un obiect.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s52-2-3-z2-social', '1-2', 52, 2, 'social'::public.pillar, 'Arătăm casa adultului', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați un loc din casă: „Uite.”', 'Adultul privește pe scurt, fără grabă.']::text[], 'A participat la arătat.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z3-fizic', '1-2', 52, 3, 'fizic'::public.pillar, 'Cartea anului: pagina lui', 5, 'A'::public.completion_mode, ARRAY['carte preferată']::text[], ARRAY['El alege cartea dacă vrea; întoarce o pagină, cu adult.', '„Carte. An.” pe scurt.']::text[], 'A ales sau a întors pagina.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z3-mental', '1-2', 52, 3, 'mental'::public.pillar, 'Imagini din an pe scurt', 3, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Arătați o imagine cunoscută: „Uite.”', 'Un cuvânt scurt, fără evaluare.']::text[], 'A privit imaginea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z3-resurse', '1-2', 52, 3, 'resurse'::public.pillar, 'Cartea pe raft la închidere', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Puneți cartea pe raft pe scurt.', '„Carte. La loc.”']::text[], 'A ajutat să pună cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z3-social', '1-2', 52, 3, 'social'::public.pillar, 'Citim blând împreună', 4, 'A'::public.completion_mode, ARRAY['carte']::text[], ARRAY['Stați cu cartea lângă adult pe scurt.', '„Împreună. Blând.” fără forțare.']::text[], 'A șezut lângă voi cu cartea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z4-fizic', '1-2', 52, 4, 'fizic'::public.pillar, 'Mingea blândă: dat pe scurt', 5, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Dați mingea pe scurt o dată, cu adult.', '„Minge. Blând.” fără grabă.']::text[], 'A atins sau a dat mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z4-mental', '1-2', 52, 4, 'mental'::public.pillar, 'Ne amintim: minge și rând', 3, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Arătați mingea: „Minge.”', '„Rând.” pe scurt, fără evaluare.']::text[], 'A auzit minge și rând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s52-2-3-z4-resurse', '1-2', 52, 4, 'resurse'::public.pillar, 'Mingea în cutie la final', 4, 'A'::public.completion_mode, ARRAY['minge', 'cutie']::text[], ARRAY['Puneți mingea în cutie pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună mingea.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z4-social', '1-2', 52, 4, 'social'::public.pillar, 'Mingea pe rând, blând', 4, 'A'::public.completion_mode, ARRAY['minge moale']::text[], ARRAY['Voi dați. „Acum tu.”', 'Așteptați fără forțare.']::text[], 'A încercat sau a privit rândul.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z5-fizic', '1-2', 52, 5, 'fizic'::public.pillar, 'Geamul: privim anul pe scurt', 5, 'A'::public.completion_mode, '{}'::text[], ARRAY['Mergeți la geam; atingeți sticla pe scurt, cu adult.', '„Geam. An.” fără grabă.']::text[], 'A atins geamul sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z5-mental', '1-2', 52, 5, 'mental'::public.pillar, 'Afară și în casă: gata blând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Arătați afară: „Afară.”', 'Arătați camera: „Casă. Blând.”']::text[], 'A privit afară și în casă.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z5-resurse', '1-2', 52, 5, 'resurse'::public.pillar, 'Perdeaua la loc blând', 4, 'A'::public.completion_mode, ARRAY['perdea']::text[], ARRAY['Trageți perdeaua pe scurt.', '„Perdea. La loc.”']::text[], 'A ajutat cu perdeaua.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z5-social', '1-2', 52, 5, 'social'::public.pillar, 'Privim geamul împreună la final', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Stați la geam unul lângă altul pe scurt.', '„Împreună. An.” fără evaluare.']::text[], 'A stat lângă voi la geam.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z6-fizic', '1-2', 52, 6, 'fizic'::public.pillar, 'Balans blând: anul se închide', 4, 'A'::public.completion_mode, '{}'::text[], ARRAY['Balanșați corpul încet pe scurt, cu adult.', '„Blând. Gata.” 10–20 de secunde.']::text[], 'A balansat sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s52-2-3-z6-mental', '1-2', 52, 6, 'mental'::public.pillar, 'Gata blând: fără notare', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Gata.” pe scurt.', '„Blând.” fără evaluare, fără forțare.']::text[], 'A auzit gata și blând.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z6-resurse', '1-2', 52, 6, 'resurse'::public.pillar, 'Favoritele pe raft, anul gata', 5, 'A'::public.completion_mode, ARRAY['2–3 jucării sau cărți']::text[], ARRAY['Puneți obiectele pe raft pe scurt.', '„La loc. An.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z6-social', '1-2', 52, 6, 'social'::public.pillar, 'Mulțumesc pe scurt, blând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Mulțumesc.” pe scurt.', 'Modelați voi; el imită dacă vrea, fără forțare.']::text[], 'A auzit sau a încercat mulțumesc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z7-fizic', '1-2', 52, 7, 'fizic'::public.pillar, 'Plimbare liberă: anul se închide', 6, 'A'::public.completion_mode, '{}'::text[], ARRAY['El dictează ritmul pe scurt, cu adult.', 'La final: un gest blând pe care îl iubește, dacă vrea.']::text[], 'A mers liber; a ales sau nu.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z7-mental', '1-2', 52, 7, 'mental'::public.pillar, 'Carte: anul se închide blând', 4, 'A'::public.completion_mode, ARRAY['carte cu imagini']::text[], ARRAY['El întoarce pagina.', '„An. Blând.” pe scurt, fără evaluare.']::text[], 'A întors pagina sau a privit.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z7-resurse', '1-2', 52, 7, 'resurse'::public.pillar, 'Totul la loc: an gata', 4, 'A'::public.completion_mode, ARRAY['2–3 obiecte']::text[], ARRAY['Puneți obiectele folosite la loc pe scurt.', '„La loc. Gata.”']::text[], 'A ajutat să pună la loc.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând'),
('s52-2-3-z7-social', '1-2', 52, 7, 'social'::public.pillar, 'Noapte bună', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['„Noapte bună.”', 'Lumină mică, fără grabă.']::text[], 'A auzit ritualul de noapte.', 'Vârsta 1–2: scurt, fără forțare; el poate refuza.', 'Anul se închide blând')
on conflict (id) do update set banda=excluded.banda, saptamana=excluded.saptamana, zi=excluded.zi, pilon=excluded.pilon, titlu=excluded.titlu, durata_min=excluded.durata_min, mod_default=excluded.mod_default, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana;
