-- PLAYFUL PILOT remap: invitation titles for S5–S7 L–D (84).
-- Does not insert new catalog rows; no other weeks/bands. Zero sounds.
update public.activities as a
set titlu = v.titlu
from (values
  ('s5-2-3-z1-fizic', 'Pași până la roșu'),
  ('s5-2-3-z1-mental', 'Uite: roșu'),
  ('s5-2-3-z1-resurse', 'Paharul colorat la loc'),
  ('s5-2-3-z1-social', 'Arătăm roșul împreună'),
  ('s5-2-3-z2-fizic', 'Căutăm două galbene'),
  ('s5-2-3-z2-mental', 'Galben — sau nu?'),
  ('s5-2-3-z2-resurse', 'În cutia galbenă'),
  ('s5-2-3-z2-social', 'Ține galbenul'),
  ('s5-2-3-z3-fizic', 'Atingem albastrul'),
  ('s5-2-3-z3-mental', 'Unde e albastru?'),
  ('s5-2-3-z3-resurse', 'Haina albastră pe cârlig'),
  ('s5-2-3-z3-social', 'Uite albastru'),
  ('s5-2-3-z4-fizic', 'Dans lângă verde'),
  ('s5-2-3-z4-mental', 'Verde pe frunză'),
  ('s5-2-3-z4-resurse', 'Dăm apă plantei'),
  ('s5-2-3-z4-social', 'Privim verdele'),
  ('s5-2-3-z5-fizic', 'Cărăm culoarea'),
  ('s5-2-3-z5-mental', 'Trei culori pe masă'),
  ('s5-2-3-z5-resurse', 'Culorile la loc'),
  ('s5-2-3-z5-social', 'Pe care culoare?'),
  ('s5-2-3-z6-fizic', 'Culori afară, pe scurt'),
  ('s5-2-3-z6-mental', 'Cer albastru — sau nor?'),
  ('s5-2-3-z6-resurse', 'O frunză colorată'),
  ('s5-2-3-z6-social', 'Tu atingi, eu numesc'),
  ('s5-2-3-z7-fizic', 'Plimbare liberă cu culori'),
  ('s5-2-3-z7-mental', 'Cartea cu culori'),
  ('s5-2-3-z7-resurse', 'Jucăriile colorate la loc'),
  ('s5-2-3-z7-social', 'Noapte bună'),
  ('s6-2-3-z1-fizic', 'Brațele: sus, jos'),
  ('s6-2-3-z1-mental', 'Sus pe raft, jos pe podea'),
  ('s6-2-3-z1-resurse', 'Jucăria jos, la loc'),
  ('s6-2-3-z1-social', 'Ridicăm brațele împreună'),
  ('s6-2-3-z2-fizic', 'Sus pe scaun (cu adult)'),
  ('s6-2-3-z2-mental', 'Tu ești sus pe scaun'),
  ('s6-2-3-z2-resurse', 'Farfuria sus pe masă'),
  ('s6-2-3-z2-social', 'Mâna pe treaptă'),
  ('s6-2-3-z3-fizic', 'O treaptă sus, una jos'),
  ('s6-2-3-z3-mental', 'Mingea sus, mingea jos'),
  ('s6-2-3-z3-resurse', 'Șosetele jos în sertar'),
  ('s6-2-3-z3-social', 'Acum tu urci'),
  ('s6-2-3-z4-fizic', 'Jos ghemuit, sus drept'),
  ('s6-2-3-z4-mental', 'Unde e? Sus sau jos?'),
  ('s6-2-3-z4-resurse', 'Cartea sus pe raft'),
  ('s6-2-3-z4-social', 'Sus? Te ridic'),
  ('s6-2-3-z5-fizic', 'Săritură mică în sus'),
  ('s6-2-3-z5-mental', 'Capul sus, picioarele jos'),
  ('s6-2-3-z5-resurse', 'Paharul jos la chiuvetă'),
  ('s6-2-3-z5-social', 'Sus la fereastră'),
  ('s6-2-3-z6-fizic', 'Bordură: sus și jos'),
  ('s6-2-3-z6-mental', 'Frunză sus, frunză jos'),
  ('s6-2-3-z6-resurse', 'Găleata jos pe iarbă'),
  ('s6-2-3-z6-social', 'Eu sus-jos, tu pe lângă'),
  ('s6-2-3-z7-fizic', 'Plimbare liberă'),
  ('s6-2-3-z7-mental', 'Cartea — tu întorci'),
  ('s6-2-3-z7-resurse', 'Haina sus pe cârlig'),
  ('s6-2-3-z7-social', 'Noapte bună'),
  ('s7-2-3-z1-fizic', 'Pași până la ușă'),
  ('s7-2-3-z1-mental', 'Înăuntru — sau afară?'),
  ('s7-2-3-z1-resurse', 'Papucii la ușă'),
  ('s7-2-3-z1-social', 'Deschidem ușa împreună'),
  ('s7-2-3-z2-fizic', 'În curte, două minute'),
  ('s7-2-3-z2-mental', 'Aer afară, aer în casă'),
  ('s7-2-3-z2-resurse', 'Haina după afară'),
  ('s7-2-3-z2-social', 'Bună, afară'),
  ('s7-2-3-z3-fizic', 'Pași înăuntru'),
  ('s7-2-3-z3-mental', 'Unde e? Înăuntru'),
  ('s7-2-3-z3-resurse', 'La loc, în casă'),
  ('s7-2-3-z3-social', 'La revedere, curte'),
  ('s7-2-3-z4-fizic', 'Afară și înapoi'),
  ('s7-2-3-z4-mental', 'Jucăria: afară sau înăuntru?'),
  ('s7-2-3-z4-resurse', 'Jucăria înăuntru, la loc'),
  ('s7-2-3-z4-social', 'Mână pe prag'),
  ('s7-2-3-z5-fizic', 'Dans, apoi la ușă'),
  ('s7-2-3-z5-mental', 'Noi înăuntru, curtea afară'),
  ('s7-2-3-z5-resurse', 'Ușa închisă'),
  ('s7-2-3-z5-social', 'Uite afară'),
  ('s7-2-3-z6-fizic', 'Plimbare scurtă în curte'),
  ('s7-2-3-z6-mental', 'Lumină afară, umbră în casă'),
  ('s7-2-3-z6-resurse', 'Piatra rămâne afară'),
  ('s7-2-3-z6-social', 'Pe prag, unul lângă altul'),
  ('s7-2-3-z7-fizic', 'Plimbare liberă'),
  ('s7-2-3-z7-mental', 'Carte pe canapea, înăuntru'),
  ('s7-2-3-z7-resurse', 'Totul de pe prag la loc'),
  ('s7-2-3-z7-social', 'Noapte bună în casă')
) as v(id, titlu)
where a.id = v.id;
