-- PLAYFUL PILOT remap: invitation titles for S1–S2 L–D + S3 L–J (72).
-- S3 V–D titles stay as lock #32. Does not insert new catalog rows. Zero sounds.
update public.activities as a
set titlu = v.titlu
from (values
  ('s1-2-3-z1-fizic', 'Pași în curte'),
  ('s1-2-3-z1-mental', 'Uite copacul'),
  ('s1-2-3-z1-resurse', 'Piatra mea'),
  ('s1-2-3-z1-social', 'Salut'),
  ('s1-2-3-z2-fizic', 'Sărituri mici'),
  ('s1-2-3-z2-mental', 'Cartea scurt'),
  ('s1-2-3-z2-resurse', 'Paharul gol — sau plin?'),
  ('s1-2-3-z2-social', 'Mulțumesc'),
  ('s1-2-3-z3-fizic', 'Dans scurt'),
  ('s1-2-3-z3-mental', 'Unde e mingea?'),
  ('s1-2-3-z3-resurse', 'Trei jucării la loc'),
  ('s1-2-3-z3-social', 'Îmbrățișare, dacă vrea'),
  ('s1-2-3-z4-fizic', 'Cărăm ceva ușor'),
  ('s1-2-3-z4-mental', 'Cald — sau rece?'),
  ('s1-2-3-z4-resurse', 'Apa la loc'),
  ('s1-2-3-z4-social', 'Pe rând'),
  ('s1-2-3-z5-fizic', 'Trepte sus, trepte jos'),
  ('s1-2-3-z5-mental', 'Trei lucruri din cameră'),
  ('s1-2-3-z5-resurse', 'Lumina aprinsă — sau stinsă?'),
  ('s1-2-3-z5-social', 'Vizită scurtă'),
  ('s1-2-3-z6-fizic', 'Nisip, iarbă, pietre'),
  ('s1-2-3-z6-mental', 'Pasăre — sau mașină?'),
  ('s1-2-3-z6-resurse', 'Udăm o plantă'),
  ('s1-2-3-z6-social', 'Eu în curte, tu pe lângă'),
  ('s1-2-3-z7-fizic', 'Plimbare liberă'),
  ('s1-2-3-z7-mental', 'Cartea preferată'),
  ('s1-2-3-z7-resurse', 'Hainele la loc'),
  ('s1-2-3-z7-social', 'Noapte bună'),
  ('s2-2-3-z1-fizic', 'Pași până la robinet'),
  ('s2-2-3-z1-mental', 'Uite apa'),
  ('s2-2-3-z1-resurse', 'Paharul cu apă'),
  ('s2-2-3-z1-social', 'Cer apă'),
  ('s2-2-3-z2-fizic', 'Turnăm cu grijă'),
  ('s2-2-3-z2-mental', 'Gol — sau plin?'),
  ('s2-2-3-z2-resurse', 'Udăm planta'),
  ('s2-2-3-z2-social', 'Beau cu tine'),
  ('s2-2-3-z3-fizic', 'Stropi pe mână'),
  ('s2-2-3-z3-mental', 'Unde e paharul?'),
  ('s2-2-3-z3-resurse', 'Ștergem apa'),
  ('s2-2-3-z3-social', 'Mulțumesc pentru apă'),
  ('s2-2-3-z4-fizic', 'Cărăm paharul gol'),
  ('s2-2-3-z4-mental', 'Apă — sau uscat?'),
  ('s2-2-3-z4-resurse', 'Paharul la loc'),
  ('s2-2-3-z4-social', 'O înghițitură pe rând'),
  ('s2-2-3-z5-fizic', 'Stropi pe geam'),
  ('s2-2-3-z5-mental', 'Auzim apa'),
  ('s2-2-3-z5-resurse', 'Oprim robinetul'),
  ('s2-2-3-z5-social', 'Uite apa'),
  ('s2-2-3-z6-fizic', 'Băltoaca, pe scurt'),
  ('s2-2-3-z6-mental', 'Nor — sau soare?'),
  ('s2-2-3-z6-resurse', 'Două frunze ude'),
  ('s2-2-3-z6-social', 'Lângă apă'),
  ('s2-2-3-z7-fizic', 'Plimbare liberă'),
  ('s2-2-3-z7-mental', 'Cartea cu apa'),
  ('s2-2-3-z7-resurse', 'Prosopul la loc'),
  ('s2-2-3-z7-social', 'Noapte bună'),
  ('s3-2-3-z1-fizic', 'Pași care se aud'),
  ('s3-2-3-z1-mental', 'Liniște scurtă'),
  ('s3-2-3-z1-resurse', 'Jucăria sonoră la loc'),
  ('s3-2-3-z1-social', 'Spunem numele'),
  ('s3-2-3-z2-fizic', 'Bătăi din palme'),
  ('s3-2-3-z2-mental', 'Unde e sunetul?'),
  ('s3-2-3-z2-resurse', 'Jucăria la loc'),
  ('s3-2-3-z2-social', 'Ascultăm'),
  ('s3-2-3-z3-fizic', 'Dans scurt'),
  ('s3-2-3-z3-mental', 'Tare — sau încet?'),
  ('s3-2-3-z3-resurse', 'Gata cu cântatul'),
  ('s3-2-3-z3-social', 'Cântăm puțin'),
  ('s3-2-3-z4-fizic', 'Sărituri pe bătăi'),
  ('s3-2-3-z4-mental', 'Pasăre — sau mașină?'),
  ('s3-2-3-z4-resurse', 'Ușa închisă încet'),
  ('s3-2-3-z4-social', 'Rândul tău')
) as v(id, titlu)
where a.id = v.id;
