-- Official activitate schema (Cristina): slug id + structured RO fields.
-- Replaces UUID placeholder catalog. Completions are wiped (V1, no prod data).

truncate public.completions;
alter table public.completions drop constraint if exists completions_activity_id_fkey;
drop table if exists public.activities cascade;

create table public.activities (
  id text primary key,
  banda text not null default '2-3',
  saptamana integer not null check (saptamana between 1 and 52),
  zi integer not null check (zi between 1 and 7),
  pilon public.pillar not null,
  titlu text not null,
  durata_min integer not null check (durata_min between 2 and 15),
  mod_default public.completion_mode not null default 'A',
  materiale text[] not null default '{}',
  pasi text[] not null default '{}',
  gata_cand text not null,
  nota text,
  tema_saptamana text not null,
  created_at timestamptz not null default now(),
  unique (saptamana, zi, pilon, banda)
);

create index activities_week_day_band_idx
  on public.activities (saptamana, zi, banda);

alter table public.completions
  alter column activity_id type text using activity_id::text;

alter table public.completions
  add constraint completions_activity_id_fkey
  foreign key (activity_id) references public.activities (id) on delete cascade;

alter table public.activities enable row level security;

create policy activities_select_authenticated
  on public.activities for select to authenticated
  using (true);

insert into public.activities (
  id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default,
  materiale, pasi, gata_cand, nota, tema_saptamana
) values
(
    's1-2-3-z1-fizic',
    '2-3',
    1,
    1,
    'fizic'::public.pillar,
    'Pași în curte',
    5,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['Ieșiți în curte.', 'Mergeți împreună 10–20 de pași.', 'Numărați cu voce tare: unu, doi…']::text[],
    'A făcut câțiva pași afară fără forțare.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z1-mental',
    '2-3',
    1,
    1,
    'mental'::public.pillar,
    'Uite copacul',
    4,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['Arătați un copac/plantă.', 'Ziceți: Copac. Verde. Sus.', 'Lăsați-l să arate și el.']::text[],
    'A privit / arătat obiectul numit.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z1-resurse',
    '2-3',
    1,
    1,
    'resurse'::public.pillar,
    'Piatra mea',
    3,
    'A'::public.completion_mode,
    ARRAY['o piatră/frunză']::text[],
    ARRAY['Alegeți împreună o piatră sau frunză.', 'Ziceți: Asta e a ta să o ții puțin.', 'La final o puneți la loc.']::text[],
    'A ținut obiectul și l-a pus la loc.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z1-social',
    '2-3',
    1,
    1,
    'social'::public.pillar,
    'Salut mamei/tatălui',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Practicați Bună, mama/tata! cu zâmbet.', 'Răspundeți cald când încearcă.']::text[],
    'A făcut un gest/salut (sau a încercat).',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z2-fizic',
    '2-3',
    1,
    2,
    'fizic'::public.pillar,
    'Sărițuri mici',
    4,
    'A'::public.completion_mode,
    ARRAY['podea/curte']::text[],
    ARRAY['Țineți-i mâinile.', '2–5 sărituri ușoare.', 'Stop când e gata.']::text[],
    'A sărit sau a încercat de câteva ori.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z2-mental',
    '2-3',
    1,
    2,
    'mental'::public.pillar,
    'Carte 5 minute',
    5,
    'A'::public.completion_mode,
    ARRAY['o carte cartonată']::text[],
    ARRAY['Stați împreună.', 'Arătați 3 imagini: Minge. Apă. Câine.', 'Nu forțați să stea mai mult.']::text[],
    'A rămas la 2–3 pagini.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z2-resurse',
    '2-3',
    1,
    2,
    'resurse'::public.pillar,
    'Paharul gol / plin',
    4,
    'A'::public.completion_mode,
    ARRAY['pahar, apă']::text[],
    ARRAY['Arătați pahar gol, apoi turnați puțin.', 'Gol. Plin.', 'El toarnă cu ajutor.']::text[],
    'A văzut / ajutat la turnat.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z2-social',
    '2-3',
    1,
    2,
    'social'::public.pillar,
    'Mulțumesc',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['După o gustare: Mulțumesc.', 'Modelați voi; el imită dacă vrea.']::text[],
    'A auzit și/sau a încercat cuvântul.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z3-fizic',
    '2-3',
    1,
    3,
    'fizic'::public.pillar,
    'Dans 2 minute',
    3,
    'A'::public.completion_mode,
    ARRAY['muzică opțională']::text[],
    ARRAY['Puneți o melodie scurtă sau bateți din palme.', 'Mișcați-vă împreună.']::text[],
    'S-a mișcat pe ritm măcar 30 sec.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z3-mental',
    '2-3',
    1,
    3,
    'mental'::public.pillar,
    'Unde e mingea?',
    4,
    'A'::public.completion_mode,
    ARRAY['minge']::text[],
    ARRAY['Ascundeți mingea la vedere (sub pernă pe jumătate).', 'Unde e mingea?', 'Bucurați-vă când o găsește.']::text[],
    'A căutat / găsit mingea.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z3-resurse',
    '2-3',
    1,
    3,
    'resurse'::public.pillar,
    'Strângem 3 jucării',
    5,
    'A'::public.completion_mode,
    ARRAY['jucării']::text[],
    ARRAY['Alegeți 3 jucării de pe jos.', 'Una. Două. Trei. Gata.', 'Puneți-le în cutie împreună.']::text[],
    'A ajutat la cel puțin 1 jucărie în cutie.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z3-social',
    '2-3',
    1,
    3,
    'social'::public.pillar,
    'Îmbrățișare la cerere',
    2,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Oferiți îmbrățișare; nu forțați.', 'Vrei îmbrățișare?']::text[],
    'A acceptat sau a refuzat clar (oricare e ok).',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z4-fizic',
    '2-3',
    1,
    4,
    'fizic'::public.pillar,
    'Cărăm ceva ușor',
    4,
    'A'::public.completion_mode,
    ARRAY['găleată/jucărie']::text[],
    ARRAY['Dați-i ceva ușor de cărat 5–10 pași.', 'Tu porți asta.']::text[],
    'A cărat obiectul câțiva pași.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z4-mental',
    '2-3',
    1,
    4,
    'mental'::public.pillar,
    'Cald / rece',
    3,
    'A'::public.completion_mode,
    ARRAY['apă sau mână']::text[],
    ARRAY['Atingeți ceva cald-safe și ceva rece.', 'Cald. Rece.']::text[],
    'A reacționat la diferență.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z4-resurse',
    '2-3',
    1,
    4,
    'resurse'::public.pillar,
    'Apa e importantă',
    3,
    'A'::public.completion_mode,
    ARRAY['pahar apă']::text[],
    ARRAY['Beți împreună apă.', 'Beau apă. E bine.']::text[],
    'A băut sau a gustat apă.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z4-social',
    '2-3',
    1,
    4,
    'social'::public.pillar,
    'Joacă de-a rândul',
    5,
    'A'::public.completion_mode,
    ARRAY['minge']::text[],
    ARRAY['Dați mingea: Acum tu. Acum eu.', '2–4 schimburi.']::text[],
    'A dat / primit mingea măcar o dată.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z5-fizic',
    '2-3',
    1,
    5,
    'fizic'::public.pillar,
    'Urcăm / coborâm trepte',
    5,
    'A'::public.completion_mode,
    ARRAY['1–3 trepte safe']::text[],
    ARRAY['Țineți mâna.', 'Una-două trepte.', 'Stop la oboseală.']::text[],
    'A urcat sau coborât cu ajutor.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z5-mental',
    '2-3',
    1,
    5,
    'mental'::public.pillar,
    'Numește 3 lucruri din cameră',
    4,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Arătați: Usa. Fereastra. Scaun.', 'El arată dacă vrea.']::text[],
    'A privit cele 3 obiecte numite.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z5-resurse',
    '2-3',
    1,
    5,
    'resurse'::public.pillar,
    'Lumina aprins / stins',
    3,
    'A'::public.completion_mode,
    ARRAY['întrerupător']::text[],
    ARRAY['Aprindeți/stingeți cu ajutorul lui (safe).', 'Aprins. Stins.', 'Nu lăsați nesupravegheat.']::text[],
    'A văzut / apăsat cu ajutor.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z5-social',
    '2-3',
    1,
    5,
    'social'::public.pillar,
    'Vizită scurtă / telefon bunica',
    5,
    'A'::public.completion_mode,
    ARRAY['opțional apel']::text[],
    ARRAY['Salut scurt unei persoane dragi.', '2 minute max.']::text[],
    'A participat la salut (vizual/audio).',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z6-fizic',
    '2-3',
    1,
    6,
    'fizic'::public.pillar,
    'Nisip / iarbă / pietre',
    6,
    'A'::public.completion_mode,
    ARRAY['curte']::text[],
    ARRAY['Descălțați dacă e safe sau atingeți texturi.', 'Moale. Aspru.']::text[],
    'A explorat 2 texturi.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z6-mental',
    '2-3',
    1,
    6,
    'mental'::public.pillar,
    'Sunete: pasăre / mașină',
    4,
    'A'::public.completion_mode,
    ARRAY['afară']::text[],
    ARRAY['Ascultați 20 sec.', 'Auzi? Pasăre. Mașină.']::text[],
    'A orientat atenția spre sunet.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z6-resurse',
    '2-3',
    1,
    6,
    'resurse'::public.pillar,
    'Udăm o plantă',
    5,
    'A'::public.completion_mode,
    ARRAY['apă, plantă']::text[],
    ARRAY['Turnați puțin împreună.', 'Dăm apă plantei.']::text[],
    'A ajutat la udat.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z6-social',
    '2-3',
    1,
    6,
    'social'::public.pillar,
    'Joacă paralel cu adultul',
    8,
    'A'::public.completion_mode,
    ARRAY['2 seturi jucării']::text[],
    ARRAY['Stați lângă el, jucați-vă cu ale voastre.', 'Comentați ce face el, fără a prelua jocul.']::text[],
    'A jucat lângă voi 3–5 min.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z7-fizic',
    '2-3',
    1,
    7,
    'fizic'::public.pillar,
    'Plimbare liberă scurtă',
    8,
    'A'::public.completion_mode,
    ARRAY['curte/parc']::text[],
    ARRAY['El dictează ritmul.', 'Voi doar supravegheați și numiți ce arată.']::text[],
    'A explorat liber >=5 min.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z7-mental',
    '2-3',
    1,
    7,
    'mental'::public.pillar,
    'Cartea preferată (repetare)',
    5,
    'A'::public.completion_mode,
    ARRAY['carte']::text[],
    ARRAY['Aceeași carte ca în săptămână.', 'Lăsați-l să întoarcă pagina.']::text[],
    'A ales / rămas la carte scurt.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z7-resurse',
    '2-3',
    1,
    7,
    'resurse'::public.pillar,
    'Punem hainele la loc',
    4,
    'A'::public.completion_mode,
    ARRAY['haină']::text[],
    ARRAY['După ieșire: haina pe cârlig/scaun.', 'La loc.']::text[],
    'A ajutat să pună haina undeva.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  ),
(
    's1-2-3-z7-social',
    '2-3',
    1,
    7,
    'social'::public.pillar,
    'Ziua e gata — pup de noapte',
    3,
    'A'::public.completion_mode,
    '{}'::text[],
    ARRAY['Ritual scurt: Noapte bună.', 'Lumină mică, calm.']::text[],
    'A participat la ritualul de somn.',
    'Vârsta 2–3: scurt, fără forțare; el poate refuza.',
    'Casa și curtea'
  )
on conflict (id) do update set
  banda = excluded.banda,
  saptamana = excluded.saptamana,
  zi = excluded.zi,
  pilon = excluded.pilon,
  titlu = excluded.titlu,
  durata_min = excluded.durata_min,
  mod_default = excluded.mod_default,
  materiale = excluded.materiale,
  pasi = excluded.pasi,
  gata_cand = excluded.gata_cand,
  nota = excluded.nota,
  tema_saptamana = excluded.tema_saptamana;
