-- PLAYFUL PILOT remap: invitation titles for S3 V–D + S4;
-- revert S14 V–D + S15 to pre-pilot wording (from #28).
-- Does not insert new catalog rows; no other weeks/bands.
update public.activities as a
set titlu = v.titlu
from (values
  ('s3-2-3-z5-fizic', 'Hai pe vârfuri'),
  ('s3-2-3-z5-mental', 'Uite 3 sunete din casă'),
  ('s3-2-3-z5-resurse', 'Hai telefonul pe liniște'),
  ('s3-2-3-z5-social', 'Hai, bună!'),
  ('s3-2-3-z6-fizic', 'Hai pași pe iarbă'),
  ('s3-2-3-z6-mental', 'Uite — vântul se aude?'),
  ('s3-2-3-z6-resurse', 'Hai piatra fără sunet'),
  ('s3-2-3-z6-social', 'Hai unul lângă altul'),
  ('s3-2-3-z7-fizic', 'Hai — tu alegi plimbarea'),
  ('s3-2-3-z7-mental', 'Hai cartea: liniște'),
  ('s3-2-3-z7-resurse', 'Hai lumina stinsă'),
  ('s3-2-3-z7-social', 'Hai noapte bună'),
  ('s4-2-3-z1-fizic', 'Hai pumnul: deschis, strâns'),
  ('s4-2-3-z1-mental', 'Uite degetul'),
  ('s4-2-3-z1-resurse', 'Hai capacul pe cutie'),
  ('s4-2-3-z1-social', 'Hai, mână?'),
  ('s4-2-3-z2-fizic', 'Hai 3 lucruri cu mâna'),
  ('s4-2-3-z2-mental', 'Uite: mare, mic'),
  ('s4-2-3-z2-resurse', 'Hai boabele în bol'),
  ('s4-2-3-z2-social', 'Hai, mână? dă înapoi'),
  ('s4-2-3-z3-fizic', 'Hai degetele pe masă'),
  ('s4-2-3-z3-mental', 'Uite — unde e mânuța?'),
  ('s4-2-3-z3-resurse', 'Hai fermoarul'),
  ('s4-2-3-z3-social', 'Hai palma, blând'),
  ('s4-2-3-z4-fizic', 'Hai împinge cutia'),
  ('s4-2-3-z4-mental', 'Uite: unu, doi'),
  ('s4-2-3-z4-resurse', 'Hai ștergem masa'),
  ('s4-2-3-z4-social', 'Hai, mână? palmă pe palmă'),
  ('s4-2-3-z5-fizic', 'Hai pe mâini pe pernă'),
  ('s4-2-3-z5-mental', 'Uite: moale, aspru'),
  ('s4-2-3-z5-resurse', 'Hai șoseta la loc'),
  ('s4-2-3-z5-social', 'Hai mâna pe umăr'),
  ('s4-2-3-z6-fizic', 'Hai săpăm cu mâna'),
  ('s4-2-3-z6-mental', 'Uite piatra și frunza'),
  ('s4-2-3-z6-resurse', 'Hai găleata la loc'),
  ('s4-2-3-z6-social', 'Hai unul lângă altul'),
  ('s4-2-3-z7-fizic', 'Hai — tu ții ceva'),
  ('s4-2-3-z7-mental', 'Hai cartea: o pagină'),
  ('s4-2-3-z7-resurse', 'Hai haina pe cârlig'),
  ('s4-2-3-z7-social', 'Hai noapte bună'),
  ('s14-2-3-z5-fizic', 'Alergăm scurt pe drum'),
  ('s14-2-3-z5-mental', 'Repede și încet pe pași'),
  ('s14-2-3-z5-resurse', 'Pantofii la loc după drum'),
  ('s14-2-3-z5-social', 'Pași pe rând'),
  ('s14-2-3-z6-fizic', 'Plimbare scurtă pe drum'),
  ('s14-2-3-z6-mental', 'Ce vedem pe drum?'),
  ('s14-2-3-z6-resurse', 'Găleata / jucăria după plimbare'),
  ('s14-2-3-z6-social', 'Mergem paralel pe drum'),
  ('s14-2-3-z7-fizic', 'Plimbare liberă pe drumul scurt'),
  ('s14-2-3-z7-mental', 'Carte: drum și pași'),
  ('s14-2-3-z7-resurse', 'Pantofii pe cârlig / la ușă'),
  ('s14-2-3-z7-social', 'Noapte bună'),
  ('s15-2-3-z1-fizic', 'La masă pe scaun'),
  ('s15-2-3-z1-mental', 'Farfuria pe masă'),
  ('s15-2-3-z1-resurse', 'Farfuria la chiuvetă după'),
  ('s15-2-3-z1-social', 'Stăm la masă împreună'),
  ('s15-2-3-z2-fizic', 'Gustare cu mâna'),
  ('s15-2-3-z2-mental', 'Mâncare pe farfurie'),
  ('s15-2-3-z2-resurse', 'Șervețelul la loc'),
  ('s15-2-3-z2-social', 'Oferim gustarea'),
  ('s15-2-3-z3-fizic', 'Lingura la gură pe scurt'),
  ('s15-2-3-z3-mental', 'Lingură și farfurie'),
  ('s15-2-3-z3-resurse', 'Lingura la chiuvetă'),
  ('s15-2-3-z3-social', 'Mâncăm pe rând cu lingura'),
  ('s15-2-3-z4-fizic', 'Cărăm paharul la masă'),
  ('s15-2-3-z4-mental', 'Pahar lângă farfurie'),
  ('s15-2-3-z4-resurse', 'Paharul la chiuvetă după masă'),
  ('s15-2-3-z4-social', 'Mulțumesc la masă'),
  ('s15-2-3-z5-fizic', 'Spălăm mâinile înainte de masă'),
  ('s15-2-3-z5-mental', 'Înainte de masă, după masă'),
  ('s15-2-3-z5-resurse', 'Prosopul la loc după mâini'),
  ('s15-2-3-z5-social', 'Chemați la masă'),
  ('s15-2-3-z6-fizic', 'Gustare pe pătură / afară pe scurt'),
  ('s15-2-3-z6-mental', 'Ce mâncăm azi?'),
  ('s15-2-3-z6-resurse', 'Ambalajul / farfuria la loc'),
  ('s15-2-3-z6-social', 'Împărțim gustarea'),
  ('s15-2-3-z7-fizic', 'Plimbare liberă după masă'),
  ('s15-2-3-z7-mental', 'Carte: mâncare pe masă'),
  ('s15-2-3-z7-resurse', 'Farfuriile la loc'),
  ('s15-2-3-z7-social', 'Noapte bună')
) as v(id, titlu)
where a.id = v.id;
