-- PLAYFUL PILOT remap: invitation titles for S8–S10 L–D (84).
-- Does not insert new catalog rows; no other weeks/bands. Zero sounds.
update public.activities as a
set titlu = v.titlu
from (values
  ('s8-2-3-z1-fizic', 'Pași pe frunze'),
  ('s8-2-3-z1-mental', 'Uite: frunza'),
  ('s8-2-3-z1-resurse', 'Frunza jos, la loc'),
  ('s8-2-3-z1-social', 'Arătăm frunza'),
  ('s8-2-3-z2-fizic', 'Culegem trei frunze'),
  ('s8-2-3-z2-mental', 'Frunză mare — sau mică?'),
  ('s8-2-3-z2-resurse', 'Frunzele în găleată'),
  ('s8-2-3-z2-social', 'Ține frunza'),
  ('s8-2-3-z3-fizic', 'Săpăm puțin'),
  ('s8-2-3-z3-mental', 'Pământ uscat — sau ud?'),
  ('s8-2-3-z3-resurse', 'Lopățica la loc'),
  ('s8-2-3-z3-social', 'Săpăm unul lângă altul'),
  ('s8-2-3-z4-fizic', 'Noroi pe degete'),
  ('s8-2-3-z4-mental', 'Frunză — sau pământ?'),
  ('s8-2-3-z4-resurse', 'Mâinile pe prosop'),
  ('s8-2-3-z4-social', 'Mâini curate'),
  ('s8-2-3-z5-fizic', 'Frunze sus, pe scurt'),
  ('s8-2-3-z5-mental', 'Frunză galbenă — sau verde?'),
  ('s8-2-3-z5-resurse', 'Trei frunze la loc'),
  ('s8-2-3-z5-social', 'Pe care frunză?'),
  ('s8-2-3-z6-fizic', 'Pe poteca cu frunze'),
  ('s8-2-3-z6-mental', 'Frunze sus pe copac'),
  ('s8-2-3-z6-resurse', 'Găleata la loc'),
  ('s8-2-3-z6-social', 'Eu frunza, tu pe lângă'),
  ('s8-2-3-z7-fizic', 'Plimbare liberă'),
  ('s8-2-3-z7-mental', 'Cartea cu frunze'),
  ('s8-2-3-z7-resurse', 'Haina la loc'),
  ('s8-2-3-z7-social', 'Noapte bună'),
  ('s9-2-3-z1-fizic', 'Pași în aer'),
  ('s9-2-3-z1-mental', 'Aerul pe față'),
  ('s9-2-3-z1-resurse', 'Haina la ușă'),
  ('s9-2-3-z1-social', 'Arătăm vântul'),
  ('s9-2-3-z2-fizic', 'Alergăm cu vântul'),
  ('s9-2-3-z2-mental', 'Frunza se mișcă'),
  ('s9-2-3-z2-resurse', 'O frunză, apoi jos'),
  ('s9-2-3-z2-social', 'Suflăm ușor împreună'),
  ('s9-2-3-z3-fizic', 'Brațele: aripă'),
  ('s9-2-3-z3-mental', 'Unde e vântul?'),
  ('s9-2-3-z3-resurse', 'Punga se umflă'),
  ('s9-2-3-z3-social', 'Uite aerul'),
  ('s9-2-3-z4-fizic', 'Învârtim eșarfa'),
  ('s9-2-3-z4-mental', 'Eșarfa zboară puțin'),
  ('s9-2-3-z4-resurse', 'Eșarfa pe cârlig'),
  ('s9-2-3-z4-social', 'Ținem eșarfa doi'),
  ('s9-2-3-z5-fizic', 'Suflăm pe frunză'),
  ('s9-2-3-z5-mental', 'Aer cald — sau rece?'),
  ('s9-2-3-z5-resurse', 'Frunza înapoi afară'),
  ('s9-2-3-z5-social', 'Acum tu sufli'),
  ('s9-2-3-z6-fizic', 'Plimbare scurtă cu vânt'),
  ('s9-2-3-z6-mental', 'Copacul se mișcă'),
  ('s9-2-3-z6-resurse', 'Găleata jos pe iarbă'),
  ('s9-2-3-z6-social', 'Eu vântul, tu pe lângă'),
  ('s9-2-3-z7-fizic', 'Plimbare liberă'),
  ('s9-2-3-z7-mental', 'Cartea: cer și nori'),
  ('s9-2-3-z7-resurse', 'Haina sus pe cârlig'),
  ('s9-2-3-z7-social', 'Noapte bună'),
  ('s10-2-3-z1-fizic', 'Culegem trei de pe jos'),
  ('s10-2-3-z1-mental', 'Trei pe masă'),
  ('s10-2-3-z1-resurse', 'În cutie'),
  ('s10-2-3-z1-social', 'Ține unul'),
  ('s10-2-3-z2-fizic', 'Cărăm cutia cinci pași'),
  ('s10-2-3-z2-mental', 'Mare — sau mic?'),
  ('s10-2-3-z2-resurse', 'Mari în cutie'),
  ('s10-2-3-z2-social', 'Pe care-l punem?'),
  ('s10-2-3-z3-fizic', 'Șosetele de pe jos'),
  ('s10-2-3-z3-mental', 'Perechea de șosete'),
  ('s10-2-3-z3-resurse', 'Șosetele în sertar'),
  ('s10-2-3-z3-social', 'Uite perechea'),
  ('s10-2-3-z4-fizic', 'Cuburi de pe covor'),
  ('s10-2-3-z4-mental', 'Cuburi, pe rând'),
  ('s10-2-3-z4-resurse', 'Cuburile în cutie'),
  ('s10-2-3-z4-social', 'Ține un cub'),
  ('s10-2-3-z5-fizic', 'Două grămezi'),
  ('s10-2-3-z5-mental', 'Aici — sau aici?'),
  ('s10-2-3-z5-resurse', 'Totul la loc'),
  ('s10-2-3-z5-social', 'Acum tu sortezi'),
  ('s10-2-3-z6-fizic', 'Trei pietre afară'),
  ('s10-2-3-z6-mental', 'Piatră — sau frunză?'),
  ('s10-2-3-z6-resurse', 'Rămân afară'),
  ('s10-2-3-z6-social', 'Uite ce-am cules'),
  ('s10-2-3-z7-fizic', 'Plimbare liberă'),
  ('s10-2-3-z7-mental', 'Cartea cu multe'),
  ('s10-2-3-z7-resurse', 'Jucăriile în cutie'),
  ('s10-2-3-z7-social', 'Noapte bună')
) as v(id, titlu)
where a.id = v.id;
