-- soft EN cleanup S2-S4
insert into public.activities (id, banda, saptamana, zi, pilon, titlu, durata_min, mod_default, materiale, pasi, gata_cand, nota, tema_saptamana) values
('s3-2-3-z1-resurse', '2-3', 3, 1, 'resurse'::public.pillar, 'Jucăria care face zgomot', 4, 'A'::public.completion_mode, ARRAY['jucărie sonoră']::text[], ARRAY['Un sunet, apoi ne oprim.', '„Sunet. Gata.”']::text[], 'A reacționat la sunet.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Sunete și liniște'),
('s3-2-3-z3-fizic', '2-3', 3, 3, 'fizic'::public.pillar, 'Dans pe o melodie scurtă', 4, 'A'::public.completion_mode, ARRAY['muzică']::text[], ARRAY['30–60 sec muzică.', 'Ne oprim.']::text[], 'S-a mișcat pe ritm.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Sunete și liniște'),
('s3-2-3-z3-resurse', '2-3', 3, 3, 'resurse'::public.pillar, 'Oprim muzica', 3, 'A'::public.completion_mode, ARRAY['telefon/boxă']::text[], ARRAY['Apăsați oprirea împreună.', '„Oprit.”']::text[], 'A văzut oprirea.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Sunete și liniște'),
('s3-2-3-z5-resurse', '2-3', 3, 5, 'resurse'::public.pillar, 'Telefonul pe silențios (model)', 3, 'A'::public.completion_mode, ARRAY['telefon']::text[], ARRAY['Puneți pe silențios, vizibil.', '„Liniște acum.”']::text[], 'A văzut gestul.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Sunete și liniște'),
('s4-2-3-z2-resurse', '2-3', 4, 2, 'resurse'::public.pillar, 'Turnăm boabe mari în bol', 5, 'A'::public.completion_mode, ARRAY['boabe/piese mari, bol']::text[], ARRAY['Una câte una.', 'Ne oprim la oboseală.']::text[], 'A turnat ≥1.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Mâini și degete'),
('s4-2-3-z3-fizic', '2-3', 4, 3, 'fizic'::public.pillar, 'Bate ritm cu degetele pe masă', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Bateți ușor cu degetele.', 'El imită.']::text[], 'A atins masa ritmic.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Mâini și degete'),
('s4-2-3-z4-social', '2-3', 4, 4, 'social'::public.pillar, 'Palmă pe palmă, blând', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Oferiți palma.', 'Fără forțare.']::text[], 'A atins palma sau a refuzat.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Mâini și degete'),
('s4-2-3-z7-social', '2-3', 4, 7, 'social'::public.pillar, 'Pup / îmbrățișare de noapte', 3, 'A'::public.completion_mode, '{}'::text[], ARRAY['Oferiți; acceptă sau refuză — în regulă.', '„Noapte bună.”']::text[], 'A participat la ritual.', 'Vârsta 2–3: scurt, fără forțare; el poate refuza.', 'Mâini și degete')
on conflict (id) do update set titlu=excluded.titlu, materiale=excluded.materiale, pasi=excluded.pasi, gata_cand=excluded.gata_cand, nota=excluded.nota, tema_saptamana=excluded.tema_saptamana, durata_min=excluded.durata_min, mod_default=excluded.mod_default;